### ISSUE TITLE
Update RNA Workflow

### ISSUE THREAD

**Issue by mayabrandi** [Clinical-Genomics/cg_lims#113]
- [x] add placement maps
- [x] tapestation - new script to parse RIN-values
- [x] script to copy volume from sample
- [x] lite annat

**Comment by cesve** [comment]
Tests:

_**Step Tapestation Reception Control (RNA)**_

<img width="1422" alt="Screenshot 2021-11-09 at 14 20 47" src="https://user-images.githubusercontent.com/37171914/140931449-09ed23d1-d47b-4fd5-b209-7b17d77053b6.png">
_Placement map is correct with original well and original container._

<img width="662" alt="Screenshot 2021-11-09 at 14 18 41" src="https://user-images.githubusercontent.com/37171914/140931601-d57ca046-db8a-458f-b15c-ca162eb96247.png">
_The script takes the RINe-value from the file and adds it to column "RIN"._
