### ISSUE TITLE
depricate calculate_amount.py

### ISSUE THREAD

**Issue by mayabrandi** [Clinical-Genomics/cg_lims#116]
This script is being used in 

Protocol: **Initial QC Microbial v3** step **CG002 - Quantit QC (DNA)**. Button: **2. Calculate Amount**

Protocol: **Library validation QC wgs v3**. Step **CG002 - Qubit QC (Library Validation)** Button: **Prehyb QC - Calc Amount and Assign QC Flagg**

It should be replaced by https://github.com/Clinical-Genomics/cg_lims/blob/master/cg_lims/EPPs/udf/calculate/calculate_amount_ng.py.  

But it must have remove 3 as argument.

**Comment by barrystokman** [comment]
PR https://github.com/Clinical-Genomics/cg_lims/pull/117 has been deployed using 0 instead of 3, as requested

**Comment by AnnaLeinfelt** [comment]
Is this done?

**Comment by barrystokman** [comment]
The old EPP has been replaced and is not in use anymore. PR to archive that EPP here: https://github.com/Clinical-Genomics/clinical_EPPs/pull/226

**Comment by mayabrandi** [comment]
Can you close this one @barrystokman if its all done?

**Comment by barrystokman** [comment]
@mayabrandi Can you approve https://github.com/Clinical-Genomics/clinical_EPPs/pull/226 so I can merge it? After that I'll close this issue.

**Comment by barrystokman** [comment]
All PRs merged, closing
