### ISSUE TITLE
model for RNA samples to Arnold

### ISSUE THREAD

**Issue by mayabrandi** [Clinical-Genomics/cg_lims#127]
RNA samples are not being pushed to arnold

- Add model in cg_lims and adjust EPP to push RNA data
- Add model to Arnold

**Comment by mayabrandi** [comment]
@annaengstrom Let me know when you are ready to pick this one up!

**Comment by annaengstrom** [comment]
I have not worked so much with the RNA protocol in LIMS, but @idalindegaard has. Would you @mayabrandi  like us to look at the model, or have a meeting?
