### ISSUE TITLE
aggreagte reads gives error - transfere fom clinical_EPPs to cg_lims

### ISSUE THREAD

**Issue by mayabrandi** [Clinical-Genomics/cg_lims#128]
Lims Issue
---------------
aggreagte reads gives error 
`AttributeError: 'NoneType' object has no attribute 'udf'`

![Skärmavbild 2021-11-26 kl  11 57 58](https://user-images.githubusercontent.com/1306333/143570645-ca59902a-eeb4-41f8-80c3-e766739fd477.png)

the script that is running is part of clinical_EPPs. When fixing error handling transfer to cg_lims

**Comment by cesve** [comment]
@moahaegglund do you know if this still is a problem?
