### ISSUE TITLE
Vulnerability in Java-based logging utility. - Apply the critical software patch!

### ISSUE THREAD

**Issue by mayabrandi** [Clinical-Genomics/cg_lims#134]
https://support.illumina.com/bulletins/2021/121/investigation-of-log4j-vulnerability-with-clarity-lims.html

**Comment by mayabrandi** [comment]
maybe you want to do this @barrystokman?

**Comment by barrystokman** [comment]
I'm looking at the instructions, and I'm running the checks for the vulnerability (I have not stopped any running services!)
Short version: instructions seems clear, but `zip` needs to be installed on both `clinical-lims-stage.scilifelab.se` and `clinical-lims.scilifelab.se` before I can continue.

**Comment by barrystokman** [comment]
More information:
```
 Prerequisites

    Make sure to have root user access to the server instance (all the following commands should be executed with root user access).
    Make sure that the server is installed with zip utility. A zip command can be issued in the terminal to verify the install. The following will be observed if the utility is not installed:
     
    zip: command not found
```
On both `lims-stage` and `lims-prod`: `bash: zip: command not found`

```
JndiLookup class removal for Elasticsearch 6.2.4:

    Make sure that the JndiLookup.class exists in the log4j-core-2.9.1.jar used for Elasticsearch 6.2.4:
     
    jar tvf /usr/share/elasticsearch/lib/log4j-core-2.9.1.jar | grep -i JndiLookup
     
    Expected example output:
     
    2937 xxx xxx xx xx:xx:xx GMT xxx
    org/apache/logging/log4j/core/lookup/JndiLookup.class
```

On lims-stage:
```
(cg_lims) bash-4.2$ jar tvf /usr/share/elasticsearch/lib/log4j-core-2.9.1.jar | grep -i JndiLookup
  2937 Sun Sep 17 22:53:00 CEST 2017 org/apache/logging/log4j/core/lookup/JndiLookup.class
```

On lims-prod (note: I had to add `/opt/gls/clarity/bin` to $PATH):
```
(base) bash-4.2$ jar tvf /usr/share/elasticsearch/lib/log4j-core-2.9.1.jar | grep -i JndiLookup
  2937 Sun Sep 17 22:53:00 CEST 2017 org/apache/logging/log4j/core/lookup/JndiLookup.class
```

```
JndiLookup class removal for Search Indexer:

    Make sure that the JndiLookup.class exists in the log4j-core-2.10.0.jar used for Search Indexer:
     
    jar tvf /opt/gls/clarity/search-indexer/lib/log4j-core-2.10.0.jar | grep -i JndiLookup
     
    Expected example output:
     
    2937 xxx xxx xx xx:xx:xx GMT xxx
    + org/apache/logging/log4j/core/lookup/JndiLookup.class
```
On lims-stage:
```
(cg_lims) bash-4.2$ jar tvf /opt/gls/clarity/search-indexer/lib/log4j-core-2.10.0.jar | grep -i JndiLookup
  2937 Sun Nov 19 00:50:42 CET 2017 org/apache/logging/log4j/core/lookup/JndiLookup.class
```

On lims-prod (note: I had to add `/opt/gls/clarity/bin` to $PATH):
```
(base) bash-4.2$ jar tvf /opt/gls/clarity/search-indexer/lib/log4j-core-2.10.0.jar | grep -i JndiLookup
  2937 Sun Nov 19 00:50:42 CET 2017 org/apache/logging/log4j/core/lookup/JndiLookup.class
```

**Comment by barrystokman** [comment]
Issue for ZIP installation: https://github.com/Clinical-Genomics/IT-issues/issues/438

**Comment by barrystokman** [comment]
## `clinical-lims-stage.scilifelab.se`

### 1. Stop all the Clarity services on the server instance before the change:
`/opt/gls/clarity/bin/run_clarity.sh stop`

### 2. JndiLookup class removal for Elasticsearch 6.2.4:
#### a. Make sure that the JndiLookup.class exists in the log4j-core-2.9.1.jar used for Elasticsearch 6.2.4:
`jar tvf /usr/share/elasticsearch/lib/log4j-core-2.9.1.jar | grep -i JndiLookup`

Expected example output:
``` 
2937 xxx xxx xx xx:xx:xx GMT xxx
org/apache/logging/log4j/core/lookup/JndiLookup.class
```
![image](https://user-images.githubusercontent.com/26384108/148782279-634f4e30-8342-4917-a987-2fc208bd611f.png)
✔️ 

#### b. Back up the log4j-core-2.9.1.jar to a designated directory. Make sure that the zip is created in the backup directory:
`zip /home/glsai/Log4j_BACKUP/backup-log4j-core-es.zip /usr/share/elasticsearch/lib/log4j-core-2.9.1.jar`

![image](https://user-images.githubusercontent.com/26384108/148783131-fa44a9c0-fde8-4586-98aa-3d4a8947362a.png)
✔️ 

#### c. Remove the JndiLookup.class from the log4j-core-2.9.1.jar:
 
`zip -d /usr/share/elasticsearch/lib/log4j-core-2.9.1.jar org/apache/logging/log4j/core/lookup/JndiLookup.class`
 
Expected example output:
 
`deleting: org/apache/logging/log4j/core/lookup/JndiLookup.class`
 
NOTE: If running the previous command produces a series of lines that look like the following, this has no effect on the removal of the vulnerable class and can safely be ignored:
 
`zip warning: Local Version Needed To Extract does not match CD: org/apache/logging/log4j/core/util/WatchManager$WatchRunnable.class`

![image](https://user-images.githubusercontent.com/26384108/149005439-5e341a1f-3167-4d99-8105-20b8e8e0cc90.png)
✔️ 
 
#### d. Verify if JndiLookup.class is removed:
 
`jar tvf /usr/share/elasticsearch/lib/log4j-core-2.9.1.jar | grep -i JndiLookup`
 
No expected output from the command.
![image](https://user-images.githubusercontent.com/26384108/149005581-6a628c95-7544-4b43-a41e-1656842e362e.png)
✔️ 

### 3. JndiLookup class removal for Search Indexer:

#### a. Make sure that the JndiLookup.class exists in the log4j-core-2.10.0.jar used for Search Indexer:
     
`jar tvf /opt/gls/clarity/search-indexer/lib/log4j-core-2.10.0.jar | grep -i JndiLookup`
     
Expected example output:
```     
2937 xxx xxx xx xx:xx:xx GMT xxx
+ org/apache/logging/log4j/core/lookup/JndiLookup.class
```
![image](https://user-images.githubusercontent.com/26384108/148784581-e58e51c9-dda2-45ee-bb44-1dc0aa24caec.png)
✔️ 
     
#### b. Back up the log4j-core-2.10.0.jar to a designated directory. Make sure that the zip is created in the backup directory:
     
`zip /home/glsai/Log4j_BACKUP/backup-log4j-core-searchindexer.zip /opt/gls/clarity/search-indexer/lib/log4j-core-2.10.0.jar`
![image](https://user-images.githubusercontent.com/26384108/148785045-5606a9e8-75fc-402e-a7b7-c2e6dce8ed1b.png)
✔️ 
     
#### c. Remove the JndiLookup.class from the log4j-core-2.10.0.jar:
     
`zip -d /opt/gls/clarity/search-indexer/lib/log4j-core-2.10.0.jar org/apache/logging/log4j/core/lookup/JndiLookup.class`
     
Expected example output:
The output should include the following line as output:

`deleting: org/apache/logging/log4j/core/lookup/JndiLookup.class`
     
NOTE: If running the previous command produces a series of lines that look like the following, this has no effect on the removal of the vulnerable class and can safely be ignored:
     
`zip warning: Local Version Needed To Extract does not match CD: org/apache/logging/log4j/core/util/WatchManager$WatchRunnable.class`

![image](https://user-images.githubusercontent.com/26384108/149005892-ded16857-fd0b-4f4f-bbeb-7e475ab2b6f7.png)
✔️ 

#### d. Verify if JndiLookup.class is removed:
     
`jar tvf /opt/gls/clarity/search-indexer/lib/log4j-core-2.10.0.jar | grep -i JndiLookup`
     
There should be no output from the command.
![image](https://user-images.githubusercontent.com/26384108/149005974-76286736-193c-4d48-b958-fde501cae6f9.png)
✔️

 ### 4. Start the Clarity services on the server instance and verify if UI is accessible:
 `/opt/gls/clarity/bin/run_clarity.sh start`
![image](https://user-images.githubusercontent.com/26384108/149006535-81b1ff75-b16a-47a5-b473-0e2ad789825f.png)
✔️ 

## `clinical-lims.scilifelab.se`

### 1. Stop all the Clarity services on the server instance before the change:
`/opt/gls/clarity/bin/run_clarity.sh stop`

### 2. JndiLookup class removal for Elasticsearch 6.2.4:
#### a. Make sure that the JndiLookup.class exists in the log4j-core-2.9.1.jar used for Elasticsearch 6.2.4:
`jar tvf /usr/share/elasticsearch/lib/log4j-core-2.9.1.jar | grep -i JndiLookup`

Expected example output:
``` 
2937 xxx xxx xx xx:xx:xx GMT xxx
org/apache/logging/log4j/core/lookup/JndiLookup.class
```
![image](https://user-images.githubusercontent.com/26384108/148958983-b5c562d9-5255-4834-9094-e2ee28d0ad4c.png)
✔️ 

#### b. Back up the log4j-core-2.9.1.jar to a designated directory. Make sure that the zip is created in the backup directory:

`zip /home/glsai/Log4j_BACKUP/backup-log4j-core-es.zip /usr/share/elasticsearch/lib/log4j-core-2.9.1.jar`

![image](https://user-images.githubusercontent.com/26384108/148959304-9eeeaeec-59c9-4884-b95a-2d99c1f91044.png)
✔️ 

#### c. Remove the JndiLookup.class from the log4j-core-2.9.1.jar:
 
`zip -d /usr/share/elasticsearch/lib/log4j-core-2.9.1.jar org/apache/logging/log4j/core/lookup/JndiLookup.class`
 
Expected example output:
 
`deleting: org/apache/logging/log4j/core/lookup/JndiLookup.class`
 
NOTE: If running the previous command produces a series of lines that look like the following, this has no effect on the removal of the vulnerable class and can safely be ignored:
 
`zip warning: Local Version Needed To Extract does not match CD: org/apache/logging/log4j/core/util/WatchManager$WatchRunnable.class`

![image](https://user-images.githubusercontent.com/26384108/149009701-7067cea9-4fce-42ca-989f-a2c791937c4a.png)
✔️ 
 
#### d. Verify if JndiLookup.class is removed:
 
`jar tvf /usr/share/elasticsearch/lib/log4j-core-2.9.1.jar | grep -i JndiLookup`
 
![image](https://user-images.githubusercontent.com/26384108/149009803-e00901d7-4c2f-47f6-b506-ecf40c68e1f3.png)
✔️ 

No expected output from the command.
### 3. JndiLookup class removal for Search Indexer:

#### a. Make sure that the JndiLookup.class exists in the log4j-core-2.10.0.jar used for Search Indexer:
     
`jar tvf /opt/gls/clarity/search-indexer/lib/log4j-core-2.10.0.jar | grep -i JndiLookup`
     
Expected example output:
```     
2937 xxx xxx xx xx:xx:xx GMT xxx org/apache/logging/log4j/core/lookup/JndiLookup.class
```
![image](https://user-images.githubusercontent.com/26384108/148959586-4006ab5c-c5ff-4ddf-8f3a-21078986bc74.png)
✔️ 

#### b. Back up the log4j-core-2.10.0.jar to a designated directory. Make sure that the zip is created in the backup directory:
     
`zip /home/glsai/Log4j_BACKUP/backup-log4j-core-searchindexer.zip /opt/gls/clarity/search-indexer/lib/log4j-core-2.10.0.jar`
![image](https://user-images.githubusercontent.com/26384108/148960100-c809dc2c-d386-4a13-a94f-c6730f5b3959.png)
✔️ 
#### c. Remove the JndiLookup.class from the log4j-core-2.10.0.jar:
     
`zip -d /opt/gls/clarity/search-indexer/lib/log4j-core-2.10.0.jar org/apache/logging/log4j/core/lookup/JndiLookup.class`
     
Expected example output:
The output should include the following line as output:

`deleting: org/apache/logging/log4j/core/lookup/JndiLookup.class`
  
NOTE: If running the previous command produces a series of lines that look like the following, this has no effect on the removal of the vulnerable class and can safely be ignored:
     
`zip warning: Local Version Needed To Extract does not match CD: org/apache/logging/log4j/core/util/WatchManager$WatchRunnable.class`

![image](https://user-images.githubusercontent.com/26384108/149009941-4a90e2b0-109e-4cef-a7a3-8d6b684caaac.png)
✔️ 

#### d. Verify if JndiLookup.class is removed:
     
`jar tvf /opt/gls/clarity/search-indexer/lib/log4j-core-2.10.0.jar | grep -i JndiLookup`
     
There should be no output from the command.
![image](https://user-images.githubusercontent.com/26384108/149010002-edb6d85c-72e4-49da-abb0-672a6abcccaa.png)
✔️ 
 ### 4. Start the Clarity services on the server instance and verify if UI is accessible:
 `/opt/gls/clarity/bin/run_clarity.sh start`
![image](https://user-images.githubusercontent.com/26384108/149010266-3878ec86-9bea-4b78-9d25-65fd39e8f22b.png)
✔️

**Comment by barrystokman** [comment]
Fix applied, everything is up and running again, closing this issue.

**Comment by henrikstranneheim** [comment]
@barrystokman well done!
