### ISSUE TITLE
Remove/add process UDF's in Twist wf

### ISSUE THREAD

**Issue by cesve** [Clinical-Genomics/cg_lims#135]
Lims Issue
---------------

**Work Flow:** TWIST v5
**Protocol:** Target Enrichment TWIST v2
**Step:** Hybridize Library TWIST, Capture and Wash TWIST & Bead Purification (post hybridization) TWIST

**Description:** As the enrichment kit has changed we need to also change LIMS accordingly. We need to make changes in Arnold at the same time.

1. Step Hybridize Library TWIST:
- [x] Remove UDF Twist enrichment kit"
- [x] Remove UDF "Vapor Lock"

2. Step Capture and Wash TWIST
- [x] Remove UDF "Twist enrichment kit.
- [x] Add UDF "Twist Binding and Purification beads
- [x] Add UDF "Twist Wash Buffers"

3. Step Bead Purification (post hybridization) TWIST
- [x] Remove UDF "Twist enrichment kit".
- [x] Add UDF "Twist Binding and Purification beads

**Comment by cesve** [comment]
@mayabrandi can we look at this on Thursday next week?

@EmiliaRegazzoni & @VasKyriak did I understand it correct?

**Comment by VasKyriak** [comment]
Yes, I think it looks fine @cesve!
One more thing is the **Vapor Lock** in the **Hybridize Library step**. It is included in the same Kit as the **Hybridization Mix**, and maybe it is redundant to have two different boxes for that. So I think you can remove that one also.

**Comment by EmiliaRegazzoni** [comment]
Yes, that both sounds great @cesve and @VasKyriak!
