### ISSUE TITLE
Add Quantit step in RNA v2 wf

### ISSUE THREAD

**Issue by cesve** [Clinical-Genomics/cg_lims#136]
Lims Issue
---------------

**Work Flow:** RNA v2
**Protocol:** Initial QC (RNA)
**Step:** New step

**Description:** Add a Quantit step in the Reception control protocol in the RNA v2 wf. The step should include scripts to extract concentrations from an excel file. A placement map with original well and container is also needed.

**Comment by idalindegaard** [comment]
Thank you @cesve! I guess it's also worth mentioning that this step will replace Step 2 Qubit QC (RNA) in the protocol Initial QC (RNA).

**Comment by cesve** [comment]
Quantit-fil
[211230rnatest1_lumousBR_controls.xlsx](https://github.com/Clinical-Genomics/cg_lims/files/7869911/211230rnatest1_lumousBR_controls.xlsx)
e

**Comment by cesve** [comment]
In order to add the Quantit step a new version of RNA had to be created, this is named **RNA v3**

A new protocol that includes the Quantit step has been made, **Initial QC (RNA) v2**

New master step **Quantit QC (RNA) v1**
And new step **Quantit QC (RNA)**

The other steps in this protocol are the same as in RNA v2.

**_Test of Quantit QC (RNA)_**
![Screenshot 2022-01-26 at 11 30 56](https://user-images.githubusercontent.com/37171914/151190207-c7e789af-9ff2-4d89-87b7-4653ffd07105.png)
![Screenshot 2022-01-26 at 11 32 22](https://user-images.githubusercontent.com/37171914/151190230-71fe1563-9e7f-4e8f-8ac0-e4e9c9a71771.png)
![Screenshot 2022-01-26 at 11 32 47](https://user-images.githubusercontent.com/37171914/151190249-5ac83346-867a-4457-b73c-df18ccd70302.png)
![Screenshot 2022-01-26 at 11 33 18](https://user-images.githubusercontent.com/37171914/151190328-9da12fdf-eccc-4cf0-92bf-780165302081.png)
![Screenshot 2022-01-26 at 11 33 51](https://user-images.githubusercontent.com/37171914/151190338-9eb6da55-1b9d-40f9-b451-8b4b298d60fa.png)
<img width="264" alt="Screenshot 2022-01-26 at 11 34 11" src="https://user-images.githubusercontent.com/37171914/151190344-33d8dbcc-222a-4f21-af68-618e25ecb6c4.png">
![Screenshot 2022-01-26 at 11 34 53](https://user-images.githubusercontent.com/37171914/151190346-42074fe4-1aca-4843-b521-5da927959474.png)
![Screenshot 2022-01-26 at 11 36 06](https://user-images.githubusercontent.com/37171914/151190352-2896618e-d629-4baa-8985-cd135686bd86.png)
![Screenshot 2022-01-26 at 11 38 06](https://user-images.githubusercontent.com/37171914/151190357-3aa9a069-89d9-44c1-b050-0607e89ce905.png)
![Screenshot 2022-01-26 at 11 40 51](https://user-images.githubusercontent.com/37171914/151190361-64e14fe6-7c7a-448b-baae-542a4c1fc7d9.png)

**Comment by cesve** [comment]
Conclusion: The new protocol and step works as expected.

**Comment by idalindegaard** [comment]
@cesve Amazing work Cecilia! Thank you!
