### ISSUE TITLE
Add sample UDF to step in LIMS

### ISSUE THREAD

**Issue by cesve** [Clinical-Genomics/cg_lims#138]
Lims Issue
---------------

**Work Flow:** TWIST v5
**Protocol:** Library Validation QC TWIST v2
**Step:** Qubit QC (Library Validation) TWIST, Quantit QC (Library Validation) TWIST and Tapestation QC TWIST

**Description:** Copy "DIN value"  (of derived sample) from input artifact of "Aggregate QC (DNA) TWIST" to messurements in the steps above.

Create new epp using copy/artifact_to_artifact.py

**Comment by cesve** [comment]
UDF's have been added @mayabrandi .

**Comment by cesve** [comment]
@mayabrandi can you help me to check the DIN-value UDF? We might need some sort of script to add the value..?

**Comment by cesve** [comment]
**_Test of new script:_**

10 samples were tested in the 3 steps. All samples got the DIN-value that was registered in the _Initial QC TWIST v3_ protocol step _Tapestation Reception Control TWIST_.

![Screenshot 2022-03-11 at 08 26 49](https://user-images.githubusercontent.com/37171914/157823541-08e126fd-7af5-4205-a4be-c8e36b0c492c.png)
![Screenshot 2022-03-11 at 08 28 15](https://user-images.githubusercontent.com/37171914/157823573-f24082d5-0cd0-424d-a242-51e6ec578836.png)
![Screenshot 2022-03-11 at 08 28 40](https://user-images.githubusercontent.com/37171914/157823605-177f00d6-cf53-445d-9233-9218e2cb582f.png)
![Screenshot 2022-03-11 at 08 30 47](https://user-images.githubusercontent.com/37171914/157823683-29f1364a-fd82-4872-84d3-93d15b2e62fb.png)
![Screenshot 2022-03-11 at 08 36 43](https://user-images.githubusercontent.com/37171914/157823699-1469af44-09c4-4473-a299-778c437f801d.png)
![Screenshot 2022-03-11 at 08 37 16](https://user-images.githubusercontent.com/37171914/157823719-28707567-e189-480b-a367-4ad9e498e91d.png)

**Comment by mayabrandi** [comment]
Automation;
![Skärmavbild 2022-03-11 kl  09 26 20](https://user-images.githubusercontent.com/1306333/157830304-8fc9dcdb-b2bb-4627-820c-463ccfcdaa7b.png)
