### ISSUE TITLE
Change QC-criteria in initial QC Twist

### ISSUE THREAD

**Issue by cesve** [Clinical-Genomics/cg_lims#139]
Lims Issue
---------------

**Work Flow:** TWIST v5
**Protocol:** Initial QC TWIST v3
**Step:** Qubit QC (DNA) TWIST and Quantit QC (DNA) TWIST

**Description:** We've changed a QC-criteria in these steps in the script "Calculate Amounts". Before we had a criteria that if sample source is not equal to cfDNA the minimum amount should be 300 ng. This should be changed to 500 ng.

**Comment by mayabrandi** [comment]
https://github.com/Clinical-Genomics/cg_lims/pull/140
