### ISSUE TITLE
Move method document for Demultiplexing to other step in LIMS

### ISSUE THREAD

**Issue by moahaegglund** [Clinical-Genomics/cg_lims#143]
Lims Issue
---------------

**Work Flow:** Delivery v1
**Protocol:** Delivery
**Step:** Delivery

**Description:**
The method document "Demultiplexing" is currently possible to choose as a method in `Delivery`. This protocol can be removed from this step and instead added to the step `Bcl Conversion & Demultiplexing (Nova Seq)`.

**Comment by mayabrandi** [comment]
done
