### ISSUE TITLE
Addition of priority in "Define Run Format and Calculate Volumes (NovaSeq)" step

### ISSUE THREAD

**Issue by AnnaLeinfelt** [Clinical-Genomics/cg_lims#147]
Lims Issue
---------------

**Work Flow:** NovaSeq v3
**Protocol:** Define Run Format and Calculate Volumes (NovaSeq)
**Step:** Define Run Format and Calculate Volumes (NovaSeq

**Description:** Addition of priority in "Define Run Format and Calculate Volumes (NovaSeq)" step

See pictures. It would be nice to have the priority information after column **Sequencing Analysis**

<img width="624" alt="Screenshot 2022-01-31 at 14 23 16" src="https://user-images.githubusercontent.com/37171709/151801436-9b77f53e-70db-476a-b322-8596c3e6ccb8.png">

<img width="643" alt="Screenshot 2022-01-31 at 14 23 28" src="https://user-images.githubusercontent.com/37171709/151801476-2a3566b9-c95b-4036-839c-2aae33287ebb.png">

<img width="539" alt="Screenshot 2022-01-31 at 14 23 43" src="https://user-images.githubusercontent.com/37171709/151801504-8ca7fcfe-51dd-4e7c-b957-9395c6c53a33.png">

**Comment by mayabrandi** [comment]
done
