### ISSUE TITLE
NIPT RC

### ISSUE THREAD

**Issue by AnnaLeinfelt** [Clinical-Genomics/cg_lims#148]
Lims Issue
---------------

**Work Flow:** Reception Control NIPT v1
**Protocol:** Reception control NIPT
**Step:** Here to!

**Description:** Today samples enter NIPT workflow as samples. I would like them to be grouped and connected to the ticket ID (as in Initial QC wgs v4, protocol Reception Control v3).
Why? Sometimes more then one NIPT batch are processed at the same time and then there is a risk when manually choosing the samples to process. (As samples are already pooled there is no "list of samples" to tick off).
See pictures below

NIPT today
<img width="611" alt="Screenshot 2022-01-31 at 14 27 28" src="https://user-images.githubusercontent.com/37171709/151802487-b51ec616-e4b9-4f73-9fcd-8eeef0393de6.png">

WGS samples today
<img width="589" alt="Screenshot 2022-01-31 at 14 27 46" src="https://user-images.githubusercontent.com/37171709/151802544-71d14200-a489-4f78-8f2b-0b1e8244f502.png">

**Comment by mayabrandi** [comment]
done
