### ISSUE TITLE
Generation of new File for Hamilton (Buffer exchange)

### ISSUE THREAD

**Issue by cesve** [Clinical-Genomics/cg_lims#150]
Lims Issue
---------------

**Work Flow:** TWIST v5
**Protocol:** Pre Processing TWIST v2
**Step:** Buffer Exchange TWIST

**Description:** This step will be automated in the lab. We need a file for this.

- [ ] The file should be in format *txt and comma separated columns
- [ ] The following columns are needed: 

**_"UDF" --> Column heading_**
Input Container Barcode --> Input Plate Barcode (see comment below)
LIMS ID (submitted Sample) --> LIMS ID
Well --> Well ID
Sample Volume (ul) --> Volume Sample
Volume Beads (ul) --> Volume Beads
Volume H2O (ul) --> Volume Elution buffer

[SamplesTest8.txt](https://github.com/Clinical-Genomics/cg_lims/files/8114801/SamplesTest8.txt)

The rows in the file should be sorted on well position like: A1, B1, C1, A2, B2, C2...

**Comment by cesve** [comment]
If a UDF in lims doesn't have a value it would be great if it's a a dash (-) in the file.

**Comment by cesve** [comment]
Create a new "Derived sample" UDF named "Input Container Barcode" but don't make it visible in the step.

In the file: use this UDF "Input Container Barcode" as "Input Plate Barcode".

Thanks!

**Comment by Karl-Svard** [comment]
### **Configuration changes done**

- Added new Derived Sample UDF **Input Container Barcode**
- Renamed file placeholder 2 in master step Buffer Exchange v2 to **Hamilton File**
- Created new automation named **Generate Hamilton File**, which is used in step Buffer Exchange TWIST for TWIST v7.
- Created new automation named **Copy Barcode from Sample Placement**, which is used on entry to step Buffer Exchange TWIST for TWIST v7. Uses the artifact-to-artifact EPP with the new flag --ignore-fail
