### ISSUE TITLE
RNA v3 - Size (bp) is not copied to the Aggregate QC step in Library Validation QC RNA (post norm) from Library Validation QC (RNA)

### ISSUE THREAD

**Issue by idalindegaard** [Clinical-Genomics/cg_lims#154]
Lims Issue
---------------

**Work Flow:** RNA v3
**Protocol:** Library Validation QC (RNA) and Library Validation QC RNA (post norm)
**Step:** Tapestation QC (RNA) (in Library Validation QC (RNA)) and Aggregate QC (Library Validation) (RNA) (in Library Validation QC RNA (post norm))

..sorry for all the parenthesis, I hope it's clear what I mean

**Description:** Describe issue here!!!

The Library Validation QC for RNA consist of three protocols:
- Library Validation QC (RNA)
- Normalization of RNA samples for sequencing
- Library Validation QC RNA (post norm)

The first and third protocols look exactly the same, with a Tapestation, Qubit, Quantit and Aggregation step. 
We measure samples with Tapestation in the first protocol and not in the third, but when we come to the Aggregation step in the third protocol we want the values (size bp) from the first protocol. Now we have to do this manually. 

Is it possible to change this without remaking the whole workflow?

**Comment by cesve** [comment]
I think the easiest solution is to add the sizes in the second QC protocol: Library Validation QC RNA (post norm)

We can remove TapeStation step from the first protocol (Library Validation QC (RNA)). You can still do the Tapestation on the undiluted samples but register the sizes in the second protocol.

What do you think @idalindegaard ?

**Comment by idalindegaard** [comment]
I see, okay @cesve ! So are you sure that LIMS won't require the size in the first Aggregation step then? I mean to be able to move on?

**Comment by cesve** [comment]
Yes I'm sure!

**Comment by idalindegaard** [comment]
Yes, it worked today. So should we close this issue and do that from now on?

**Comment by cesve** [comment]
Yes, let's do that!
