### ISSUE TITLE
1464, 1057 and 1717 ready to be merged and used in Atlas

### ISSUE THREAD

**Issue by amandaraud** [Clinical-Genomics/cg_lims#155]
Lims Issue
---------------

**Work Flow:** WGS PCR free v5
**Protocol:** TruSeq DNA PCR-free Library Prep
**Step:** 

- [x] Aliquot Samples for Covaris, 
- [x] Fragment DNA (TruSeq DNA), 
- [x] End repair Size selection A-tailing and Adapter ligation (TruSeq PCR-free DNA)

**Description:** AM document 1464 Automated TruSeq DNA PCR-free library preparation method has been moved to Atlas and is ready to be merged and used.

**Comment by AnnaLeinfelt** [comment]
@amandaraud Is the low input document used in the same step, ie should we wait for that document?

**Comment by amandaraud** [comment]
Yes, good point! The two methods use the same steps.

**Comment by amandaraud** [comment]
> @amandaraud Is the low input document used in the same step, ie should we wait for that document?

Yes, good point! The two methods use the same steps.

**Comment by AnnaLeinfelt** [comment]
Ok, I'll try to add the Low inout document to Atlas today then.

**Comment by AnnaLeinfelt** [comment]
@amandaraud I've PRs for both the Lucigen documentation and manual truseq.

**Comment by cesve** [comment]
MB will teach KS and CS how this is done.

**Comment by mayabrandi** [comment]
I need to know the name of the method documents in atlas or the paths

**Comment by amandaraud** [comment]
The name in Atlas is _Automated TruSeq DNA PCR-free library preparation._ 
Path: production/lab/library_prep_methods/automated_preps/automated_truseq/

**Comment by RasmusBurge-CG** [comment]
@amandaraud 1464 ready to be fully transfered to atlas. Method is able to be selected in lims. Will continue with 1057 and 1717

**Comment by RasmusBurge-CG** [comment]
@AnnaLeinfelt @amandaraud  The following, are also avaliable in LIMS: 

 1464:
Automated TruSeq DNA PCR-free library preparation.
Path: /production/lab/library_prep_methods/automated_preps/automated_truseq/

 1057:
Manual TruSeq DNA PCR-free library preparation
Path: /production/lab/library_prep_methods/manual_preps/manual_truseq/

 1717:
NxSeq® AmpFREE Low DNA Library Kit (Lucigen)
Path: /production/lab/library_prep_methods/manual_preps/manual_lucigen/production/lab/library_prep_methods/manual_preps/manual_lucigen/

**Comment by AnnaLeinfelt** [comment]
Nice work!

@amandaraud Can you create PRs to remove the WIP heading?
And for the 1464 make a new edition according to these instructions? https://atlas.scilifelab.se/about/move_from_am_to_atlas/

(I've already made one for 1057). 

MASA has 1717 on review in AM, I've contacted her.

**Comment by RasmusBurge-CG** [comment]
- [ ] Remove 1464, 1057 and 1717 in step End repair _Size selection A-tailing and Adapter ligation (TruSeq PCR-free DNA)_

**Comment by AnnaLeinfelt** [comment]
> @AnnaLeinfelt @amandaraud Let me know when they are "removed" from AM and the I will remove them in LIMS:)

Hi @RasmusBurge-CG! Instructions archived in AM!

**Comment by RasmusBurge-CG** [comment]
Perfect! Will remove them asap

**Comment by RasmusBurge-CG** [comment]
> * [x]  Remove 1464, 1057 and 1717 in step _End repair Size selection A-tailing and Adapter ligation (TruSeq PCR-free DNA)_

All references to the old document is done, the new atlas docs are fully in production.
