### ISSUE TITLE
New validation and normalization protocols for the SARS-CoV-2 wf

### ISSUE THREAD

**Issue by cesve** [Clinical-Genomics/cg_lims#158]
Lims Issue
---------------

**Work Flow:** SARS-CoV-2 v3
**Protocol:**
**Step:**

**Description:**

Today we do normalization calculations in an excel sheet (see document [Calculation sheet for dilution and normalization of samples and libraries](https://atlas.scilifelab.se/production/lab/supporting_procedures/calculation_sheet_for_norm_and_dil/)), which makes the concentrations and calculations less traceable in LIMS. We would like to have the same setup for normalization as in other library preparation methods, with a Library validation protocol, normalization protocol and finally a Library validation (post norm) protocol. 

Current set-up:
![Screenshot 2022-02-22 at 15 08 22](https://user-images.githubusercontent.com/37171914/155148779-96092007-bb2e-453f-8c51-650784bab07f.png)

- [x] New protocol: Library Validation QC (Cov) v2
Same as Library Validation QC (Cov) v1 but without the TapeStation step

- [x] New protocol: Normalization of pool for sequencing (Cov) v1
Step: Normalization of pool for sequencing (Cov) v1

- [x] New protocol: Library Validation QC (post norm) (Cov) v1
This should be an exact copy of Library Validation QC (Cov) v1 with the TapeStation step

**Comment by idalindegaard** [comment]
The testing of the new protocols will be performed in the verification issue of the new version of this workflow, see #376

**Comment by idalindegaard** [comment]
**New protocol and step set-up as a reference to the old:**

<img width="586" alt="Screenshot 2023-05-15 at 14 49 15" src="https://github.com/Clinical-Genomics/cg_lims/assets/82438141/c38299dd-e690-4112-81c5-76499abf67b1">
<img width="829" alt="Screenshot 2023-05-15 at 14 49 30" src="https://github.com/Clinical-Genomics/cg_lims/assets/82438141/87c64bd3-5ec9-4959-8787-9eed62a4b756">

<img width="829" alt="Screenshot 2023-05-15 at 14 49 52" src="https://github.com/Clinical-Genomics/cg_lims/assets/82438141/db3ac6d7-1fe3-4bc5-8018-c4c898fbc649">

<img width="829" alt="Screenshot 2023-05-15 at 14 50 08" src="https://github.com/Clinical-Genomics/cg_lims/assets/82438141/f0315390-77f2-4442-b02d-c389973bd328">

**Comment by idalindegaard** [comment]
Closing this issue; the rest is being recorded in the verification issue #376
