### ISSUE TITLE
New PCR machine (Pyder), add to relevant workflows

### ISSUE THREAD

**Issue by amandaraud** [Clinical-Genomics/cg_lims#174]
Lims Issue
---------------

**Work Flow:** Full name here please!
**Protocol:** And here!
**Step:** Here to!

**Description:** The new PCR machine Pyder in POST has been verified and needs to be added to all relevant workflows in Lims.

**Comment by RasmusBurge-CG** [comment]
[x] Tested on stage

Pyder is now available in:

- Twist steps:

- [x] Amplify Captured Libraries TWIST v2

- [x] KAPA Library Preparation TWIST v1

Covid steps:

- [x] Library Preparation (Cov) v1

Micro:

- [x] CG002 - Microbial Library Prep (Nextera)


Keeping this issue open until feedback from users.
