### ISSUE TITLE
Transfer qPCR_dilution.py

### ISSUE THREAD

**Issue by mayabrandi** [Clinical-Genomics/cg_lims#186]
qPCR_dilution.py
 Calculate Concentration And Assign QC

**Comment by RasmusBurge-CG** [comment]
When doing this, also make the script check what outlier to remove. Lab staff often have to download the raw qPCR file and remove outliers manually.

**Comment by RasmusBurge-CG** [comment]
Filename should be an input to the EPP, also dilution within replicates and between dilutions. In my mind, the config in LIMS would look something like this:

`... EPPs udf calculate qPCR-calc -fName 'foobar' -dil '0.5' -dil_bet '0.5'`


Also, when a replicate needs to be removed it should test what extreme to remove. Quite often the script removes an outlier and fails the sample even though if it had removed the other extreme the sample would have passed.

**Comment by RasmusBurge-CG** [comment]
See PR: https://github.com/Clinical-Genomics/cg_lims/pull/304

**Comment by Karl-Svard** [comment]
Remember to close deviation https://github.com/Clinical-Genomics/Deviations/issues/328 when this is complete.

**Comment by idalindegaard** [comment]
Remember to change the script also in WF "Development Projects v3" > Protocol "Library Validation QC (Dev) v3" > Step "qPCR QC (Library Validation) (Dev)"

**Comment by AnnaLeinfelt** [comment]
What is the status of this?

**Comment by Karl-Svard** [comment]
It's still a work in progress. Some bugs were encountered that may require a restructuring of the code. We will hopefully get to work on it some more when time is freed up from production.

**Comment by Karl-Svard** [comment]
New PR here https://github.com/Clinical-Genomics/cg_lims/pull/478

**Comment by Karl-Svard** [comment]
Closing as the PR has been merged since a few weeks ago. The deployment to production will be documented in https://github.com/Clinical-Genomics/cg_lims/issues/460
