### ISSUE TITLE
Change criteria for RIN-value (RNA)

### ISSUE THREAD

**Issue by cesve** [Clinical-Genomics/cg_lims#214]
Lims Issue
---------------

**Work Flow:** RNA v3
**Protocol:** Initial QC (RNA) v2
**Step:** Tapestation Reception Control (RNA)

**Description:** Change criteria for RIN value to be >7 (instead of 8).

**Comment by cesve** [comment]
The configuration was changed and tested on lims stage:

![Screenshot 2022-03-11 at 15 05 02](https://user-images.githubusercontent.com/37171914/157883911-0e249ee9-6f04-4b60-8770-15ff8f5fa610.png)
![Screenshot 2022-03-11 at 15 11 04](https://user-images.githubusercontent.com/37171914/157883924-cd1e9dd1-a904-4eb6-86bb-79c58fec1ffc.png)

**Comment by cesve** [comment]
The criteria is now changed @idalindegaard , do we need to update the method or is this already done?

**Comment by idalindegaard** [comment]
Perfect! The method is updated.
