### ISSUE TITLE
sort_csv need handeling of mixture of tubes and plates in one file

### ISSUE THREAD

**Issue by mayabrandi** [Clinical-Genomics/cg_lims#219]

**Comment by RasmusBurge-CG** [comment]
Attached you will find how we want the file to be sorted. :) @cesve can you have a look at the file also?  

[Norm_Pool_Example_File.csv](https://github.com/Clinical-Genomics/cg_lims/files/8252649/Norm_Pool_Example_File.csv)

**Comment by RasmusBurge-CG** [comment]
Attached you will find how we would like to have the file sorted. :) @cesve Could you just look at the file and see if you disagree.  

[Norm_Pool_Example_File.csv](https://github.com/Clinical-Genomics/cg_lims/files/8252682/Norm_Pool_Example_File.csv)

**Comment by cesve** [comment]
Is it sorted in the following order?

1. Barcode Source Container (if plate)
2. Source well (if plate)
3. Destination well (if tube)
