### ISSUE TITLE
1471 ready to be merged and used in Atlas

### ISSUE THREAD

**Issue by EmiliaRegazzoni** [Clinical-Genomics/cg_lims#221]
Lims Issue
---------------

**Work Flow:** Microbial WGS v6
**Protocol:** CG002 - Normalization of microbial samples for sequencing
**Step:** Step 1 CG002 - Normalization of microbial samples for sequencing

**Description:** I am moving document 1471 to Atlas, could you add the Altas document as an option in this lims step before I merge the PR?

**Comment by mayabrandi** [comment]
I need to know the name of the method document in atlas or the path

**Comment by EmiliaRegazzoni** [comment]
the title of the document is: Normalization and dilution of samples/libraries using Bravo Shirin
The pull request is: Adds normalisation bravo shirin #464

**Comment by mayabrandi** [comment]
@EmiliaRegazzoni There is a broblem having / in the title of the document. Can you change that?

**Comment by AnnaLeinfelt** [comment]
> @EmiliaRegazzoni There is a broblem having / in the title of the document. Can you change that?

@mayabrandi 
Should I change to Normalization and dilution on Bravo Shirin in the title?

![Screenshot 2022-03-18 at 14 33 29](https://user-images.githubusercontent.com/37171709/159012248-a200dba5-0605-4087-96d5-3277be06a07b.png)

**Comment by RasmusBurge-CG** [comment]
Title changed to _"Normalization and dilution using Bravo Shirin"_

**Comment by EmiliaRegazzoni** [comment]
@RasmusBurge-CG Done!

**Comment by RasmusBurge-CG** [comment]
Also added shirin to step _CG002 - Normalization of microbial samples_

**Comment by RasmusBurge-CG** [comment]
All done, tested and up and running in LIMS!

**Comment by RasmusBurge-CG** [comment]
Done!
