### ISSUE TITLE
1564 merged and ready to be used in Atlas

### ISSUE THREAD

**Issue by amandaraud** [Clinical-Genomics/cg_lims#222]
Lims Issue
---------------

**Work Flow:** CG001 Genotyping
**Protocol:** CG002 - Genotyping
- [x] **Step:** CG002 - Plate Setup MAF
NB! Might not be included in this step, but it should be!
- [x] **Remove reference to am doc:** CG002 - Plate Setup MAF

**Work Flow:** TWIST v5
**Protocol:** Library Prep TWIST v2
- [x] **Step:** Aliquot samples for enzymatic fragmentation TWIST
- [x] **Remove reference to am doc:** 

**Work Flow:** WGS PCR free v5
**Protocol:** TruSeq DNA PCR-free Library Prep
- [x] **Step:** Aliquot Samples for Covaris ?
- [x]  **Remove reference to am doc:** 
NB! Might not be included in this step, but it should be!

**Work Flow:** Microbial WGS v6
**Protocol:** Nextera Microbial WGS v4
- [x] **Step:** Normalization of microbial samples v2
- [x]  **Remove reference to am doc:** 

**Description:** 1564 Normalization on Bravo Celeste has been merged and is ready to be used in Atlas. Lims workflows need to be updated. The method is used in several workflows, listed above.

**Comment by mayabrandi** [comment]
I need to know the name of the method document in atlas or the path

**Comment by amandaraud** [comment]
The name in Atlas is _Normalization of samples on Bravo Celeste_
Path: /production/lab/supporting_procedures/normalisation_bravo_celeste/

**Comment by RasmusBurge-CG** [comment]
@amandaraud @AnnaLeinfelt All done, tested and up and running in LIMS
