### ISSUE TITLE
Improvement suggestions for WGS PCR free v5

### ISSUE THREAD

**Issue by amandaraud** [Clinical-Genomics/cg_lims#234]
Lims Issue
---------------

**Work Flow:** WGS PCR free v5
**Protocol:** TruSeq DNA PCR-free Library Prep
**Step:** Aliquot Samples for Covaris, Fragment DNA (TruSeq DNA)

**Description:**
Some improvement suggestions for WGS work flow:
- Bead purification (section 3.2.2 in protocol) does not exist in Lims, meaning that the lot numbers of beads, resuspension buffer, water or ethanol are not registered in Lims.
- Resuspension buffer is registered in Fragmentation step and not in the Aliquotation step (where it is actually used)
- Change "Covaris tube" to "Covaris plate/tube" in Fragmentation

**Comment by RasmusBurge-CG** [comment]
Actions:

- [ ] Bead purification (section 3.2.2 in protocol) does not exist in Lims, meaning that the lot numbers of beads, resuspension buffer, water or ethanol are not registered in Lims.

- [ ] Resuspension buffer is registered in Fragmentation step and not in the Aliquotation step (where it is actually used)

- [ ] Change "Covaris tube" to "Covaris plate/tube" in Fragmentation

- [ ] Setup trending for Arnold

**Comment by cesve** [comment]
Closing issue!
