### ISSUE TITLE
1764 ready to be merged and used in Atlas

### ISSUE THREAD

**Issue by FayKanellidou** [Clinical-Genomics/cg_lims#237]
Lims Issue
---------------

**Work Flow:** Microbial WGS v6
**Protocol:** Initial QC Microbial v3 , Nextera Microbial WGS v4 
**Step:**  

- [x] CG002 - Quantit QC (DNA) 
- [x] Microbial Library Prep (Nextera) v2 
- [x] Post-PCR bead purification v1 

**Description:** AM document 1764 "Manual cost-efficient library preparation for microbial WGS"  has been moved to Atlas and is ready to be merged and used.

**Comment by RasmusBurge-CG** [comment]
Atlas doc _**Manual cost-efficient library preparation for microbial WGS**_ now available in all lims steps, @FayKanellidou please let me know when the atlas doc is fully up and running and the AM doc is archived :)

**Comment by FayKanellidou** [comment]
The doc is now moved to Atlas @RasmusBurge-CG

**Comment by RasmusBurge-CG** [comment]
Remove all references to 1764 in the following steps:

- [ ]  CG002 - Quantit QC (DNA)
- [ ]  Microbial Library Prep (Nextera) v2
- [ ]  Post-PCR bead purification v1

**Comment by FayKanellidou** [comment]
@RasmusBurge-CG can you remove the UDFS with the 1764 doc in the CG002 - Quantit QC (DNA)? I think you forgot to remove them ;)

<img width="976" alt="Screen Shot 2022-04-01 at 11 28 28" src="https://user-images.githubusercontent.com/91183363/161253024-eff8e87a-8eea-4e4c-965e-dbc26e25f54c.png">

**Comment by RasmusBurge-CG** [comment]
<img width="1005" alt="Screenshot 2022-04-01 at 13 27 25" src="https://user-images.githubusercontent.com/80392398/161254709-65a7ec5b-e177-4f17-b831-da706cce835f.png">

**Comment by FayKanellidou** [comment]
@RasmusBurge-CG Perfect!! Looks great now!

**Comment by RasmusBurge-CG** [comment]
Atlas document is fully in production.
