### ISSUE TITLE
1117 ready to be merged and used in Atlas 

### ISSUE THREAD

**Issue by saschaconradt** [Clinical-Genomics/cg_lims#239]
Lims Issue
---------------

**Work Flow:** WGS PCR free v5
**Protocol:** Initial QC wgs v4
**Step:** 
- CG002 – Qubit QC (DNA)
- Quantit QC (DNA) WGS v1

**Description:** AM document 1117 " Reception control of incoming WGS-samples" has been moved to Atlas and is ready to be merged and used.

**Comment by RasmusBurge-CG** [comment]
- [ ]  CG002 – Qubit QC (DNA).  

- [ ]  Quantit QC (DNA) WGS v1

**Comment by RasmusBurge-CG** [comment]
Document _**Reception control of incoming WGS-samples**_ is now an option in all lims-steps, @saschaconradt please let me know when the AM doc is archived and the Atlas doc is fully up and running :)

**Comment by saschaconradt** [comment]
@RasmusBurge-CG the AM doc 1117 is archived and the Atlas doc (Reception control of incoming WGS-samples) is fully up and running.

**Comment by RasmusBurge-CG** [comment]
Remove 1117 from:

- [ ] CG002 – Qubit QC (DNA)

- [ ] Quantit QC (DNA) WGS v1

**Comment by RasmusBurge-CG** [comment]
Atlas doc added and AM doc removed from LIMS
