### ISSUE TITLE
CG002 - reception control, group samples by SupportSystem ID

### ISSUE THREAD

**Issue by AnnaLeinfelt** [Clinical-Genomics/cg_lims#241]
Lims Issue
---------------

**Work Flow:** CG002 - reception control
**Protocol:** CG002 - reception control
**Step:** See picture

**Description:** I would like samples to be group be SuSy id in this step.

![Screenshot 2022-03-25 at 09 57 48](https://user-images.githubusercontent.com/37171709/160088735-563b1a44-acb0-4f6d-96d1-fe39cc43f044.png)
![Screenshot 2022-03-25 at 09 57 56](https://user-images.githubusercontent.com/37171709/160088740-7fa62749-7758-4eff-b0f0-e5f96076b51a.png)

The same feature was implemented in the issue, https://github.com/Clinical-Genomics/cg_lims/issues/148

**Comment by AnnaLeinfelt** [comment]
fyi @Clinical-Genomics/sequencing

**Comment by cesve** [comment]
Samples should now be sorted by Project.

Was it in workflow RML v6? @AnnaLeinfelt

**Comment by AnnaLeinfelt** [comment]
> Samples should now be sorted by Project.
> 
> Was it in workflow RML v6? @AnnaLeinfelt

Yes!

**Comment by cesve** [comment]
Great!
