### ISSUE TITLE
Import sample UDF Volume (ul) to step Aliquot samples for enzymatic fragmentation TWIST

### ISSUE THREAD

**Issue by cesve** [Clinical-Genomics/cg_lims#243]
Lims Issue
---------------

**Work Flow:** TWIST v7
**Protocol:** Library Prep TWIST v2
**Step:** Aliquot samples for enzymatic fragmentation TWIST

**Description:** A Sample volume is seen for each sample in the Sample table. This is the volume from the order. We would like to change this so that the Volume from UDF "Volume (ul)" in the Qubit/Quantit step is imported instead.

**Comment by cesve** [comment]
Sample artifact Volume (ul) was added to the script _1. Copy UDFs from Buffer Exchange v2 or sample-artifact_. 

The UDF was also added to the Sample table in the Record details tab (Derived sample). The old Volume (ul) UDF was removed as this was the "Submitted sample" UDF (volume from order). The Volume (ul) UDF was also added to step _Aggregate QC (DNA) TWIST_ in protocol _Initial QC TWIST v3_.

![Screenshot 2022-03-28 at 13 08 01](https://user-images.githubusercontent.com/37171914/160386436-e7c97298-d2ee-44d7-9158-076200790af6.png)

This was tested on stage:

**Comment by mayabrandi** [comment]
JOhooooo. Bravo Cissi

**Comment by cesve** [comment]
Deployed to production.

Test in lims prod:

**_Sample the went through buffer exchange and Quantit:_**


**_Sample that went directly to Initial QC and Qubit:_**

**Comment by mayabrandi** [comment]
🥳
