### ISSUE TITLE
Remove samples from NovaSeq run

### ISSUE THREAD

**Issue by karlnyr** [Clinical-Genomics/cg_lims#256]
Lims Issue
---------------

For definitions of headings below see [Basic Concepts](https://atlas.scilifelab.se/infrastructure/lims/basic_concepts/).

**Description:** Describe the issue here!!!

Situations arise where it would be appropriate to make our systems believe that a sample was never sequenced on a flowcell - albeit sample mixups or corrupted data generated from the sequencing. CG fetches information from LIMS in this [step](https://github.com/Clinical-Genomics/cg/blob/594db33f553f657c467bc0d26d4041e07e7156be/cg/apps/lims/samplesheet.py#L90). 

The following steps are required to process to ensure that a sample is not included on a sequencer run:

- Define Run format and calculate volumes
- STANDARD Make Pool and Denature (Nova Seq)
- STANDARD Prepare for Sequencing (Nova Seq)
- NovaSeq Run

Ideally, the user should be able to remove samples from pools on a flow cell.

This is a request, but if it is too complicated and would require too much time it is not required.

**Comment by Karl-Svard** [comment]
I had a conversation with @mayabrandi about this and unfortunately we don't have the ability to directly remove them. The closest we can go is by manually failing the QC flag of the sample in its previous runs, which makes them not being taken into consideration further down the line. We already have a script that does this for an entire process (https://clinical-lims.scilifelab.se/clarity/work-details/279840) but we can look into creating one which lets the user specify a subset of samples.

**Comment by cesve** [comment]
No solution yet, will be opened when/if we have one.
