### ISSUE TITLE
2182 ready to be used in Atlas

### ISSUE THREAD

**Issue by susannemaner** [Clinical-Genomics/cg_lims#257]
Lims Issue
---------------

For definitions of headings below see [Basic Concepts](https://atlas.scilifelab.se/infrastructure/lims/basic_concepts/).

**Work Flow:** Library Prep (Cov) v2
**Protocol:** Library Preparation (Cov)
**Step:**Library validation QC (Cov) v1

**Description:** Description: "Manual SARS-CoV-2 library preparation using Illumina COVIDseq Test" has been merged and is ready to be used in Atlas. Lims workflows need to be updated. The method is used in workflows, listed above.

**Comment by susannemaner** [comment]
@saschaconradt Can you help me verify that the LIMS step are correct?

**Comment by RasmusBurge-CG** [comment]
I think it should be:
Work Flow: SARS-CoV-2 v3
Protocol: Library Prep (Cov) v2
**Step:**

- [ ] Sample Placement (Cov) v1
- [ ] Library Preparation (Cov) v1
- [ ] Pooling and Clean-up (Cov) v1

**Comment by RasmusBurge-CG** [comment]
Hi @susannemaner! Atlas document "Manual SARS-CoV-2 library preparation using Illumina COVIDseq Test" is available in all steps. Let me know when I can remove references to 2182 from LIMS.

**Comment by cesve** [comment]
@susannemaner is the method removed from AM and ready to be used in Atlas now?

**Comment by susannemaner** [comment]
@cesve Not yet. Hopefully later today. Need some help for the last steps.

**Comment by cesve** [comment]
No rush, just let us know when you're ready!

**Comment by susannemaner** [comment]
The document is now ready to use in Atlas. Make sure that the AM-document it's not used today before references to 2182 is removed from LIMS.

**Comment by RasmusBurge-CG** [comment]
Remove 2182 from steps:

- [ ] Sample Placement (Cov) v1
- [ ]  Library Preparation (Cov) v1
- [ ] Pooling and Clean-up (Cov) v1

**Comment by RasmusBurge-CG** [comment]
Transfer completed
