### ISSUE TITLE
Vapor lock no longer used

### ISSUE THREAD

**Issue by EmiliaRegazzoni** [Clinical-Genomics/cg_lims#260]
Lims Issue
---------------

For definitions of headings below see [Basic Concepts](https://atlas.scilifelab.se/infrastructure/lims/basic_concepts/).

**Work Flow:** Twist v7
**Protocol:** Target Enrichment TWIST v3
**Step:** Target enrichment TWIST

**Description:** We no longer use a separate vapor lock in TGA, but instead the hybridisation enhancer which is a part of the TWIST Hybridisation kit. Therefore the box Vapor lock can be removed, nothing needs to replace it.

**Comment by RasmusBurge-CG** [comment]
The udf "Vapor lock" was removed from step "Target enrichment TWIST".
