### ISSUE TITLE
Make a EPP that is able to change reception date

### ISSUE THREAD

**Issue by RasmusBurge-CG** [Clinical-Genomics/cg_lims#265]
Lims Issue
---------------

For definitions of headings below see [Basic Concepts](https://atlas.scilifelab.se/infrastructure/lims/basic_concepts/).

**Work Flow:** Full name here please!
**Protocol:** And here!
**Step:** Here to!

**Description:** Describe issue here!!!

**Comment by cesve** [comment]
Suggestion: Move step Reception control so that it's done after initial QC. Can be in the Initial QC protocol. Change order of the steps.

**Comment by cesve** [comment]
Wait until the large update is done.

**Comment by RasmusBurge-CG** [comment]
How about requeue samples back to Reception Control step again after failed QC? they would then get a new date.
