### ISSUE TITLE
Preparing plate for genotyping ready to be use in Atlas

### ISSUE THREAD

**Issue by MarcelaGa** [Clinical-Genomics/cg_lims#268]
Lims Issue
---------------

For definitions of headings below see [Basic Concepts](https://atlas.scilifelab.se/infrastructure/lims/basic_concepts/).

**Work Flow:** CG002 - Genotyping
**Protocol:** CG002 - Plate Setup MAF
**Step:** Step 1: CG002 - Plate Setup MAF

**Description:** Preparing plate for genotyping has been merged and is ready to be used in Atlas. Lims workflows need to be updated. The method is used in workflows, listed above.

**Comment by RasmusBurge-CG** [comment]
Hi @MarcelaGa! What is the title of the method in atlas? :)

**Comment by MarcelaGa** [comment]
The Title is Preparing plate for genotyping and the current doc in AM is 1243:14

**Comment by RasmusBurge-CG** [comment]
Hi @MarcelaGa! Let me know when the document is "removed" from AM :)

**Comment by MarcelaGa** [comment]
> Hi @MarcelaGa! Let me know when the document is "removed" from AM :)

Hi @RasmusBurge-CG! The document is deprecated in AM now :)

**Comment by RasmusBurge-CG** [comment]
Perfect @MarcelaGa! Will remove 1243 from the steps. :) You can also remove the WIP heading from your atlas document :)

**Comment by cesve** [comment]
@MarcelaGa is the WIP removed from the heading?

**Comment by MarcelaGa** [comment]
> @MarcelaGa is the WIP removed from the heading?

Yes, it was removed!
