### ISSUE TITLE
Rework Initial QC (Cov) v1?

### ISSUE THREAD

**Issue by RasmusBurge-CG** [Clinical-Genomics/cg_lims#269]
Is a rework of Initial QC (Cov) v1 needed?

**Comment by RasmusBurge-CG** [comment]
> OK. Thanks! We also use the Initial QC (Cov) v1 (step 1-5, we only use step 1 and 5) and Library validation QC (cov) v 1 (step 1-4, we only use step 3 and 4). Do we need to add them?

Hi @susannemaner! 
From your question in the move of the 2182 document, I got a feeling that the covid workflow needs the be changed? There are a lot of steps you don't use, is there a need to change this workflow?

**Comment by cesve** [comment]
The reason for having the Quantit/Qubit and TS step in Initial QC is to have the option to measure if we want to. I think we should keep the steps but it's optional to run them.

We will most likely run the micro-prep with the covid-protocol in the future and then we might want to run Quantit first.

**Comment by RasmusBurge-CG** [comment]
Okay! What about these steps _"Library validation QC (cov) v 1 (step 1-4, we only use step 3 and 4)."_? :)

**Comment by RasmusBurge-CG** [comment]
Okay, soo there is no need! Perfect!
