### ISSUE TITLE
Update placement map in step Aliquot Samples for Fragmentation (RNA)

### ISSUE THREAD

**Issue by idalindegaard** [Clinical-Genomics/cg_lims#270]
Lims Issue
---------------

For definitions of headings below see [Basic Concepts](https://atlas.scilifelab.se/infrastructure/lims/basic_concepts/).

**Work Flow:** RNA v3
**Protocol:** Library Prep (RNA)
**Step:** Aliquot Samples for Fragmentation (RNA)

**Description:** 
The placement map in this step could be updated in two ways:
- Add udf information "Volume H20 (ul)". - Now we only have the sample volume, and it makes the placement map only work 50% of it's intended capacity.
- Remove the row containing "Source container" - This information is redundant, project, sample name and LIMS ID are enough to identify which sample it is.

**Comment by cesve** [comment]
@idalindegaard what if the samples arrive in several plates, wouldn't it be good to have source container?

**Comment by cesve** [comment]
@RasmusBurge-CG perhaps we can look at this together? I think we need a new EPP for this.

**Comment by RasmusBurge-CG** [comment]
@cesve yes, let's do that

**Comment by idalindegaard** [comment]
> @idalindegaard what if the samples arrive in several plates, wouldn't it be good to have source container?

@cesve Ok, good point, let's keep it!

**Comment by RasmusBurge-CG** [comment]
I changed the automation from:
```
bash -c "/home/glsai/miniconda3/envs/epp_master/bin/make_placement_map.py --pid {processLuid} --res {compoundOutputFileLuid1} --orig --dest_96well"
```

to

````
bash -c "/home/glsai/miniconda3/envs/epp_master/bin/96well_placement_map.py -p {processLuid} -r {compoundOutputFileLuid1} -o -u 'Volume H2O (ul)' 'Sample Volume (ul)'"

````


This made these changes:

|   | 1                                                                                                                                                                         | 2                                                                                                                                                                                                   | 3                                                                                                                                                                                                   | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11 | 12 |
|---|---------------------------------------------------------------------------------------------------------------------------------------------------------------------------|-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|---|---|---|---|---|---|----|----|----|
| A | Project : 460047 Sample Name : RNA-T-K4205-22 Sample ID : ACC9684A1 Original Container : YL017 Original Well : A:1 Volume H2O (ul) : 24.72 Sample Volume (ul) : 0.28      | Project : 474378 Sample Name : MOL558-22RNA Sample ID : ACC9661A1 Original Container : MOL558-22RNA Original Well : 1:1 Volume H2O (ul) : 24.44 Sample Volume (ul) : 0.56                           | Project : 213816 Sample Name : RNAprep-control-HeLaS3-29 Sample ID : ACC9464A9 Original Container : RNAprep-control-HeLaS3-29 Original Well : 1:1 Volume H2O (ul) : 16.67 Sample Volume (ul) : 8.33 |   |   |   |   |   |   |    |    |    |
| B | Project : 460047 Sample Name : RNA-T-K4258-22 Sample ID : ACC9684A2 Original Container : YL017 Original Well : B:1 Volume H2O (ul) : 24.66 Sample Volume (ul) : 0.34      | Project : 474378 Sample Name : MOL783-22RNA Sample ID : ACC9661A5 Original Container : MOL783-22RNA Original Well : 1:1 Volume H2O (ul) : 24.53 Sample Volume (ul) : 0.47                           |                                                                                                                                                                                                     |   |   |   |   |   |   |    |    |    |
| C | Project : 460047 Sample Name : RNA-T-K4282-22 Sample ID : ACC9684A3 Original Container : YL017 Original Well : C:1 Volume H2O (ul) : 24.64 Sample Volume (ul) : 0.36      | Project : 474378 Sample Name : MOL788-22RNA Sample ID : ACC9661A4 Original Container : MOL788-22RNA Original Well : 1:1 Volume H2O (ul) : 24.39 Sample Volume (ul) : 0.61                           |                                                                                                                                                                                                     |   |   |   |   |   |   |    |    |    |
| D | Project : 460047 Sample Name : RNA-T-K4310-22 Sample ID : ACC9684A4 Original Container : YL017 Original Well : D:1 Volume H2O (ul) : 24.28 Sample Volume (ul) : 0.72      | Project : 474378 Sample Name : MOL846-22RNA Sample ID : ACC9661A6 Original Container : MOL846-22RNA Original Well : 1:1 Volume H2O (ul) : 14.32 Sample Volume (ul) : 10.68                          |                                                                                                                                                                                                     |   |   |   |   |   |   |    |    |    |
| E | Project : 460047 Sample Name : RNA-T-K4387-22 Sample ID : ACC9684A5 Original Container : YL017 Original Well : E:1 Volume H2O (ul) : 22.58 Sample Volume (ul) : 2.42      | Project : 474378 Sample Name : MOL875-22RNA Sample ID : ACC9661A3 Original Container : MOL875-22RNA Original Well : 1:1 Volume H2O (ul) : 22.16 Sample Volume (ul) : 2.84                           |                                                                                                                                                                                                     |   |   |   |   |   |   |    |    |    |
| F | Project : 460047 Sample Name : RNA-T-K4535-22 Sample ID : ACC9684A6 Original Container : YL017 Original Well : F:1 Volume H2O (ul) : 23.06 Sample Volume (ul) : 1.94      | Project : 213816 Sample Name : RNAprep-control-HeLaS3-26 Sample ID : ACC9464A6 Original Container : RNAprep-control-HeLaS3-26 Original Well : 1:1 Volume H2O (ul) : 16.67 Sample Volume (ul) : 8.33 |                                                                                                                                                                                                     |   |   |   |   |   |   |    |    |    |
| G | Project : 460047 Sample Name : RNA-T-K4586-22 Sample ID : ACC9684A7 Original Container : YL017 Original Well : G:1 Volume H2O (ul) : 24.61 Sample Volume (ul) : 0.39      | Project : 213816 Sample Name : RNAprep-control-HeLaS3-27 Sample ID : ACC9464A7 Original Container : RNAprep-control-HeLaS3-27 Original Well : 1:1 Volume H2O (ul) : 16.67 Sample Volume (ul) : 8.33 |                                                                                                                                                                                                     |   |   |   |   |   |   |    |    |    |
| H | Project : 474378 Sample Name : MOL250-22RNA Sample ID : ACC9661A2 Original Container : MOL250-22RNA Original Well : 1:1 Volume H2O (ul) : 19.29 Sample Volume (ul) : 5.71 | Project : 213816 Sample Name : RNAprep-control-HeLaS3-28 Sample ID : ACC9464A8 Original Container : RNAprep-control-HeLaS3-28 Original Well : 1:1 Volume H2O (ul) : 16.67 Sample Volume (ul) : 8.33 |                                                                                                                                                                                                     |   |   |   |   |   |   |    |    |    |

Orignial looked like this:

|   | 1                                                                                                                                             | 2                                                                                                                                                                       | 3                                                                                                                                                                       | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11 | 12 |
|---|-----------------------------------------------------------------------------------------------------------------------------------------------|-------------------------------------------------------------------------------------------------------------------------------------------------------------------------|-------------------------------------------------------------------------------------------------------------------------------------------------------------------------|---|---|---|---|---|---|----|----|----|
| A | Project : 460047 Sample Name : RNA-T-K4205-22 Sample ID : ACC9684A1 Source Container : YL017 Source Well : A:1 Sample Volume (ul) : 0.28      | Project : 474378 Sample Name : MOL558-22RNA Sample ID : ACC9661A1 Source Container : MOL558-22RNA Source Well : 1:1 Sample Volume (ul) : 0.56                           | Project : 213816 Sample Name : RNAprep-control-HeLaS3-29 Sample ID : ACC9464A9 Source Container : RNAprep-control-HeLaS3-29 Source Well : 1:1 Sample Volume (ul) : 8.33 |   |   |   |   |   |   |    |    |    |
| B | Project : 460047 Sample Name : RNA-T-K4258-22 Sample ID : ACC9684A2 Source Container : YL017 Source Well : B:1 Sample Volume (ul) : 0.34      | Project : 474378 Sample Name : MOL783-22RNA Sample ID : ACC9661A5 Source Container : MOL783-22RNA Source Well : 1:1 Sample Volume (ul) : 0.47                           |                                                                                                                                                                         |   |   |   |   |   |   |    |    |    |
| C | Project : 460047 Sample Name : RNA-T-K4282-22 Sample ID : ACC9684A3 Source Container : YL017 Source Well : C:1 Sample Volume (ul) : 0.36      | Project : 474378 Sample Name : MOL788-22RNA Sample ID : ACC9661A4 Source Container : MOL788-22RNA Source Well : 1:1 Sample Volume (ul) : 0.61                           |                                                                                                                                                                         |   |   |   |   |   |   |    |    |    |
| D | Project : 460047 Sample Name : RNA-T-K4310-22 Sample ID : ACC9684A4 Source Container : YL017 Source Well : D:1 Sample Volume (ul) : 0.72      | Project : 474378 Sample Name : MOL846-22RNA Sample ID : ACC9661A6 Source Container : MOL846-22RNA Source Well : 1:1 Sample Volume (ul) : 10.68                          |                                                                                                                                                                         |   |   |   |   |   |   |    |    |    |
| E | Project : 460047 Sample Name : RNA-T-K4387-22 Sample ID : ACC9684A5 Source Container : YL017 Source Well : E:1 Sample Volume (ul) : 2.42      | Project : 474378 Sample Name : MOL875-22RNA Sample ID : ACC9661A3 Source Container : MOL875-22RNA Source Well : 1:1 Sample Volume (ul) : 2.84                           |                                                                                                                                                                         |   |   |   |   |   |   |    |    |    |
| F | Project : 460047 Sample Name : RNA-T-K4535-22 Sample ID : ACC9684A6 Source Container : YL017 Source Well : F:1 Sample Volume (ul) : 1.94      | Project : 213816 Sample Name : RNAprep-control-HeLaS3-26 Sample ID : ACC9464A6 Source Container : RNAprep-control-HeLaS3-26 Source Well : 1:1 Sample Volume (ul) : 8.33 |                                                                                                                                                                         |   |   |   |   |   |   |    |    |    |
| G | Project : 460047 Sample Name : RNA-T-K4586-22 Sample ID : ACC9684A7 Source Container : YL017 Source Well : G:1 Sample Volume (ul) : 0.39      | Project : 213816 Sample Name : RNAprep-control-HeLaS3-27 Sample ID : ACC9464A7 Source Container : RNAprep-control-HeLaS3-27 Source Well : 1:1 Sample Volume (ul) : 8.33 |                                                                                                                                                                         |   |   |   |   |   |   |    |    |    |
| H | Project : 474378 Sample Name : MOL250-22RNA Sample ID : ACC9661A2 Source Container : MOL250-22RNA Source Well : 1:1 Sample Volume (ul) : 5.71 | Project : 213816 Sample Name : RNAprep-control-HeLaS3-28 Sample ID : ACC9464A8 Source Container : RNAprep-control-HeLaS3-28 Source Well : 1:1 Sample Volume (ul) : 8.33 |                                                                                                                                                                         |   |   |   |   |   |   |    |    |    |
