### ISSUE TITLE
Remove the "default selected" on Atlas document

### ISSUE THREAD

**Issue by RasmusBurge-CG** [Clinical-Genomics/cg_lims#271]
Lims Issue
---------------

For definitions of headings below see [Basic Concepts](https://atlas.scilifelab.se/infrastructure/lims/basic_concepts/).

**Work Flow:** 
**Protocol:** And here!
**Step:** Here to!

**Description:** Describe issue here!!!

Looking at old samples in LIMS one could get the impression that a Atlas method has been used if the udf "Method Document" is set as default. This has been removed for the following steps:

- [x] KAPA Library Preparation Twist v1, Custom Entries "yes"
- [x] CG002 - Microbial Library Prep (Nextera), Custom Entries "no"
- [x] CG002 - Quantit QC (DNA), Custom Entries "no"
- [x] CG002 - Qubit QC (DNA), Custom Entries "no"
- [x] CG002 - Plate Setup MAF, Custom Entries "no"
- [x] Normalization of samples for Sequencing (TWIST) v1, Custom Entries "no"
- [x] fragment DNA (TruSeq DNA), Custom Entries "no"
- [x] CG002 - Normalization of microbial samples for sequencing, Custom Entries "no"
- [x] Quantit QC (DNA) WGS v1, Custom Entries "no"
- [x] End repair Size selection A-tailing and adapter ligation (TruSeq PCR-free DNA), Custom Entries "no"
- [x] Enzymatic fragmentation Twist v2, Custom Entries "yes"
- [x] CG002 - Normalization of microbial samples, Custom Entries "no"
- [x] POST-PCR bead purification v1, Custom Entries "no"
- [x] Aliquot samples for enzymatic fragmentation TWIST v2, Custom Entries "no"
- [x] Aliquot samples for covaris, Custom Entries "no"

**Comment by RasmusBurge-CG** [comment]
Hi @AnnaLeinfelt, the bug should now be fixed for all steps.

**Comment by AnnaLeinfelt** [comment]
> Hi @AnnaLeinfelt, the bug should now be fixed for all steps.

Nice! Thanks!
