### ISSUE TITLE
Change method document in LIMS for RNA RC

### ISSUE THREAD

**Issue by idalindegaard** [Clinical-Genomics/cg_lims#274]
Lims Issue
---------------

For definitions of headings below see [Basic Concepts](https://atlas.scilifelab.se/infrastructure/lims/basic_concepts/).

**Work Flow:** RNA v3
**Protocol:** Initial QC (RNA) v2
**Step:** Quantit QC (RNA) and Qubit QC (RNA)

**Description:** 
The method document 2234 has been divided, and the reception control part is now a separate document and has been moved to Atlas. The new name is "Reception control of incoming RNA samples". The old AM document and document version have been recorded in the LIMS steps Quantit QC (RNA) and Qubit QC (RNA). This should be changed now with the update.

**Comment by idalindegaard** [comment]
@RasmusBurge-CG Hi, the priority is quite high for this issue. Would be great if it could be changed as soon as possible. :)

**Comment by RasmusBurge-CG** [comment]
Note for me: Replace 2234 with "Reception control of incoming RNA samples".

**Comment by RasmusBurge-CG** [comment]
Added "Reception control of incoming RNA samples" to steps:
- [ ] Quantit QC (RNA)
- [ ] Qubit QC (RNA)

**Comment by RasmusBurge-CG** [comment]
Hi @idalindegaard! Document "Reception control of incoming RNA samples" is available to select in the steps.

**Comment by idalindegaard** [comment]
Thank you @RasmusBurge-CG ! Now the transfer is fully done.

**Comment by RasmusBurge-CG** [comment]
Remove 2234 from steps:
- [ ] Quantit QC (RNA)
- [ ] Qubit QC (RNA)

**Comment by RasmusBurge-CG** [comment]
New automation named “Save Atlas Documents” in Quantit QC (RNA), Protocol: Initial QC (RNA) v2. It saves the version and pathway of the Atlas methods, like the automation “Atlas Method Document” the only difference is that it looks for udfs named “Method Document 1” until “Method Document 3"(this can be increased).

**Comment by RasmusBurge-CG** [comment]
All done
