### ISSUE TITLE
Change allowed amount in aliquotation step (RNA)

### ISSUE THREAD

**Issue by cesve** [Clinical-Genomics/cg_lims#278]
Lims Issue
---------------

For definitions of headings below see [Basic Concepts](https://atlas.scilifelab.se/infrastructure/lims/basic_concepts/).

**Work Flow:** RNA v3
**Protocol:** Library Prep (RNA)
**Step:** Aliquot Samples for Fragmentation (RNA)

**Description:** We would like to change the script Calculate Volume H2O so that all amount needed values are accepted.

**Comment by RasmusBurge-CG** [comment]
See pull request https://github.com/Clinical-Genomics/cg_lims/pull/280
