### ISSUE TITLE
Add ladder lot nr to step in RNA wf

### ISSUE THREAD

**Issue by cesve** [Clinical-Genomics/cg_lims#283]
Lims Issue
---------------

For definitions of headings below see [Basic Concepts](https://atlas.scilifelab.se/infrastructure/lims/basic_concepts/).

**Work Flow:** RNA v3
**Protocol:** Initial QC (RNA) v2
**Step:** Tapestation Reception Control (RNA)

**Description:** Add the lot no of the TapeStation adder as it is not the same as the buffer.

**Comment by cesve** [comment]
The process UDF has been added.

@RasmusBurge-CG and @idalindegaard do you think it's necessary to trend this or if it's useful for troubleshooting?

**Comment by idalindegaard** [comment]
@cesve Thanks! I don't think that's necessary.. or do we add all lot numbers to the Arnold model?

**Comment by cesve** [comment]
No just the ones we think is necessary!
