### ISSUE TITLE
2233 ready to be merged and used in Atlas

### ISSUE THREAD

**Issue by saschaconradt** [Clinical-Genomics/cg_lims#284]
Lims Issue
---------------

For definitions of headings below see [Basic Concepts](https://atlas.scilifelab.se/infrastructure/lims/basic_concepts/).

**Work Flow:** TWIST v7
**Protocol:** Pre Processing TWIST v3, Initial QC TWIST v3 
**Step:** Sample Placement (TWIST), Buffer Exchange (TWIST), Tapestation Reception Control TWIST, Qubit QC (DNA) TWIST, Quantit QC (DNA) TWIST, 

**Description:** AM document 2233 " Reception control of incoming TGA-samples" has been moved to Atlas and is ready to be merged and used. Please change also minimum requirement is 250ng above that a green flag will be assigned. Now the minimum is set to 500ng.

**Comment by RasmusBurge-CG** [comment]
### Pre Processing TWIST v3
______________

- [ ] Sample Placement (TWIST)
- [ ] Buffer Exchange (TWIST)

### Initial QC TWIST v3
______________

- [ ] Tapestation Reception Control TWIST
- [ ] Qubit QC (DNA) TWIST
- [ ] Quantit QC (DNA) TWIST

### Unrelated task
______________

Please change also minimum requirement is 250ng above that a green flag will be assigned. Now the minimum is set to 500ng.

**Comment by RasmusBurge-CG** [comment]
Hi @saschaconradt! You can now deprecate the document in AM.

**Comment by saschaconradt** [comment]
> Hi @saschaconradt! You can now deprecate the document in AM.

Done :-)

**Comment by RasmusBurge-CG** [comment]
Remove 2233

### Pre Processing TWIST v3
______________

- [ ] Sample Placement (TWIST)
- [ ] Buffer Exchange TWIST

### Initial QC TWIST v3
______________

- [ ] Tapestation Reception Control TWIST
- [ ] Qubit QC (DNA) TWIST
- [ ] Quantit QC (DNA) TWIST
