### ISSUE TITLE
Couldn't use -su in the make_96well_placement_map.py

### ISSUE THREAD

**Issue by RasmusBurge-CG** [Clinical-Genomics/cg_lims#285]
Lims Issue
---------------

For definitions of headings below see [Basic Concepts](https://atlas.scilifelab.se/infrastructure/lims/basic_concepts/).

**Work Flow:** Full name here please!
**Protocol:** And here!
**Step:** Aliquot Samples for Fragmentation (RNA) v1

**Description:** Describe issue here!!!

Tried to make a placement map that contained 'Volume H2O (ul)' 'Sample Volume (ul)' in RNA the WF, step Aliquot Samples for Fragmentation (RNA) v1. Was not able to get any of the udfs displayed in the placement map when I ran this:
`````
bash 
-c -l "conda activate cg_lims &&  lims -c /home/glsai/.genologics.yaml epps 
-l {compoundOutputFileLuid0} -p {processLuid}  files placement-map -o -f {compoundOutputFileLuid1} 
-su 'Volume H2O (ul)' 'Sample Volume (ul)'"

`````

Also, test this:

`````
lims -c ../config/genologics-stage.yaml epps -l log -p '24-319376' 
files placement-map -f remove.me -su "Volume H2O (ul)"

`````

And I don't get the "Volume H2O (ul)" udf in the file.

  | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11 | 12 | 13
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
A | Project : 460047Sample Name : RNA-T-K4205-22Sample ID : ACC9684A1Source Container : YL017Source Well : A:1 | Project : 474378Sample Name : MOL558-22RNASample ID : ACC9661A1Source Container : MOL558-22RNASource Well : 1:1 | Project : 213816Sample Name : RNAprep-control-HeLaS3-29Sample ID : ACC9464A9Source Container : RNAprep-control-HeLaS3-29Source Well : 1:1 |   |   |   |   |   |   |   |   |   |  
B | Project : 460047Sample Name : RNA-T-K4258-22Sample ID : ACC9684A2Source Container : YL017Source Well : B:1 | Project : 474378Sample Name : MOL783-22RNASample ID : ACC9661A5Source Container : MOL783-22RNASource Well : 1:1 |   |   |   |   |   |   |   |   |   |   |  
C | Project : 460047Sample Name : RNA-T-K4282-22Sample ID : ACC9684A3Source Container : YL017Source Well : C:1 | Project : 474378Sample Name : MOL788-22RNASample ID : ACC9661A4Source Container : MOL788-22RNASource Well : 1:1 |   |   |   |   |   |   |   |   |   |   |  
D | Project : 460047Sample Name : RNA-T-K4310-22Sample ID : ACC9684A4Source Container : YL017Source Well : D:1 | Project : 474378Sample Name : MOL846-22RNASample ID : ACC9661A6Source Container : MOL846-22RNASource Well : 1:1 |   |   |   |   |   |   |   |   |   |   |  
E | Project : 460047Sample Name : RNA-T-K4387-22Sample ID : ACC9684A5Source Container : YL017Source Well : E:1 | Project : 474378Sample Name : MOL875-22RNASample ID : ACC9661A3Source Container : MOL875-22RNASource Well : 1:1 |   |   |   |   |   |   |   |   |   |   |  
F | Project : 460047Sample Name : RNA-T-K4535-22Sample ID : ACC9684A6Source Container : YL017Source Well : F:1 | Project : 213816Sample Name : RNAprep-control-HeLaS3-26Sample ID : ACC9464A6Source Container : RNAprep-control-HeLaS3-26Source Well : 1:1 |   |   |   |   |   |   |   |   |   |   |  
G | Project : 460047Sample Name : RNA-T-K4586-22Sample ID : ACC9684A7Source Container : YL017Source Well : G:1 | Project : 213816Sample Name : RNAprep-control-HeLaS3-27Sample ID : ACC9464A7Source Container : RNAprep-control-HeLaS3-27Source Well : 1:1 |   |   |   |   |   |   |   |   |   |   |  
H | Project : 474378Sample Name : MOL250-22RNASample ID : ACC9661A2Source Container : MOL250-22RNASource Well : 1:1 | Project : 213816Sample Name : RNAprep-control-HeLaS3-28Sample ID : ACC9464A8Source Container : RNAprep-control-HeLaS3-28Source Well : 1:1 |   |   |   |   |   |   |   |   |   |   |

**Comment by Karl-Svard** [comment]
Issue fixed in PR https://github.com/Clinical-Genomics/cg_lims/pull/344.

I have now also switched to using the new EPP in production for this step.

Old configuration:
```
bash -c "/home/glsai/miniconda3/envs/epp_master/bin/96well_placement_map.py -p {processLuid} -r {compoundOutputFileLuid1} -o -u 'Volume H2O (ul)' 'Sample Volume (ul)'"
```

New configuration:
```
bash -c -l "conda activate cg_lims &&  lims -c /home/glsai/.genologics.yaml epps -l {compoundOutputFileLuid0} -p {processLuid}  files placement-map -o -f {compoundOutputFileLuid1} -au 'Volume H2O (ul)' -au 'Sample Volume (ul)'"
```

The only difference is that columns "Source container" and "Source well" have been removed from the top table as that data seemed to be dulicated with "Original container" and "Original well". See difference below in the before and after pictures:
![Screenshot 2023-02-03 at 10 40 08](https://user-images.githubusercontent.com/60181709/216566796-2bb2c985-5036-4a68-8eab-2c979dfe4d35.png)
![Screenshot 2023-02-03 at 10 40 16](https://user-images.githubusercontent.com/60181709/216566810-59561235-a9b1-4202-90de-6569c8446197.png)

The next task will be to perform the same transition to the new EPP for steps still using the old 96well_placement_map (see https://github.com/Clinical-Genomics/cg_lims/issues/146).
