### ISSUE TITLE
Update automation "Atlas Method Document"

### ISSUE THREAD

**Issue by cesve** [Clinical-Genomics/cg_lims#291]
Lims Issue
---------------

For definitions of headings below see [Basic Concepts](https://atlas.scilifelab.se/infrastructure/lims/basic_concepts/).

**Work Flow:** NA
**Protocol:** NA
**Step:** NA

**Description:** In a lab meeting (2022-06-01) it was decided that the process UDF's where the user specify Methods will have a more strict and consistent nomenclature.

For library preparation methods: "Library Preparation Method 1,2,3..."
For Supporting procedures: "Supporting Procedure Document 1,2,3..."
For Equipments: "Equipment Document 1,2,3..."

We will update the automation "Atlas Method Document" to include all different documents:

bash -c -l "conda activate cg_lims && lims -c /home/glsai/.genologics.yaml epps -l {compoundOutputFileLuid0} -p {processLuid} udf set method-document -pru 'Library Preparation Method 1' -pru 'Library Preparation Method 2' -pru 'Supporting Procedure Document 1 -pru 'Supporting Procedure Document 2' -pru 'Equipment Document 1' -pru 'Equipment Document 2'"

- [ ] Update Automation
- [ ] Update Process UDF's in affected steps (see pictures below)
<img width="614" alt="Screenshot 2022-06-02 at 08 07 29" src="https://user-images.githubusercontent.com/37171914/171564188-2e40a174-8df8-4d93-b3ac-2431d0ab17f8.png">
<img width="542" alt="Screenshot 2022-06-02 at 08 07 41" src="https://user-images.githubusercontent.com/37171914/171564195-6b12b34d-c85e-4517-b73d-5e12b0dd320f.png">
<img width="608" alt="Screenshot 2022-06-02 at 08 07 59" src="https://user-images.githubusercontent.com/37171914/171564198-9d3a6cd6-f982-43ba-80fb-ce5cbadd06eb.png">

**Comment by RasmusBurge-CG** [comment]
Decided to config the button like this instead : 
```
bash -c -l "conda activate cg_lims && lims -c /home/glsai/.genologics.yaml epps -l {compoundOutputFileLuid0} -p {processLuid} udf set method-document -pru 'Method Document' -pru 'Library Preparation Method'  -pru 'Library Preparation Method 1' -pru 'Library Preparation Method 2' -pru 'Supporting Procedure Document' -pru 'Supporting Procedure Document 1' -pru 'Supporting Procedure Document 2' -pru 'Equipment Document' -pru 'Equipment Document 1' -pru 'Equipment Document 2'"
```

**Comment by RasmusBurge-CG** [comment]
If any issue with the new version this is how the old automation 'Atlas Method Document' is Configured in prod :
````bash -c -l "conda activate cg_lims && lims -c /home/glsai/.genologics.yaml epps -l {compoundOutputFileLuid0} -p {processLuid} udf set method-document -pru 'Method Document'"````

**Comment by RasmusBurge-CG** [comment]
New config in prod

**Comment by RasmusBurge-CG** [comment]
## Step to change:

- [ ] Delivery v1 
- [ ] Bcl Conversion & Demultiplexing (Nova Seq)
- [ ] CG002 - qPCR QC (Library Validation)
- [ ] CG002 - Qubit QC (DNA)
- [ ] CG002 - Microbial Library Prep (Nextera)
- [ ] CG002 - Normalization of microbial samples
- [ ] CG002 - Normalization of microbial samples for sequencing
- [ ] CG002 - Quantit QC (DNA)
- [ ] Qubit QC (RNA) v1
- [ ] Post-PCR bead purification v1
- [ ] Quantit QC (DNA) WGS v1
- [ ] End repair Size selection A-tailing and Adapter ligation (TruSeq PCR-free DNA)
- [ ] Fragment DNA (TruSeq DNA)
- [ ] Buffer Exchange v2
- [ ] Enzymatic fragmentation TWIST v2
- [ ] KAPA Library Preparation TWIST v1
- [ ] Library Preparation (Cov) v1
- [ ] Pooling and Clean-up (Cov) v1
- [ ] Sample Placement (Cov) v1
- [ ] Sample Placement (TWIST) v1
- [ ] Normalization of samples for sequencing (TWIST) v1
- [ ] CG002 - Plate Setup MAF'
- [ ] Aliquot Samples for Covaris'
- [ ] Aliquot samples for enzymatic fragmentation TWIST v2'
- [ ] Quantit QC (DNA) TWIST v2
- [ ] Qubit QC (DNA) TWIST v2
- [ ] Tapestation Reception Control TWIST v2
- [ ] Quantit QC (RNA) v1

**Comment by RasmusBurge-CG** [comment]
Done!
