### ISSUE TITLE
Volume calculation of requeued TWIST-samples (in pooling for hyb)

### ISSUE THREAD

**Issue by RasmusBurge-CG** [Clinical-Genomics/cg_lims#293]
Lims Issue
---------------

For definitions of headings below see [Basic Concepts](https://atlas.scilifelab.se/infrastructure/lims/basic_concepts/).

**Work Flow:** TWIST v7
**Protocol:** Target Enrichment TWIST v3
**Step:** Target enrichment TWIST v1

**Description:** Describe issue here!!!

Often when a sample is requeued the udf 'sample volume needed' is off. This is because the script associated with button "Calculate Volumes" looks at udf "Missing reads (m)", often when a reprep is done one wants to redo the full required amount of reads. It is therefore suggested to look at the sum of sample udfs 'Missing reads (m)' and 'Total reads (m)'  in the skript.

**Comment by RasmusBurge-CG** [comment]
@VasKyriak about right? :)

**Comment by RasmusBurge-CG** [comment]
Hi @AnnaZetterlund! How often does this happen?

**Comment by Karl-Svard** [comment]
Hej @AnnaZetterlund ! Skulle detta fortfarande vara relevant att ta en titt på?

**Comment by AnnaZetterlund** [comment]
> Hej @AnnaZetterlund ! Skulle detta fortfarande vara relevant att ta en titt på?

@Karl-Svard I asked the tga lab people and no one answered so I guess it is not relevant anymore!
