### ISSUE TITLE
New minimum requirement in initial QC WGS

### ISSUE THREAD

**Issue by saschaconradt** [Clinical-Genomics/cg_lims#295]
Lims Issue
---------------

For definitions of headings below see [Basic Concepts](https://atlas.scilifelab.se/infrastructure/lims/basic_concepts/).

**Work Flow:** WGS PCR free v5
**Protocol:** Initial QC wgs v4
**Step:**CG002-Qubit QC (DNA), Quantit QC (DNA) WGS

**Description:** Please change minimum requirement to 1100ng, above that a green flag will be assigned. Now the minimum is set to 1300ng.

**Comment by saschaconradt** [comment]
Yes that was the idea before. But now we have new rules:
- if a sample has more then 1100ng we will do normal WGS-prep
- if a sample has less then 1100ng we change to low-input-prep
Before the customer could choose to continue with normal WGS-prep if f.e 800ng

**Comment by RasmusBurge-CG** [comment]
@saschaconradt Perfect! 
>if a sample has more then 1100ng we will do normal WGS-prep 
Last stupid question, is it more or equal to 1100ng? :) If just more than I would set the minimum to 1101 ng...

**Comment by saschaconradt** [comment]
I would say also equal 1100ng. But I am not sure, I never did the WGS-prep.

**Comment by RasmusBurge-CG** [comment]
Perfect, the default value is now changed from 1300ng to 1100ng
