### ISSUE TITLE
Barcode generator EPP

### ISSUE THREAD

**Issue by RasmusBurge-CG** [Clinical-Genomics/cg_lims#298]
Lims Issue
---------------

We need a script that generates a CSV file that contains the lims-IDs in the reception control steps. 

For definitions of headings below see [Basic Concepts](https://atlas.scilifelab.se/infrastructure/lims/basic_concepts/).

**Work Flow:** Full name here please!
**Protocol:** And here!
**Step:** Here to!

**Description:** Describe issue here!!!

**Comment by cesve** [comment]
Not relevant any longer.

**Comment by RasmusBurge-CG** [comment]
https://github.com/Clinical-Genomics/cg_lims/pull/313

**Comment by RasmusBurge-CG** [comment]
Tested and in production.

**Comment by RasmusBurge-CG** [comment]
Might be good to add a option to remove the first characters, like ACC. Could look like this :

<script> -rm-str 3

**Comment by RasmusBurge-CG** [comment]
The lims-id's were t0o long to read by the instrument, this PR https://github.com/Clinical-Genomics/cg_lims/pull/324 will fix that issue.
