### ISSUE TITLE
Small bug in Micro workflow in this step "CG002 - Microbial Library Prep (Nextera)". No EPP Log and the first file is a placement map. Need to change the output of placement map file to second placeholder.

### ISSUE THREAD

**Issue by cesve** [Clinical-Genomics/cg_lims#300]

**Comment by cesve** [comment]
@RasmusBurge-CG should I do this?

**Comment by RasmusBurge-CG** [comment]
@cesve Yes please do!

**Comment by cesve** [comment]
Changed an tested on stage 22-06-24:

**_New Automation:_**
<img width="720" alt="Screenshot 2022-06-23 at 14 01 07" src="https://user-images.githubusercontent.com/37171914/175293951-6c997770-d3fa-4986-a9cc-d12ad23167db.png">

**_Sample placement:_**
<img width="872" alt="Screenshot 2022-06-23 at 13 59 39" src="https://user-images.githubusercontent.com/37171914/175294008-5a517665-83bb-4c0b-a5bc-a49dd8f22730.png">

**_Script works:_**
<img width="886" alt="Screenshot 2022-06-23 at 13 59 25" src="https://user-images.githubusercontent.com/37171914/175294095-539173b3-534c-4df5-a544-94e50bfd14f0.png">

_**Placement map with correct information:**_
<img width="1436" alt="Screenshot 2022-06-23 at 13 58 55" src="https://user-images.githubusercontent.com/37171914/175294186-c4b25a3c-4ee9-464f-8cfb-eb61c6ef39e3.png">

**Comment by cesve** [comment]
Updated on production 22-06-24:

**_New Automation:_**
<img width="720" alt="Screenshot 2022-06-23 at 14 05 45" src="https://user-images.githubusercontent.com/37171914/175294739-92d7ebed-4722-4d74-8d82-58cc163ff2ab.png">

**Comment by cesve** [comment]
Tested on a NTC in prod:

Sample placement:
<img width="884" alt="Screenshot 2022-06-23 at 14 28 54" src="https://user-images.githubusercontent.com/37171914/175298698-9928a277-7edc-4536-861b-1f43fa172da1.png">

Script works:
<img width="872" alt="Screenshot 2022-06-23 at 14 14 31" src="https://user-images.githubusercontent.com/37171914/175298562-3b83618c-3e54-4442-b17b-93b67745a96e.png">

Placement map:
<img width="1437" alt="Screenshot 2022-06-23 at 14 29 42" src="https://user-images.githubusercontent.com/37171914/175298847-7c55aab3-2ee2-4514-828f-99eaa146ba1d.png">

**Comment by cesve** [comment]
In addition LIMS ID (Submitted Sample) was added.

Changes work well!
