### ISSUE TITLE
Set "Primer" for all sars-cov-2 samples processed so far

### ISSUE THREAD

**Issue by henningonsbring** [Clinical-Genomics/cg_lims#303]
We have a new UDF in LIMS called "Primer"
![Screenshot 2022-06-28 at 19 08 29](https://user-images.githubusercontent.com/66672810/176242149-b39fb550-0928-4aba-9a5a-2c5410113e2d.png)

We need to set this field to "Illumina Artic V3". A list of samples where this needs to be set can be found here: `/home/hiseq.clinical/HO_data_processing/projects/retroactively_add_primer_names/all_samples_ever_analyzed.txt`

This issue can be closed when primer is assigned to all our old sarscov2 analyses.

**Comment by henningonsbring** [comment]
Not sure if it matters, but pay attention to that the primer field only got two options. I assume it is important that the information is submitted in the exact same way as the "selectable option" is written. Users can't set this value via free text.

**Comment by Karl-Svard** [comment]
**32565** out of **32660** samples from the list have now been updated with the sample udf "Primer" set to "Illumina Artic V3". The 95 non-updated samples could not be found in lims as they were cancelled in ticket [#158161](https://clinical-scilifelab.supportsystem.com/scp/tickets.php?id=44006).
