### ISSUE TITLE
Minor changes to lucigen

### ISSUE THREAD

**Issue by RasmusBurge-CG** [Clinical-Genomics/cg_lims#305]
Lims Issue
---------------

For definitions of headings below see [Basic Concepts](https://atlas.scilifelab.se/infrastructure/lims/basic_concepts/).

**Work Flow:** WGS PCR free v5
**Protocol:** TruSeq DNA PCR-free Library Prep
**Step:** Aliquot Samples for Covaris

**Description:**
One udf "Lot no: EB or RB" is wrong, for lucigen EB is never used, water is.

One button is called "Calculate RB volume" a better name would be "Calculate volume of dilution buffer", because RB is not used in the lucigen protocol.

**Comment by cesve** [comment]
As we're working on a new WGS-prep protocol that will be able to handle all kind of samples we'll wait with this issue. Closing.
