### ISSUE TITLE
Quantit result file upload in WGS RC

### ISSUE THREAD

**Issue by ceciliamattssonscilifelab** [Clinical-Genomics/cg_lims#306]
Lims Issue
---------------
Not possible to upload more than one Quantit Result File 

**Work Flow:** Initial QC wgs v4
**Protocol:** AM 1843 and Reception control of incoming WGS-samples
**Step:** Quantit QC (DNA) WGS v1

**Description:** When there is more than 88 samples in the WGS RC, two or more quantit plates are prepared in the lab. It is possible in LIMS to add more plates in the layout view, when you place the samples in the quantit plate. But it not possible to upload more than one result file.

**Comment by RasmusBurge-CG** [comment]
This is possible but I cannot see the benefit compare to just starting two steps in lims. I might be missing some additional information, please let me know if this is the case.

**Comment by ceciliamattssonscilifelab** [comment]
Thanks for the comments @RasmusBurge-CG!

It could be convenient to have all samples in the same step. But if it works well for everyone as it is, then we don't need to make a change. Then we can clarify in the WGS RC-method to make two steps in LIMS.

It would be good idea to have @saschaconradt thoughts on this as well!

**Comment by saschaconradt** [comment]
I think it is ok with 2 steps in LIMS. 
I have already added the info in the RC-document "Important: The maximal quantity of samples per run is 88 (+8 standards), if you have more samples run two Quantit-plates (rcYYMMDDwgs1 / rcYYMMDDwgs2)"
