### ISSUE TITLE
Transfer 1830 to Atlas

### ISSUE THREAD

**Issue by idalindegaard** [Clinical-Genomics/cg_lims#307]
Lims Issue
---------------

For definitions of headings below see [Basic Concepts](https://atlas.scilifelab.se/infrastructure/lims/basic_concepts/).

**Work Flow:** 
**Protocol:** NovaSeq v3
**Step:** Define Run Format and Calculate Volumes (Nova Seq)

**Description:** 
Update the "Method" box to the Atlas document name "NovaSeq 6000 Sequencing method" and remove the "Version" box.

See the PR [#789](https://github.com/Clinical-Genomics/atlas/pull/789)

**Comment by RasmusBurge-CG** [comment]
Done!

**Comment by AnnaLeinfelt** [comment]
Looks like some history is not shown, see screenshot below.

Field without info displayed:
- 'Sequencing method'

Missing file attached:
- 'index check' 
I also looked at a run performed in LIMS after 1830 being transferred to Atlas and that run is also missing the 'index check' file, see run from [2022-08-19](https://clinical-lims.scilifelab.se/clarity/work-complete/351028) 

![Screen Shot 2022-08-22 at 07 52 21](https://user-images.githubusercontent.com/37171709/185848819-75abf1e7-066b-457c-bdc9-7c3edecb0f99.png)

**Comment by AnnaLeinfelt** [comment]
Never mind, - I talked to Rasmus and for 'Sequencing Method' this is available in the "hidden" information (as previous decided to do for all LIMS steps where instructions have been transferred).

The index check is supposed to be empty, it only has a file when there are duplicated indices. 

No action needed.
