### ISSUE TITLE
Show TAT in delivery

### ISSUE THREAD

**Issue by moahaegglund** [Clinical-Genomics/cg_lims#311]
Lims Issue
---------------

For definitions of headings below see [Basic Concepts](https://atlas.scilifelab.se/infrastructure/lims/basic_concepts/).

**Work Flow:** delivery
**Protocol:** And here!
**Step:** Here to!

**Description:** In delivery in LIMS we can see for how many days the samples have been in delivery, which is good, but I would like to add turnaround time as well. If we had turnaround time it would be easier for prod bioinfo to catch analyses that we might need to raise the priority of on the cluster.

**Comment by RasmusBurge-CG** [comment]
Hi @moahaegglund! Do want this new udf to be on sample level or process level?

**Comment by RasmusBurge-CG** [comment]
Or is it good enough to have it like below, with udfs "Received at" and "Delivered at"?
<img width="1065" alt="Screenshot 2022-09-20 at 13 55 14" src="https://user-images.githubusercontent.com/80392398/191251087-3b48df8c-a531-4fa4-ad39-7aa3f161096b.png">

**Comment by moahaegglund** [comment]
Hi,
Thanks for looking into this!
Actually it's in this view that I would like to see it:
![Screenshot 2022-09-20 at 14 14 54](https://user-images.githubusercontent.com/19236050/191255116-1c364457-3c1a-48fb-ba28-80e98c5ed2eb.png)

**Comment by RasmusBurge-CG** [comment]
Patch, might be nice to have a count of days.
<img width="1305" alt="Screenshot 2022-09-20 at 14 28 10" src="https://user-images.githubusercontent.com/80392398/191257464-39eea15b-fdb0-4cd6-9b9b-79c276f1a0a8.png">

**Comment by Karl-Svard** [comment]
Closing as this is as far as we can do it at the moment.
