### ISSUE TITLE
Add method instructions to Atlas Illumina_COVIDseq_on_Hamilton

### ISSUE THREAD

**Issue by MarcelaGa** [Clinical-Genomics/cg_lims#312]
Lims Issue
---------------

For definitions of headings below see [Basic Concepts](https://atlas.scilifelab.se/infrastructure/lims/basic_concepts/).

**Work Flow:** SARS-CoV-2 v3
**Protocol:** Library Prep (Cov) v2
                     
**Step:** Sample placement (Cov)
                 Library Preparation (Cov)
                 Pooling and Clean-up (Cov)

**Description:** Please add the Atlas method Illumina_COVIDseq_on_Hamilton. Thank you!

**Comment by RasmusBurge-CG** [comment]
Hi @MarcelaGa! We have added the new document to LIMS, please "remove" 2203 from AM. :)

**Comment by MarcelaGa** [comment]
Thanks Rasmus! I've sent the doc deprecated for AL approval in AM.

**Comment by RasmusBurge-CG** [comment]
Done! https://github.com/Clinical-Genomics/atlas/pull/996, let's do the next step when you have time @idalindegaard.

**Comment by idalindegaard** [comment]
Now it's done!

**Comment by RasmusBurge-CG** [comment]
@MarcelaGa told me that we need to add this to one more step @idalindegaard

**Comment by MarcelaGa** [comment]
Hi! Yes, please add the Atlas doc to the step Sample Placement (Cov) as well. Thanks!
