### ISSUE TITLE
Add Atlas link for manual KAPA in lims

### ISSUE THREAD

**Issue by EmiliaRegazzoni** [Clinical-Genomics/cg_lims#315]
Lims Issue
---------------

For definitions of headings below see [Basic Concepts](https://atlas.scilifelab.se/infrastructure/lims/basic_concepts/).

**Work Flow:** TWIST v7

**Protocol 1:** Library Prep TWIST v2
**Steps:** 
- [x] Aliquot samples for enzymatic fragmentation
- [x] Enzymatic fragmentation TWIST
- [x] KAPA Library Preparation

**Protocol 2:** Target Enrichment TWIST v3
**Steps:** 
- [x] Pool samples for hybridization TWIST
- [x] Target enrichment TWIST

**Protocol 3:** Normalization of samples for sequencing (TWIST)
**Steps:** 
- [x] Normalization of samples for sequencing (TWIST)

**Description:** We are adding the manual KAPA prep to Atlas! It may be available to choose in some steps (see: https://clinical-lims.scilifelab.se/clarity/work-complete/357505) but is lacking entirely in some steps: https://clinical-lims.scilifelab.se/clarity/work-complete/358408). Could you add the atlas and remove the AM option after this?

**Comment by idalindegaard** [comment]
I'm looking at it today!

**Comment by EmiliaRegazzoni** [comment]
Wonderful! I have removed the WIP and the AM document will be depreciated later today when AL is able to! I think you can remove the AM doc options now as well

**Comment by idalindegaard** [comment]
Ok, great!
