### ISSUE TITLE
Add Barcodes at Clinical Genomics to RC WGS

### ISSUE THREAD

**Issue by RasmusBurge-CG** [Clinical-Genomics/cg_lims#316]
Lims Issue
---------------

For definitions of headings below see [Basic Concepts](https://atlas.scilifelab.se/infrastructure/lims/basic_concepts/).

**Work Flow:** Full name here please!
**Protocol:** Reception Control v3
**Step:** Initial QC wgs v4

**Description:** 
Add document Barcodes at Clinical Genomics to Initial QC wgs v4

**Comment by idalindegaard** [comment]
Done!
