### ISSUE TITLE
Add Barcodes at Clinical Genomics to RC TGA

### ISSUE THREAD

**Issue by RasmusBurge-CG** [Clinical-Genomics/cg_lims#317]
Lims Issue
---------------

For definitions of headings below see [Basic Concepts](https://atlas.scilifelab.se/infrastructure/lims/basic_concepts/).

**Work Flow:** Full name here please!
**Protocol:** Pre Processing TWIST v3
**Step:** Reception Control TWIST

**Description:** Describe issue here!!!
Add this document [Barcodes at Clinical Genomics](https://atlas.scilifelab.se/production/lab/supporting_procedures/barcodes_at_cg/) to the step mentioned.

**Comment by idalindegaard** [comment]
Done!
