### ISSUE TITLE
New workflow "WGS PCR-Free Tagmentation"

### ISSUE THREAD

**Issue by RasmusBurge-CG** [Clinical-Genomics/cg_lims#319]
Validation steps
---
- [ ] Validation report https://github.com/Clinical-Genomics/validations/pull/57 
- [ ] Perform test--> new version of "Validation Report" with signed Test specifications. 
- [ ] Implementation plan of new workflow

Building workflow steps
----

| Workflow name: | WGS PCR-Free Tagmentation  |
|---|---|

**All** details regarding steps, udf's and similar, will be documented in document [Workflow Details](https://docs.google.com/document/d/12oFxvZdLc2vPU9jAsrVwok9NB32mjVs3qa96dCEK8o4/edit?usp=sharing). (Update 230316: This document has been deleted, maybe when Rasmus' scilifelab-account was removed)

Method here: https://docs.google.com/document/d/1ALF3ZOiuxfdZxQMXKjzmn8Wqyv-pXdAyx8RgJYoOi84/edit#heading=h.civpcarm52us

Checklist
---
- [ ] Add trending by Arnold.

**Comment by RasmusBurge-CG** [comment]
Hi @AnnaLeinfelt! Looking at the validation steps, we have one that says:
> Documenting results in Clarity LIMS (Atlas) - Update with new WF"
How should we document this?

**Comment by AnnaLeinfelt** [comment]
This refers to the previous document in Atlas called Documenting results…

How are the wf specific “things” documented in Atlas today?
