### ISSUE TITLE
New Return Samples WF

### ISSUE THREAD

**Issue by RasmusBurge-CG** [Clinical-Genomics/cg_lims#321]
- [x] [LIMS Validation report](https://github.com/Clinical-Genomics/validations/pull/58) approved and signed by VW, ALY and AL 221202
- [x] [Implementation plan](https://github.com/Clinical-Genomics/validations/issues/63) signed by AL, AZ, ALY and VW 221206
- [x] Perform tests - Done by RB 221012

**Comment by RasmusBurge-CG** [comment]
Hi! I just created all the "Return Samples" workflow in production LIMS.

**Comment by RasmusBurge-CG** [comment]
Test on stage
![Screenshot 2022-10-12 at 15 07 24](https://user-images.githubusercontent.com/80392398/195350869-ad0ed21d-fb69-4686-b69c-80eabe936dee.png)

**Comment by saschaconradt** [comment]
I processed all DNA-samples which we returned during 2022 in "LIMS Return Samples-workflow" and uploaded the corresponding returning samples documents.
