### ISSUE TITLE
Change accepted amount values in script "Calculate RB volume"

### ISSUE THREAD

**Issue by idalindegaard** [Clinical-Genomics/cg_lims#322]
Lims Issue
---------------

For definitions of headings below see [Basic Concepts](https://atlas.scilifelab.se/infrastructure/lims/basic_concepts/).

**Work Flow:** WGS PCR-Free Tagmentation v.2, WGS PCR free v5
**Protocol:** Illumina DNA PCR-Free Library prep (WGS) v.1, TruSeq DNA PCR-free Library Prep
**Step:** Aliquot Samples for Tagmentation v.1, Aliquot Samples for Covaris

**Description:** 
For the new WGS workflow, WGS PCR-Free Tagmentation v.2, we want to have an amount of 500 ng, but the EPP "Calculate RB volume" is limited and only accepts values 200 or 1100 ng. We only need this change for the new workflow, but I added the old steps where this script is used FYI. Would be good to eliminate the limitation completely and accept all values.

**Comment by Karl-Svard** [comment]
See PR #325 for a possible solution

**Comment by idalindegaard** [comment]
<img width="1098" alt="Screen Shot 2022-10-06 at 10 45 14" src="https://user-images.githubusercontent.com/82438141/194269113-40da542c-4fe1-4861-a7b4-be163d4fa0e1.png">

Tested the script on stage ([#325](https://github.com/Clinical-Genomics/cg_lims/pull/325)) and it looks good!
