### ISSUE TITLE
Add Hamilton Udf in Lims Aliquotation step for WGS

### ISSUE THREAD

**Issue by FayKanellidou** [Clinical-Genomics/cg_lims#330]
Lims Issue
---------------

For definitions of headings below see [Basic Concepts](https://atlas.scilifelab.se/infrastructure/lims/basic_concepts/).

**Work Flow:** WGS PCR free v5
**Protocol:** TruSeq DNA PCR-free Library Prep
**Step:** Aliquot Samples for Covaris

**Description:** Describe issue here!!!

In Aliquot Samples for Covaris step in supporting procedure document UDF we need to have the options for Hamilton normalisation and pooling and we need one more UDF box for choosing the Hamilton used (leslie or laura).

Checklist:
- [x] Add document "Hamilton normalisation and pooling" to UDF Supporting Procedure Document 221020/IL
- [x] Add new UDF with choices Leslie/Laura/NA 221020/IL

**Comment by idalindegaard** [comment]
Done @FayKanellidou! Let me know if there are any issues
