### ISSUE TITLE
Add qPCR in the copy task menu of  the Aggregate QC (Library Validation) (Dev)

### ISSUE THREAD

**Issue by MariaSalli** [Clinical-Genomics/cg_lims#331]
**Lims Issue**
---------------

For definitions of headings below see [Basic Concepts](https://atlas.scilifelab.se/infrastructure/lims/basic_concepts/).

**Work Flow:** Development work flow v3
**Protocol:** Library validation QC (Dev) v3
**Step:** Aggregate QC (Library Validation) (Dev)

**Description:** We are missing the qPCR option (only Quantit and Qubit is available) in the dropdown menu of the Copy task 1 - Source Step box in the Aggregate QC (Library Validation) (Dev) step.

![aggregate qc dev](https://user-images.githubusercontent.com/82388181/197720790-97f14f34-9a6b-4244-a95a-25a7a2242667.jpg)

**Comment by idalindegaard** [comment]
I've fixed it now, hope it works :) @MariaSalli @susannemaner
