### ISSUE TITLE
Add new Atlas Tapestation doc in LIMS workflows.

### ISSUE THREAD

**Issue by VasKyriak** [Clinical-Genomics/cg_lims#333]
Lims Issue
---------------

For definitions of headings below see [Basic Concepts](https://atlas.scilifelab.se/infrastructure/lims/basic_concepts/).

**Work Flow, Protocols and Steps:** 

- [x] Initial QC TWIST v3 --> Tapestation Reception control TWIST
- [x] Library Validation QC TWIST v2 —> Tapestation QC TWIST
- [x] Library Validation QC TWIST (post hyb) —> Tapestation QC TWIST
- [x] Microbial Library Validation QC v3 —> CG002 - Tapestation Microbial QC
- [x] Initial QC (RNA) v2 --> Tapestation Reception control RNA
- [x] Library Validation QC (RNA) --> Tapestation QC (RNA)
- [x] Library Validation QC RNA (post norm) --> Tapestation QC (RNA)

**Description:** The TapeStation 4200 - Nucleic Acid Fragment Size Analysis System doc is ready to move from AM to Atlas, therefore the LIMS steps that include this analysis require update.

**Comment by idalindegaard** [comment]
@VasKyriak Now all steps are done, hope everything works!
