### ISSUE TITLE
Small adjustments for reception control in lims

### ISSUE THREAD

**Issue by EmiliaRegazzoni** [Clinical-Genomics/cg_lims#334]
Lims Issue
---------------

For definitions of headings below see [Basic Concepts](https://atlas.scilifelab.se/infrastructure/lims/basic_concepts/).

**Work Flow:** WGS
**Protocol:** reception control
**Step:** Quantit QC (DNA) WGS v1

**Description:**
- in lims, Quantit QC (DNA) WGS v1, could you set lumous to the default plate reader?
- In the same step the Hamilton instruments need to be added, this is also true for the tga RC and for both quantit and tapestation in both workflows.
- There are different limits in the preset for WGS quantit and qubit - could these be changed so they are the same?

**Comment by idalindegaard** [comment]
@EmiliaRegazzoni About the last bullet point: what limits do you want for both?

**Comment by EmiliaRegazzoni** [comment]
<img width="700" alt="image" src="https://user-images.githubusercontent.com/92719658/199739039-bd8ab707-aabe-4e6e-aa39-44f72eb55fca.png">

as in the wgs RC protocol I think - am I correct @MarcelaGa and @saschaconradt?

**Comment by MarcelaGa** [comment]
Should we bring this to the lab meeting on Monday maybe?

**Comment by idalindegaard** [comment]
I have completed the things on the list. Changed the minimum required amount (ng) for Quantit from 1100 ng to 1300 ng according to the RC document so now it's the same for both Qubit and Quantit. If we want to change this, I can easily fix it again.

@MarcelaGa shall I wait with closing the issue until it's discussed on Monday?

**Comment by saschaconradt** [comment]
@idalindegaard 1100ng is the correct limit for WGS-samples (the table is wrong, I have updated it in a new PR). Is that correct @AnnaZetterlund?

**Comment by AnnaZetterlund** [comment]
> @idalindegaard 1100ng is the correct limit for WGS-samples (the table is wrong, I have updated it in a new PR). Is that correct @AnnaZetterlund?

It is correct that we use 1100 ng for the prep. I think 1300 ng is from before when we had that as a limit on the homepage?

**Comment by EmiliaRegazzoni** [comment]
Should it be a deviation that we have been using different/incorrect limits for wgs?

**Comment by AnnaZetterlund** [comment]
> Should it be a deviation that we have been using different/incorrect limits for wgs?

I believe we have always used 1100 ng in the prep. Correct?

**Comment by EmiliaRegazzoni** [comment]
I meant for the RC, we have had different limits for qubit and quantit and the limit in the document was 1300?

**Comment by idalindegaard** [comment]
Yes, maybe that would require a deviation, although the grade is pretty low

**Comment by idalindegaard** [comment]
I have now changed so it's 1100 ng everywhere

**Comment by annaengstrom** [comment]
We use 1100 ng for the prep. 1300 ng is to be able to do both WGS and lucigen if a prep fails. Our normal routine is to always to be able to two two preps

**Comment by idalindegaard** [comment]
Ahh okay, now it makes total sense. Soo, I change back again then to 1300 ng as cutoff
