### ISSUE TITLE
Change SMTP configuration to use new KTH accounts

### ISSUE THREAD

**Issue by Karl-Svard** [Clinical-Genomics/cg_lims#337]
Lims Issue
---------------

**Description:** 
The old SMTP service used to send emails have been replaced and a set of new accounts have been granted from KTH (see https://github.com/Clinical-Genomics/IT-issues/issues/622). 

It will require some set-up to get these up and running, and will document my process here. When complete we will have two new email addresses that will replace the old noreply.claritylims@genologics.com:

For prod: noreply-claritylims@scilifelab.se
For stage: noreply-claritylims-stage@scilifelab.se

**Comment by Karl-Svard** [comment]
Updates have been tested and deployed to both prod and stage. Email functionalities are now back. 

A new configuration of Grails was set up to support KTH SMTP's move to STARTTLS. The following options were used in `/opt/gls/clarity/tomcat/apache-tomcat-8.5.34/lib/activity-management-ui-config.groovy`:

Prod configuration:
```
grails.mail.host="smtp.kth.se"
grails.mail.port="587"
grails.mail.username=see in file
grails.mail.password=see in file
grails.mail.props=[
    "mail.smtp.starttls.enable": "true",
    "mail.smtp.port": "587",
    "mail.smtp.ssl.protocols": "TLSv1.2"
]
grails.mail.default.from="noreply-claritylims@scilifelab.se"
```

Stage configuration:
```
grails.mail.host="smtp.kth.se"
grails.mail.port="587"
grails.mail.username=see in file
grails.mail.password=see in file
grails.mail.props=[
    "mail.smtp.starttls.enable": "true",
    "mail.smtp.port": "587",
    "mail.debug": "true",
    "mail.smtp.ssl.protocols": "TLSv1.2"
]
grails.mail.default.from="noreply-claritylims-stage@scilifelab.se"
```

**Comment by henrikstranneheim** [comment]
@Karl-Svard Well done!
