### ISSUE TITLE
Change default to quantit

### ISSUE THREAD

**Issue by EmiliaRegazzoni** [Clinical-Genomics/cg_lims#339]
Lims Issue
---------------

For definitions of headings below see [Basic Concepts](https://atlas.scilifelab.se/infrastructure/lims/basic_concepts/).

**Work Flow:** TWIST
**Protocol:** All QC protocols
**Step:** Aggregation

**Description:** We always use Quantit to measure the concentration for TGA samples, libraries (rc, pre, post hyb, and post norm). It is easy to forget to change the preset in aggregation to quantit from qubit. We want the preset to have the default setting of quantit instead.

**Comment by idalindegaard** [comment]
I have changed the preset default option to Quantit to the steps now
