### ISSUE TITLE
Bait set version missing in Development workflow

### ISSUE THREAD

**Issue by annaengstrom** [Clinical-Genomics/cg_lims#341]
Lims Issue
---------------

For definitions of headings below see [Basic Concepts](https://atlas.scilifelab.se/infrastructure/lims/basic_concepts/).

**Work Flow:** Development
**Protocol:** Library prep
**Step:** -

**Description:** The bait set is not possible to assign in LIMS for this workflow, making[ this issue ](https://clinical-scilifelab.supportsystem.com/scp/tickets.php?id=54746)in the analysis show up. Please add a possibility to add bait set. If possible, the entire workflow should be updated.

**Comment by annaengstrom** [comment]
fyi @VasKyriak

**Comment by idalindegaard** [comment]
@annaengstrom @VasKyriak The bait set option has been added to the workflow now.

If needing a bigger update for the workflow, please list the other things you need in a new issue. Or we can talk about it some day.
