### ISSUE TITLE
Receive samples that have already done QC, CG does no RC

### ISSUE THREAD

**Issue by annaengstrom** [Clinical-Genomics/cg_lims#347]
Lims Issue
---------------

For definitions of headings below see [Basic Concepts](https://atlas.scilifelab.se/infrastructure/lims/basic_concepts/).

**Work Flow:** Different steps?
**Protocol:** And here!
**Step:** Here to!

**Description:** Some customers want to submit samples where we do no QC in RC, they want to send this information via the order. The workflow for TGA need to be updated so that we can get information from the order.

**Comment by pbiology** [comment]
Would be good to do for both TGA and WGS.

**Comment by Karl-Svard** [comment]
## LIMS steps are completed

### Added new sample UDFs
- `Skip Reception Control QC`, bool
- `Concentration (ng/ul)`, numeric

Both these are set by cg according to the info in the connected order.

### Added Skip Reception Control QC to relevant steps
For now, only steps from the workflow TWIST v8 have been updated. But you can easily add it to several ones in the future if requested.

#### Reception Control TWIST, Processing TWIST v3
- Queue
- Ice Bucket
- Record Details

#### Tapestation Reception Control TWIST, Initial QC TWIST v3
- Queue
- Ice Bucket
- Record Details

#### Qubit QC (DNA) TWIST, Initial QC TWIST v3
- Queue
- Ice Bucket

#### Quantit QC (DNA) TWIST, Initial QC TWIST v3
- Queue
- Ice Bucket

#### Aggregate QC (DNA) TWIST, Initial QC TWIST v3
- Queue
- Ice Bucket
- Record Details

### Needed to update some EPPs
- cg_lims/EPPs/udf/calculate/calculate_amount_ng.py
- cg_lims/EPPs/udf/copy/sample_to_artifact.py

See the PR for further info:
https://github.com/Clinical-Genomics/cg_lims/pull/470

### New automations
- _Copy Customer Volume and Concentration_, activated upon entry to the Aggregate QC (DNA) TWIST step. Will copy customer concentration (`Concentration (ng/ul)`) and volume (`Volume (ul)`) from the sample.
- _Calculate Amount (Aggregate QC)_, calculates the amount (ng) based on the concentration and volumes set on the input artifacts. Was also added to the Aggregate QC (DNA) TWIST step.

### Modified automations
Skipping Qubit/Quantit means we need to calculate the sample amount in the Aggregate QC step. This required a change to the current code, and thus the CLI command is slightly different. The flag `-m` is now a **requirement** for using the script in steps where UDFs are saved on measurement artifacts. The following automations were appended with this flag:
- Calculate Amount
- 2. Calculate Amount
- Prehyb QC - Calc Amount and Assign QC Flag

**Comment by Karl-Svard** [comment]
### Update 2024-03-07
After feedback on the current implementation, we have instead decided to merge `Copy Customer Volume and Concentration` into 1. Aggregate QC Flags and Copy Fields. This is to minimize the amounts of different procedures needed to process both regular samples and those that have skipped RC QC. 

New Automation created:
```
bash -c -l "conda activate cg_lims && lims -c /home/glsai/.genologics.yaml epps -l {compoundOutputFileLuid0} -p {processLuid} udf copy sample-to-artifact -sudf 'Concentration (ng/ul)' -audf 'Concentration' -i --ignore-fail && lims -c /home/glsai/.genologics.yaml epps -l {compoundOutputFileLuid0} -p {processLuid} udf copy sample-to-artifact -sudf 'Volume (uL)' -audf 'Volume (ul)' -i --ignore-fail && lims -c /home/glsai/.genologics.yaml epps -l {compoundOutputFileLuid0} -p {processLuid} udf copy aggregate-qc-and-copy-fields"
``` 

Added to Aggregate QC (DNA) TWIST v2
