### ISSUE TITLE
RC WGS/TGA: Update script that calculates amount needed to avoid negative values

### ISSUE THREAD

**Issue by annaengstrom** [Clinical-Genomics/cg_lims#348]
Lims Issue
---------------

For definitions of headings below see [Basic Concepts](https://atlas.scilifelab.se/infrastructure/lims/basic_concepts/).

**Work Flow:** WGS PCR Free v5 *AND* TWIST v7
**Protocol:** ruSeq DNA PCR-free Library Prep *AND* 
**Step:** Aliquot Samples for Covaris *AND* Aliquot samples for enzymatic fragmentation TWIST

**Description:** We will not do speedvac anymore. This means that some samples will be too dilute. When making aliquotation calculations this can lead to negative values in the volumes for DNA and buffer. We would like to update the scripts so that LIMS makes a new calculation of total amount if the sample is too dilute, i.e. if it gets negative values. The total amount should always be correct, even though it may be lower than the amount required for the method.

When this new script has been implemented, the RC WGS and RC TGA should be updated (it now specifies that the user needs to make this calculation manually).

**Comment by annaengstrom** [comment]
@EmiliaRegazzoni fyi

**Comment by Karl-Svard** [comment]
TWIST step will be fixed by https://github.com/Clinical-Genomics/cg_lims/pull/475, better late than never 🙃

**Comment by Karl-Svard** [comment]
Might as well start work on the WGS one as well. Will link the upcoming PR here

**Comment by Karl-Svard** [comment]
Closing as this will be solved in the new Watchmaker workflow
