### ISSUE TITLE
Add nuclease free H2O to step in TGA

### ISSUE THREAD

**Issue by EmiliaRegazzoni** [Clinical-Genomics/cg_lims#350]
Lims Issue
---------------

For definitions of headings below see [Basic Concepts](https://atlas.scilifelab.se/infrastructure/lims/basic_concepts/).

**Work Flow:** TWIST
**Protocol:** Library prep twist v2
**Step:** Enzymatic fragmentation TWIST

**Description:** Could you please add nuclease free H2O to step in TGA? We use it in this step but only record the lot number in the step after...

**Comment by idalindegaard** [comment]
@EmiliaRegazzoni Added!
