### ISSUE TITLE
Change QC pass limit for cfDNA samples for EPP "Calculate Amounts" in TWIST v7

### ISSUE THREAD

**Issue by idalindegaard** [Clinical-Genomics/cg_lims#356]
Lims Issue
---------------

For definitions of headings below see [Basic Concepts](https://atlas.scilifelab.se/infrastructure/lims/basic_concepts/).

**Work Flow:**TWIST v7
**Protocol:** Initial QC TWIST v3
**Step:** Quantit QC (DNA) TWIST v2 and Qubit QC (DNA) TWIST v2

**Description:** Describe issue here!!!
We will receive more and more cfDNA samples and they have a lower limit for passing the amount-check than other sample sources, which is done in steps _Quantit QC (DNA) TWIST v2_ and _Qubit QC (DNA) TWIST v2_ when running the EPP "Calculate Amounts".

The lower limit for cfDNA is **10 ng** (and 25 ng for other sources).
We want the script to also take into account the "Source" udf and make sure "cfDNA" has different QC limits

**Comment by Karl-Svard** [comment]
Looks like this is already implemented in the script?

```python
def get_qc(source: str, conc: float, amount: float) -> str:
    """QC-criteria depends on sample source, total amount and sample concentration. See AMS doc 1117, 1993 and 2125.
    The volume is subtracted by 3 in the calculations. This is beacause the lab uses 3 ul in the initial qc measurements.
    """

    qc = "FAILED"

    if source == "cfDNA":
        if amount >= 10 and conc <= 250 and conc >= 0.2:
            qc = "PASSED"
    else:
        if amount >= 250 and conc <= 250 and conc >= 8.33:
            qc = "PASSED"

    return qc
``` 

Or should we lower the threhold of normal samples from 250 to 25 ng?

**Comment by idalindegaard** [comment]
The script did not work for some cfDNA samples this week, but I saw that the sample source for cfDNA is written as "cell-free DNA", so the script needs an update (looking at the previous comment from KSV)

**Comment by Karl-Svard** [comment]
PR opened https://github.com/Clinical-Genomics/cg_lims/pull/445
