### ISSUE TITLE
New data from lims

### ISSUE THREAD

**Issue by EmiliaRegazzoni** [Clinical-Genomics/cg_lims#364]
Lims Issue
---------------

For definitions of headings below see [Basic Concepts](https://atlas.scilifelab.se/infrastructure/lims/basic_concepts/).

**Work Flow:** TWIST
**Protocol:** Target Enrichment TWIST v3
**Step:** Target enrichment TWIST

**Description:** Discussed with KS and ALY. We would like to know the number of pools prepped per week with each bait set in an easy way without having to record information in more places than just lims. This is for fun statistics as well as inventory purposes. It would be great if this info was easy to access / readily available.

**Comment by idalindegaard** [comment]
Linked to [557](https://github.com/Clinical-Genomics/project-planning/issues/557)

**Comment by idalindegaard** [comment]
The data can be retrieved and handled for the intended purpose with the help of Advanced search, the new feature that came with the lims 6.2 version update. EDER looked into it today and approved, so the issue can be closed
