### ISSUE TITLE
Verification of new workflow version: WGS PCR free v6

### ISSUE THREAD

**Issue by idalindegaard** [Clinical-Genomics/cg_lims#370]
Lims Issue
---------------

For definitions of headings below see [Basic Concepts](https://atlas.scilifelab.se/infrastructure/lims/basic_concepts/).

**Work Flow:** WGS PCR free v6
**Protocol:** Initial QC wgs v4, TruSeq DNA PCR-free Library Prep, Library validation QC wgs v4
**Step:** All steps

## Description:
With the new workflow setup where we have two separate sequencing workflows (NovaSeq 6000 and NovaSeq X), we need to create new versions of all workflows that end with sequencing. We will remove protocols NovaSeq v3 and Delivery v1, and include a new automation to queue the samples to an intermediate workflow, Queue samples for sequencing. Following documents [New workflow in LIMS](https://atlas.scilifelab.se/infrastructure/lims/development/new_workflow/) and [Validation and verification](https://atlas.scilifelab.se/validation/validation_and_verification/#verifications-in-lims), all new versions of workflows need to be verified. 

The verification includes 

-  creating the new workflow version in [the LIMS stage environment](https://clinical-lims-stage.scilifelab.se/clarity/)
-  testing it with different scenarios and adding screenshots of the tests in this issue
-  create the workflow in [the LIMS production environment](https://clinical-lims.scilifelab.se/clarity/)
-  test the workflow in production

Since many protocols are straight out copied from the previous version they won't go through extensive testing, we will just check that they perform satisfactorily with regular samples.

## Actions:

The new workflow is essentially the same as v5, and consists of three protocols:

**Initial QC wgs v2**: same protocol as WGS PCR free v5
**TruSeq DNA PCR-free Library Prep**: same protocol as WGS PCR free v5 
**Library validation QC wgs v4**: new protocol, same as v3, but with updated _Aggregate QC (Library Validation)_
- created new Automation _Set library prep date and Queue samples for sequencing_
- added new automation to master step Aggregate QC (Library Validation)
- activated automation as _Automatic on exit_ in _Record details_

| Protocol | Created in Stage | Tested in Stage | Created in Production  | 
|---|---|---|---|
| Initial QC wgs v4 | N/A* | Done! 2023-05-16 ARW | N/A  | 
| TruSeq DNA PCR-free Library Prep | N/A* | Done! 2023-05-16 ARW | N/A  |  
| Library validation QC wgs v4 | Done! 2023-05-15 ARW | Done! 2023-05-17 ARW | 2023-05-26 ARW  | 

*This protocol is the same as in the previous version of the workflow

**Testing setup:**

Eight samples will be run through the entire workflow. For protocols **Initial QC wgs v4** and **TruSeq DNA PCR-free Library Prep**, the samples will just be passed on through the steps to test that they perform the same as in the current workflow (v5). For protocol **Library validation QC wgs v4**, only the last step has been altered as compared to v3. This step will be verified to see that the new function of queueing samples to the workflow Queue Samples for Sequencing works.

The plate was named verwgs230516

For result files for Quant-iT, Tapestation and qPCR, result files from production were used. The files can be found in the respective folder in the [screen shot folder on Google Drive](https://drive.google.com/drive/folders/15gzKDwTFs7CXyfJY6C5c3VHz8Pbhvwg5) 

All samples were from #116728

|     Lims-ID    |    Sample    | Apptag |
|-------------------|----------------------|------------|
|     ACC11297A2    |     2023-02343-03    | WGSPCFC030 |
|     ACC11297A3    |     2023-02367-03    | WGSPCFC030 |
|     ACC11297A4    |     2023-02409-03    | WGSPCFC030 |
|     ACC11297A5    |     2023-02412-03    | WGSPCFC030 |
|     ACC11297A6    |     2023-02529-03    | WGSPCFC030 |
|     ACC11297A7    |     2023-02535-03    | WGSLIFC030 |
|     ACC11297A8    |     2023-02569-03    | WGSPCFC030 |
|     ACC11297A9    |     2023-02572-03    | WGSPCFC030 |

| Protocol | Step | Test specification | Comments/Results  | P/F  | Sign | 
|---|---|---|---|---|---| 
| Initial QC wgs v4 | CG002 - Reception Control | N/A** | All 8 samples passed without error messages. All EPPs functional  |   P | 2023-05-16 ARW
| Initial QC wgs v4 | CG002 - Qubit QC (DNA) | N/A** | All 8 samples passed without error messages. All EPPs functional  |  P |  2023-05-16 ARW
| Initial QC wgs v4 | Quantit QC (DNA) WGS v1 | N/A** |  Used result file rc230516wgs. All 8 samples passed without error messages. All EPPs functional  | P  | 2023-05-16 ARW
| Initial QC wgs v4 | Tapestation QC (DNA) WGS v3 | N/A** | Used result file from rc221221tga. All 8 samples passed without error messages. All EPPs functional  | P  | 2023-05-16 ARW
| Initial QC wgs v4 | Aggregate QC (DNA) | N/A** | All 8 samples passed without error messages. All EPPs functional  | P  | 2023-05-16 ARW
| TruSeq DNA PCR-free Library Prep | Aliquot Samples for Covaris | N/A** |  All 8 samples passed without error messages. All EPPs functional  | P  | 2023-05-16 ARW
| TruSeq DNA PCR-free Library Prep | Fragment DNA (TruSeq DNA) | N/A** | All 8 samples passed without error messages. All EPPs functional  | P  | 2023-05-16 ARW
| TruSeq DNA PCR-free Library Prep | End repair Size selection A-tailing and Adapter ligation (TruSeq PCR-free DNA) | N/A** |   All 8 samples passed without error messages | P  | 2023-05-16 ARW
| Library validation QC wgs v4 | Tapestation QC (DNA) WGS v3 |N/A**  |  Used result file from rc221221tga. All 8 samples passed without error messages. All EPPs functional  | P  | 2023-05-16 ARW
| Library validation QC wgs v4 | CG002 - qPCR QC (Library Validation) | N/A** |  Used result file from wgs230511_col1-4. All 8 samples passed without error messages. All EPPs functional  | P  | 2023-05-16 ARW
| Library validation QC wgs v4 | CG002 - Qubit QC (Library Validation) | N/A** | It was noted that automations Posthyb QC and Prehyb QC were activated on this step, and that the step had two presents (prehyb and posthyb). These were removed from the step. All 8 samples passed without error messages. All EPPs functional  | P  | 2023-05-16 ARW
| Library validation QC wgs v4 | Quantit QC (DNA) WGS v1 | N/A** |  Used result file from wgs230511_col1-4. All 8 samples passed without error messages. All EPPs functional  | P  | 2023-05-16 ARW
| Library validation QC wgs v4 | Aggregate QC (Library Validation) | Test 4 samples with preset Quant-it and 4 with preset qPCR. Check that there are no errors with EPPs. Check that samples are queued to the correct workflow |  All 8 samples passed without error messages. All EPPs functrional. All 8 samples were successfully aggregated and queued to the correct workflow |  P | 2023-05-17 ARW

**The step is the same as in the previous version of the workflow and will not be tested specifically with different scenarios

#### **Project resources:**

Screen shots of all steps can be found on [Google Drive](https://drive.google.com/drive/folders/15gzKDwTFs7CXyfJY6C5c3VHz8Pbhvwg5) 

## **Conclusions:**

The workflow WGS PCR free v6 has passed the verification and is ready to be activated and used in production. 

## **Sign off**

| Head of Unit Lab | Date |
|----------------- |------|
|        ALY                      |     2023-08-25     |

## **Implementation**

| What is needed to implement changes |  Item        |  Date signature    |
|--------------------------------------- |---------- |--------------------|
|  *Information to staff*             |    1. Email sent out to email adress clinical_production@scilifelab.se  <br> 2. Inform during lab meeting <br> 3. Inform lab staff on Slack when workflow is activated    |  1. 2023-08-23 IL  <br>  2. 2023-08-28 ARW + IL  <br> 3. 230829/ARW+IL |
|  *Documentation*                    |   Not needed   |      N/A              |
|  *Test in production*          |   Monitor workflow performance during the first week after activation    |    2023-09-05  ARW + IL             |
|  *Move ongoing samples*                            |  Move all ongoing samples to new workflow    |      2023-08-30 ARW + IL              |
|  *Move negative controls*                            |    N/A     |      N/A          |
|  Archive old workflow version   | Archive WGS PCR free v5 | KSV |

- [x] Verification completed and implemented

**Comment by amandaraud** [comment]
Verification done! Ready to be created in production.

**Comment by amandaraud** [comment]
Created in production, ready to be activated and tested.
