### ISSUE TITLE
Verification of new workflow version: NIPT v2

### ISSUE THREAD

**Issue by idalindegaard** [Clinical-Genomics/cg_lims#371]
Lims Issue
---------------

For definitions of headings below see [Basic Concepts](https://atlas.scilifelab.se/infrastructure/lims/basic_concepts/).

**Work Flow:** NIPT v2
**Protocol:** Reception Control NIPT v1, Pool samples NIPT v2
**Step:** 

## Description:

With the new workflow setup where we have two separate sequencing workflows (NovaSeq 6000 and NovaSeq X), we need to create new versions of all workflows that end with sequencing. We will remove protocols NovaSeq v3 and Delivery v1, and include a new automation to queue the samples to an intermediate workflow, Queue samples for sequencing. Following documents [New workflow in LIMS](https://atlas.scilifelab.se/infrastructure/lims/development/new_workflow/) and [Validation and verification](https://atlas.scilifelab.se/validation/validation_and_verification/#verifications-in-lims), all new versions of workflows need to be verified. 

The verification includes 

-  creating the new workflow version in [the LIMS stage environment](https://clinical-lims-stage.scilifelab.se/clarity/)
-   testing it with different scenarios and adding screenshots of the tests in this issue
-  create the workflow in [the LIMS production environment](https://clinical-lims.scilifelab.se/clarity/)
-  test the workflow in production

Since many protocols are straight out copied from the previous version they won't go through extensive testing, we will just check that they perform satisfactorily with regular samples.

## Actions:

The new workflow is essentially the same as v1,  and consists of two protocols:

**Reception Control NIPT v1** same protocol as in NIPT v1
**Pool samples NIPT v2** new protocol, with updated step _Library Pooling NIPT_
- created new Automation _Queue samples for sequencing_
- added new automation to master step Library Pooling NIPT
- activated automation as _Automatic upon exit_ in _Record details_

| Protocol | Created in Stage | Tested in Stage | Created in Production  | 
|---|---|---|---|
| Reception Control NIPT v1 | NA*  |  2023-05-17 ARW | N/A  | 
| Pool samples NIPT v2 | 2023-05-05 ARW | 2023-05-17 ARW | 2023-05-26 ARW  |  

*This protocol is the same as in the previous version of the workflow

Testing setup:

Eight samples will be run through the entire workflow. For protocol **Reception Control NIPT v1**, the samples will just be passed on through to test that the protocol performs the same as in the current workflow (NIPT v1). For protocol **Pool samples NIPT v2**, the step *Library Pooling NIPT* will be verified to see that the new function of queueing samples to the workflow Queue Samples for Sequencing works.

The plate was named vernipt230517

All 8 samples were from #983783

| LIMS ID (Sample) | Sample Name   | Sequencing Analysis |
|------------------|---------------|---------------------|
| ACC11378A1       | 2023-03170-03 | RMLP05R800          |
| ACC11378A2       | 2023-03174-03 | RMLP05R800          |
| ACC11378A3       | 2023-03175-03 | RMLP05R800          |
| ACC11378A4       | 2023-03176-03 | RMLP05R800          |
| ACC11378A5       | 2023-03178-03 | RMLP05R800          |
| ACC11378A6       | 2023-03212-03 | RMLP05R800          |
| ACC11378A7       | 2023-03213-03 | RMLP05R800          |
| ACC11378A8       | 2023-03214-03 | RMLP05R800          |

| Protocol | Step | Test specification | Comments/Results  | P/F  | Sign | 
|---|---|---|---|---|---| 
| Reception Control NIPT v1 | Reception Control NIPT | NA** | All 8 samples passed without error messages. All EPPs functional.  | P | 2023-05-17 ARW
| Pool samples NIPT v2 | Library Pooling NIPT | Check that there are no errors with EPPs. Check that samples are queued to the correct workflow| All 8 samples passed without error messages. Pooling successful. All 8 samples were successfully aggregated and queued to the correct workflow  | P | 2023-05-17 ARW

**The step is the same as in the previous version of the workflow and will not be tested specifically with different scenarios

#### **Project resources:**

Screen shots of all steps can be found on [Google Drive](https://drive.google.com/drive/folders/14FO6m1nE1oVvaSPSA4vog4iaWlMQeRsx) 

## **Conclusions:**

The workflow NIPT v2 has passed the verification and is ready to be activated and used in production. 

## **Sign off**

| Head of Unit Lab | Date |
|----------------- |------|
|            ALY                  |    2023-08-25      |

## **Implementation**

| What is needed to implement changes |  Item        |  Date signature    |
|--------------------------------------- |---------- |--------------------|
|  *Information to staff*             |    1. Email sent out to email adress clinical_production@scilifelab.se  <br> 2. Inform during lab meeting <br> 3. Inform lab staff on Slack when workflow is activated   |  1. 2023-08-23 IL  <br>  2. 2023-08-28 ARW + IL  <br> 3. 230829/ARW+IL |
|  *Documentation*                    |  NovaSeq 6000 Sequencing method refers to Pool samples NIPT v1 in section 3.2.1.1 NIPT  @idalindegaard      |   2023-09-01 IL                 |
|  Test in production           |   Monitor workflow performance during the first week after activation     |  2023-09-05 ARW+IL               |
|  *Move negative controls*                            |    N/A       |          N/A          |
|  *Move ongoing samples*                            |    N/A (workflow update was performed between two NIPT runs)      |          N/A          |
|  Archive old workflow version  | Archive workflow *NIPT v1* | KVS |

- [x] Verification completed and implemented

**Comment by amandaraud** [comment]
Verification done! Ready to be created in production.

**Comment by amandaraud** [comment]
Workflow created in production, ready to be activated and tested.

**Comment by amandaraud** [comment]
Ready to be signed off @annaengstrom
