### ISSUE TITLE
Verification of new workflow version: Microbial WGS v7

### ISSUE THREAD

**Issue by idalindegaard** [Clinical-Genomics/cg_lims#372]
Lims Issue
---------------

For definitions of headings below see [Basic Concepts](https://atlas.scilifelab.se/infrastructure/lims/basic_concepts/).

**Work Flow:** Microbial WGS v7
**Protocol:** Pre Processing Microbial v1, Initial QC Microbial v3, Nextera Microbial WGS v4, Microbial Library Validation QC v3, CG002 - Normalization of microbial samples for sequencing v2
**Step:**

## Description:
With the new workflow setup where we have two separate sequencing workflows (NovaSeq 6000 and NovaSeq X), we need to create new versions of all workflows that end with sequencing. We will remove protocols NovaSeq v3 and Delivery v1, and include a new automation to queue the samples to an intermediate workflow, Queue samples for sequencing. Following documents [New workflow in LIMS](https://atlas.scilifelab.se/infrastructure/lims/development/new_workflow/) and [Validation and verification](https://atlas.scilifelab.se/validation/validation_and_verification/#verifications-in-lims), all new versions of workflows need to be verified. 

The verification includes 

-  creating the new workflow version in [the LIMS stage environment](https://clinical-lims-stage.scilifelab.se/clarity/)
-   testing it with different scenarios and adding screenshots of the tests in this issue
-  create the workflow in [the LIMS production environment](https://clinical-lims.scilifelab.se/clarity/)
-  test the workflow in production

Since many protocols are straight out copied from the previous version they won't go through extensive testing, we will just check that they perform satisfactorily with regular samples.

## Actions:

The new workflow is essentially the same as v6, and consists of 5 protocols:

**Pre Processing Microbial v1**: same protocol as in Microbial WGS v6
**Initial QC Microbial v3**: same protocol as in Microbial WGS v6
**Nextera Microbial WGS v4**: same protocol as in Microbial WGS v6
**Microbial Library Validation QC v3**: same protocol as in Microbial WGS v6
**CG002 - Normalization of microbial samples for sequencing v2**: new protocol, same as v1, but with updates in step *CG002 - Normalization of microbial samples for sequencing*
- created new Automation _Atlas Method Document and Queue samples for sequencing_
- added new automation to master step _CG002 - Normalization of microbial samples for sequencing_
- activated automation as _Automatic on exit_ in _Record details_

| Protocol | Created in Stage | Tested in Stage | Created in Production  | 
|---|---|---|---|
| Pre Processing Microbial v1 | N/A*  | 2023-05-24 ARW |  N/A | 
| Initial QC Microbial v3 | N/A*  | 2023-05-24 ARW |  N/A  | 
| Nextera Microbial WGS v4 | N/A*  | 2023-05-24 ARW |  N/A  | 
| Microbial Library Validation QC v3 | N/A*  | 2023-05-24 ARW |  N/A  | 
| CG002 - Normalization of microbial samples for sequencing v2 | 2023-05-15 ARW | 2023-05-25 ARW | 2023-06-12 ARW  | 

*This protocol is the same as in the previous version of the workflow

Testing setup:

Eight samples will be run through the entire workflow. For the first four protocols, samples will just be passed on through the steps to test that they perform the same as in the current workflow (v6). Four of the samples will go through Buffer Exchange, while four will be used to test the 'Skip buffer exchange' function in Reception Control. For protocol **CG002 - Normalization of microbial samples for sequencing v2**, the step _CG002 - Normalization of microbial samples for sequencing_ will be verified to see that the new function of queuing samples to the workflow Queue Samples for Sequencing works.

For result files for Quant-iT and Tapestation, result files from production were used. The files can be found in the respective folder in the [screen shot folder on Google Drive](https://drive.google.com/drive/folders/1VdkEjfzgB94JGGVO1qFjmeikabeTfKBM) 

All samples were from #528947. The plate was named vernex230425 in Lims.

| LIMS ID (Sample) | Sample Name  | Sequencing Analysis | Skip Buffer Exchange |
|------------------|--------------|---------------------|----------------------|
| ACC11377A1       | 23-MIK017658 | MWRNXTR003          | FALSE                |
| ACC11377A2       | 22-MIK235999 | MWRNXTR003          | FALSE                |
| ACC11377A3       | 22-PAT007694 | MWRNXTR003          | FALSE                |
| ACC11377A4       | 22-VLT000565 | MWRNXTR003          | FALSE                |
| ACC11377A5       | 22-VLT001651 | MWRNXTR003          | TRUE                 |
| ACC11377A6       | 22-VLT002322 | MWRNXTR003          | TRUE                 |
| ACC11377A7       | 22-VLT002625 | MWRNXTR003          | TRUE                 |
| ACC11377A8       | 22-VLT003071 | MWRNXTR003          | TRUE                 |

| Protocol | Step | Test specification | Comments/Results  | P/F  | Sign | 
|---|---|---|---|---|---| 
| Pre Processing Microbial v1 | Reception Control no placement v1 | N/A** | All 8 samples passed without errors. All EPPs functional. 4 samples were queued to Buffer Ecxhange v1, and four were ticked with 'Skip Buffer Exchange'. All samples were queued the samples to the correct protocol  |  P  | 2023-05-24 ARW
| Pre Processing Microbial v1 | Buffer Exchange v1 | N/A** | All 4 samples passed without errors. All EPPs functional. Updated the step so that it refers to Atlas method instead of AM  |  P | 2023-05-24 ARW
| Initial QC Microbial v3 | CG002 - Quantit QC (DNA) | N/A** | All 8 samples passed without errors. All EPPs functional. Used old Quant-it result file (nex230208)  |  P | 2023-05-24 ARW | 
| Initial QC Microbial v3 | CG002 - Aggregate QC (DNA) |  N/A**| All 8 samples passed without errors. All EPPs functional.  |   P | 2023-05-24 ARW 
| Nextera Microbial WGS v4 | CG002 - Normalization of microbial samples | N/A** | All 8 samples passed without errors. All EPPs functional (Hamilton EPP got error message because barcode UDF was not set in Reception control.  |  P | 2023-05-24 ARW | 
| Nextera Microbial WGS v4 | CG002 - Microbial Library Prep (Nextera) | N/A** |  All 8 samples passed without errors. All EPPs functional  | P | 2023-05-24 ARW | 
| Nextera Microbial WGS v4 | Post-PCR bead purification v1 | N/A** | All 8 samples passed without errors. All EPPs functional  | P | 2023-05-24 ARW | 
| Microbial Library Validation QC v3 | CG002 - Tapestation Microbial QC | N/A** | All 8 samples passed without errors. All EPPs functional. Get size (bp) from file gave error message because the file contained more than 8 samples, but the script managed to extract sample sizes and was considered functional  | P  | 2023-05-24 ARW | 
| Microbial Library Validation QC v3 | CG002 - Quantit QC (Library Validation) | N/A** |  All 8 samples passed without errors. All EPPs functional. Used old Quant-it result file (nex230208) |  P | 2023-05-24 ARW | 
| Microbial Library Validation QC v3 | CG002 - Aggregate QC (Library Validation) | N/A** |  All 8 samples passed without errors. All EPPs functional. | P | 2023-05-24 ARW | 
| CG002 - Normalization of microbial samples for sequencing v2 | CG002 - Normalization of microbial samples for sequencing | Test all 8 samples. Check that there are no errors with EPPs. Check that samples are queued to the correct workflow | All 8 samples passed without errors. All EPPs functional, although Hamilton EPP got error message because source barcode UDF was not set in previous step, but the generated file was ok despite the missing source barcode, and the EPP is thus functional. All samples were successfully queued to _Queue samples for sequencing_ step | P  | 2023-05-25 ARW | 

**The step is the same as in the previous version of the workflow and will not be tested specifically with different scenarios

#### **Project resources:**

Screen shots of all steps can be found on [Google Drive](https://drive.google.com/drive/folders/1VdkEjfzgB94JGGVO1qFjmeikabeTfKBM) 

## **Conclusions:**

The workflow Microbial WGS v7 has passed the verification and is ready to be activated and used in production.

## **Sign off**

| Head of Unit Lab | Date |
|----------------- |------|
|      ALY                        |    2023-08-25      |

## **Implementation**

| What is needed to implement changes |  Item        |  Date signature    |
|--------------------------------------- |---------- |--------------------|
|  *Information to staff*             |    1. Email sent out to email adress clinical_production@scilifelab.se  <br> 2. Inform during lab meeting <br> 3. Inform lab staff on Slack when workflow is activated   |  1. 2023-08-23 IL  <br>  2. 2023-08-28 ARW + IL  <br> 3. 230829/ARW+IL  |
|  *Documentation*                    |   Atlas document _Atlas documentation Manual cost-efficient library preparation for microbial WGS_ does not contain any protocol version numbers and does not need to be updated     |     N/A               |
|  *Test in production*           |   Monitor workflow performance during the first week after activation    |  2023-09-05 IL               |
|  *Move control samples*                            |    Move all controls to new workflow after activation in prod        |    2023-08-30 ARW + IL                |
|  *Move ongoing samples*                            |   Move all ongoing samples to new workflow after activation in prod       |      2023-08-30 ARW + IL              |
|  Archive old workflow version and hide from lab view  |  Archive workflow *Microbial WGS v6* | KSV |

- [x] Verification completed and implemented

**Comment by amandaraud** [comment]
Created in production (as pending), ready to be activated and tested.

**Comment by amandaraud** [comment]
Ready to be signed off! @annaengstrom
