### ISSUE TITLE
Verification of new workflow version: Development Projects v4

### ISSUE THREAD

**Issue by idalindegaard** [Clinical-Genomics/cg_lims#373]
Lims Issue
---------------

For definitions of headings below see [Basic Concepts](https://atlas.scilifelab.se/infrastructure/lims/basic_concepts/).

**Work Flow:** Development Projects v4
**Protocol:** Initial QC (Dev) v3, Library Prep (Dev) v3, Library validation QC (Dev) v4
**Step:** 

## Description:
With the new workflow setup where we have two separate sequencing workflows (NovaSeq 6000 and NovaSeq X), we need to create new versions of all workflows that end with sequencing. We will remove protocols NovaSeq v3 and Delivery v1, and include a new automation to queue the samples to an intermediate workflow, Queue samples for sequencing. Following documents [New workflow in LIMS](https://atlas.scilifelab.se/infrastructure/lims/development/new_workflow/) and [Validation and verification](https://atlas.scilifelab.se/validation/validation_and_verification/#verifications-in-lims), all new versions of workflows need to be verified. 

The verification includes 

-  creating the new workflow version in [the LIMS stage environment](https://clinical-lims-stage.scilifelab.se/clarity/)
-   testing it with different scenarios and adding screenshots of the tests in this issue
-  create the workflow in [the LIMS production environment](https://clinical-lims.scilifelab.se/clarity/)
-  test the workflow in Lims prod

Since many protocols are straight out copied from the previous version they won't go through extensive testing, we will just check that they perform satisfactorily with regular samples.

## Actions:

| Protocol | Created in Stage | Tested in Stage | Created in Production  | 
|---|---|---|---|
| Initial QC (Dev) v3 | N/A* | 2023-05-24 ARW | N/A  |
| Library Prep (Dev) v3 | N/A* | 2023-05-25 ARW |  N/A |
| Library validation QC (Dev) v4 | Done! 2023-05-25 ARW | 2023-05-26 ARW |  2023-06-12 ARW | 

*This protocol is the same as in the previous version of the workflow

**Testing setup:**

Eight samples will be run through the entire workflow. Because this workflow is used for development projects, the protocols are quite basic in order to accommodate many different needs. For protocols **Initial QC (Dev) v3** and **Library Prep (Dev) v3**, the samples will just be passed on through the steps to test that they perform the same as in the current workflow (v3). For protocol **Library validation QC (Dev) v4**, only the last step has been altered as compared to v3. This step will be verified to see that the new function of queueing samples to the workflow Queue Samples for Sequencing works.

The plate was named verDP230525

For result files for Quant-iT, Tapestation and qPCR, result files from production or earlier tests were used. The files can be found in the respective folder in the [screen shot folder on Google Drive](https://drive.google.com/drive/folders/1HYjryHkvKEAGWbTxbppYHIFKqdG37hT4) 

All samples were from #706451

| LIMS ID     | Sample Name | Sequencing Analysis |
|-------------|-------------|---------------------|
| ACC10455A1  | NA12878-1   | WGSPCFR400          |
| ACC10455A2  | NA12878-2   | WGSPCFR400          |
| ACC10455A3  | NA12878-3   | WGSPCFR010          |
| ACC10455A4  | NA12878-4   | WGSPCFR400          |
| ACC10455A9  | NA24143-5   | WGSPCFR400          |
| ACC10455A10 | NA24143-6   | WGSPCFR400          |
| ACC10455A11 | NA24143-7   | WGSPCFR010          |
| ACC10455A12 | NA24143-8   | WGSPCFR400          |

| Protocol | Step | Test specification | Comments/Results  | P/F  | Sign | 
|---|---|---|---|---|---| 
| Initial QC (Dev) v3 | Reception Control (Dev) v3 | N/A** |  All 8 samples passed without error. All EPPs functional. |  P | 2023-05-25 ARW
| Initial QC (Dev) v3 | Tapestation Reception Control (Dev) v3 | N/A** | All 8 samples passed without error.  Used old RC TGA Tapestation results, EPP successfully extracted sizes (bp) from the .csv file, but gave an error because the number of samples in the .csv file did not match the number of samples in the step. This is an accurate warning, and the EPP is considered functional.  | P  | 2023-05-25 ARW
| Initial QC (Dev) v3 | Qubit QC (DNA) (Dev) v3 | N/A** | All 8 samples passed without error. All EPPs functional. Manually added concentration 10 ng/ul and volume 50 ul  | P  | 2023-05-25 ARW
| Initial QC (Dev) v3 | Quantit QC (DNA) (Dev) v1 | N/A** | All 8 samples passed without error. Used old WGS dev test result file, EPP successfully extracted concentrations from the .xlsx file  | P  | 2023-05-25 ARW
| Initial QC (Dev) v3 | Aggregate QC (DNA) (Dev) v3 | N/A** | All 8 samples passed without error. All EPPs functional.  |  P | 2023-05-25 ARW
| Library Prep (Dev) v3 | Indexing (Dev) v2 | N/A** | All 8 samples passed without error. 4 samples were queued for Pooling and 4 for the prep.  |  P | 2023-05-25 ARW
| Library Prep (Dev) v3 | Pooling (Dev) v2 | N/A** | All 4 samples successfully pooled.  | P | 2023-05-25 ARW
| Library Prep (Dev) v3 | Library Prep (Dev) v3 | N/A** |  All 4 samples and the pool passed without error | P | 2023-05-25 ARW
| Library validation QC (Dev) v4 | Tapestation QC (Dev) v2 | N/A** | All 4 samples and the pool passed without error. Used old TGA development Tapestation results, EPP successfully extracted sizes (bp) from the .csv file, but gave an error because the number of samples in the .csv file did not match the number of samples in the step. This is an accurate warning, and the EPP is considered functional. | P | 2023-05-25 ARW
| Library validation QC (Dev) v4 | qPCR QC (Library Validation) (Dev) v3 | N/A** | All 4 samples passed without error. Used old WGS development result file. EPP was not able to retrieve results for the pool, but this function is not needed in the lab and the step is considered functional |  P | 2023-05-25 ARW
| Library validation QC (Dev) v4 | Qubit QC (Library Validation) (Dev) v2 | N/A** | All 4 samples and the pool passed without error. Manually added concentration 10 ng/ul  |  P | 2023-05-25 ARW
| Library validation QC (Dev) v4 | Quantit QC (DNA) (Dev) v1 | N/A** | All 4 samples and the pool passed without error. Used old WGS development result file. All EPPs functional  | P  |  2023-05-25 ARW 
| Library validation QC (Dev) v4 | Aggregate QC (Library Validation) (Dev) v3 | Check that all samples and pool are successfully aggregated and queued to the workflow Queue samples for sequencing | EPPs retrieve correct results depending on preset. All 4 samples and the pool passed without error, and were queued to the correct workflow | P  | 2023-05-26 ARW  |

**The step is the same as in the previous version of the workflow and will not be tested specifically with different scenarios

#### **Project resources:**

Screen shots of all steps can be found on [Google Drive](https://drive.google.com/drive/folders/1HYjryHkvKEAGWbTxbppYHIFKqdG37hT4) 

## **Conclusions:**

The workflow passed the verification and is ready to be used in Lims prod.

## **Sign off**

| Head of Unit Lab | Date |
|----------------- |------|
|               ALY         |   2023-08-25       |

## **Implementation**

| What is needed to implement changes |  Item        |  Date signature    |
|--------------------------------------- |---------- |--------------------|
|  *Information to staff*             |    1. Email sent out to email adress clinical_production@scilifelab.se  <br> 2. Inform during lab meeting <br> 3. Inform lab staff on Slack when workflow is activated   |  1. 2023-08-23 IL  <br>  2. 2023-08-28 ARW + IL  <br> 3. 230829/ARW+IL |
|  *Documentation*                    |    No Atlas updates needed, no mention of protocol version in the _LIMS Development workflow_       |         N/A           |
|  *Test in Lims prod*           |   Monitor workflow performance during the first week after activation    |     2023-09-05 ARW + CDM            |
|  *Move negative controls*                            |   N/A   |           N/A         |
|  *Move ongoing samples*                            |    Move all ongoing samples to new workflow after activation in prod       |       2023-08-30 ARW + IL             |
|  Archive old workflow version and hide from lab view  |  Archive workflow *Development Projects v3*  | KSV |

- [x] Verification completed and implemented

**Comment by amandaraud** [comment]
The workflow has been tested and works well in stage. Ready to be created in production.

**Comment by amandaraud** [comment]
Workflow created in production, ready to be activated and tested.

**Comment by amandaraud** [comment]
@annaengstrom ready to be signed off!
