### ISSUE TITLE
Verification of new workflow version: RML v8

### ISSUE THREAD

**Issue by idalindegaard** [Clinical-Genomics/cg_lims#374]
Lims Issue
---------------

For definitions of headings below see [Basic Concepts](https://atlas.scilifelab.se/infrastructure/lims/basic_concepts/).

**Work Flow:** RML v8
**Protocol:** CG002 Reception Control, CG002 RML Pool samples, CG002 RML Initial QC v3
**Step:** 

## Description:
With the new workflow setup where we have two separate sequencing workflows (NovaSeq 6000 and NovaSeq X), we need to create new versions of all workflows that end with sequencing. We will remove protocols NovaSeq v3 and Delivery v1, and include a new automation to queue the samples to an intermediate workflow, Queue samples for sequencing. Following documents [New workflow in LIMS](https://atlas.scilifelab.se/infrastructure/lims/development/new_workflow/) and [Validation and verification](https://atlas.scilifelab.se/validation/validation_and_verification/#verifications-in-lims), all new versions of workflows need to be verified. 

The verification includes 

-  creating the new workflow version in [the LIMS stage environment](https://clinical-lims-stage.scilifelab.se/clarity/)
-   testing it with different scenarios and adding screenshots of the tests in this issue
-  create the workflow in [the LIMS production environment](https://clinical-lims.scilifelab.se/clarity/)
-  test the workflow in production

Since many protocols are straight out copied from the previous version they won't go through extensive testing, we will just check that they perform satisfactorily with regular samples.

## Actions:

The new workflow is essentially the same as v6, and consists of three protocols:

**CG002 Reception Control**: same protocol as in RML v6
**CG002 RML Pool samples**: same protocol as in RML v6
**CG002 RML Initial QC v3**: new protocol, same as in v1, except:
- removed _CG002 - qPCR QC (Library Validation)_
- updated _Aggregate QC (DNA)_
  - created new Automation _Queue samples for sequencing (from QC step)_
  - added new automation to master step Aggregate QC (DNA)
  - activated automation as _Automatic upon exit_ in _Record details_

| Protocol | Created in Stage | Tested in Stage | Created in Production  |
|---|---|---|---|
| CG002 Reception Control | N/A* | Done! 2023-05-23 ARW | N/A  |
| CG002 RML Pool samples | N/A* | Done! 2023-05-23 ARW | N/A |
| CG002 RML Initial QC v3 | Done! 2023-05-17 ARW  | Done! 2023-05-23 ARW | 2023-06-12 ARW  |

*This protocol is the same as in the previous version of the workflow

**Testing setup:**

Eight samples will be run through the entire workflow. For protocols **CG002 Reception Control** and **CG002 RML Pool samples**, the samples will just be passed on through the steps to test that they perform the same as in the current workflow (v6). For protocol **CG002 RML Initial QC v3**, only the last step has been altered as compared to v1. This step will be verified to see that the new function of queueing samples to the workflow Queue Samples for Sequencing works.

The plate was named verrml230523

All samples were from #327440

| LIMS ID (Sample) | Sample Name                                            | Apptag     |
|------------------|--------------------------------------------------------|------------|
| ACC11446A1       | PB-P-OLVA4006-CFDNA-Ctrl1-KH20230213-C420230214        | RMLP15R100 |
| ACC11446A2       | PB-P-OLVA4006-CFDNA-Ctrl2-KH20230213-C420230214        | RMLP15R100 |
| ACC11446A3       | PB-P-OLVA4006-CFDNA-Ctrl3-KH20230213-C420230214        | RMLP15R100 |
| ACC11446A4       | PB-P-OLVA4006-CFDNA-Wash1-KH20230213-C420230214        | RMLP15R100 |
| ACC11446A5       | PB-P-OLVA4006-CFDNA-Wash2-KH20230213-C420230214        | RMLP15R100 |
| ACC11446A7       | PB-P-OLVA4006-CFDNA-evaporation1-KH20230213-C420230214 | RMLP15R100 |
| ACC11446A8       | PB-P-OLVA4006-CFDNA-Evaporation2-KH20230213-C420230214 | RMLP15R100 |
| ACC11446A9       | PB-P-OLVA4006-CFDNA-Evaporation3-KH20230213-C420230214 | RMLP15R100 |

| Protocol | Step | Test specification | Comments/Results  | P/F  | Sign | 
|---|---|---|---|---|---| 
| CG002 Reception Control | CG002 - Reception Control | NA** |  All 8 samples passed without error messages. All EPPs functional |  P | 2023-05-23 ARW
| CG002 RML Pool samples | CG002 - RML Library Pooling | NA** | All 8 samples passed without error messages. All EPPs functional  |   P | 2023-05-23 ARW
| CG002 RML Initial QC v3 | CG002 - Qubit QC RML | NA** |  All 8 samples passed without error messages. All EPPs functional. Used Qubit values from original run on 230216 (320 bp, 1,78 ng/ul)|   P | 2023-05-23 ARW
| CG002 RML Initial QC v3 | CG002 - Aggregate QC (DNA) | Test using 8 samples in one pool. Check that there are no errors with EPPs. Check that samples are queued to the correct workflow | All 8 samples passed without error messages. All EPPs functional. The pool was successfully aggregated and queued to the correct workflow |  P | 2023-05-23 ARW  |

**The step is the same as in the previous version of the workflow and will not be tested specifically with different scenarios

#### **Project resources:**

Screen shots of all steps can be found on [Google Drive](https://drive.google.com/drive/folders/1i88xKaQ8G7FuACr1XQ8p14BVgeZFYZVf)

## **Conclusions:**

The workflow passed the verification and is ready to be used in production.

## **Sign off**

| Head of Unit Lab | Date |
|----------------- |------|
|               ALY        |      2023-08-25    |

## **Implementation**

| What is needed to implement changes |  Item        |  Date signature    |
|--------------------------------------- |---------- |--------------------|
|  *Information to staff*             |    1. Email sent out to email adress clinical_production@scilifelab.se  <br> 2. Inform during lab meeting <br> 3. Inform lab staff on Slack when workflow is activated   |  1. 2023-08-23 IL  <br>  2. 2023-08-28 ARW + IL  <br> 3. 230829/ARW+IL  |
|  *Documentation*                    |    No Atlas updates needed, no mention of protocol version in _NovaSeq 6000 Sequencing method_     |      N/A              |
|  *Test in production*          |   Monitor workflow performance during the first week after activation    |    2023-09-05 ARW+IL             |
|  *Move negative controls*                            |    N/A       |      N/A              |
|  *Move ongoing samples*                            |    N/A   (workflow update was performed between two NIPT runs)    |      N/A              |
|  Archive old workflow version and hide from lab view  |  Archive workflow _RML v7_ | KSV |

- [x] Verification completed and implemented

**Comment by amandaraud** [comment]
Testing in stage done! Ready to be created in production.

**Comment by amandaraud** [comment]
Workflow created in production (pending), ready to be activated and tested.

**Comment by amandaraud** [comment]
Ready to be signed off @annaengstrom
