### ISSUE TITLE
Verification of new workflow version: RNA v4

### ISSUE THREAD

**Issue by idalindegaard** [Clinical-Genomics/cg_lims#375]
Lims Issue
---------------

For definitions of headings below see [Basic Concepts](https://atlas.scilifelab.se/infrastructure/lims/basic_concepts/).

**Work Flow:** RNA v4
**Protocol:** Initial QC (RNA) v2, Library Prep (RNA), Library Validation QC (RNA), Normalization of RNA samples for sequencing, Library Validation QC RNA (post norm) v2
**Step:** 

## Description:

With the new workflow setup where we have two separate sequencing workflows (NovaSeq 6000 and NovaSeq X), we need to create new versions of all workflows that end with sequencing. We will remove protocols NovaSeq v3 and Delivery v1, and include a new automation to queue the samples to an intermediate workflow, Queue samples for sequencing. Following documents [New workflow in LIMS](https://atlas.scilifelab.se/infrastructure/lims/development/new_workflow/) and [Validation and verification](https://atlas.scilifelab.se/validation/validation_and_verification/#verifications-in-lims), all new versions of workflows need to be verified. 

The verification includes 

-  creating the new workflow version in [the LIMS stage environment](https://clinical-lims-stage.scilifelab.se/clarity/)
-  testing it with different scenarios and adding screenshots of the tests in this issue
-  create the workflow in [the LIMS production environment](https://clinical-lims.scilifelab.se/clarity/)
-  test the workflow in production

Since many protocols are straight out copied from the previous version they won't go through extensive testing, we will just check that they perform satisfactorily with regular samples.

During creation in stage, there was an error with RNA v4, and a new version of the workflow was created (RNA v4.1). This verification tests RNA v4.1, but when created in production it will be named RNA v4 to minimize confusion, since the workflow in use today is RNA v3.

## Actions:

The new workflow is essentially the same as v3, and consists of three protocols:

**Initial QC (RNA) v2**: same protocol as in RNA v3
**Library Prep (RNA)**: same protocol as in RNA v3
**Library Validation QC (RNA)**: same protocol as in RNA v3
**Normalization of RNA samples for sequencing**: same protocol as in RNA v3
**Library Validation QC RNA (post norm) v2**: new protocol, same as v1, but with updated _Aggregate QC (Library Validation) (RNA)_
- created new Automation _Arnold upload RNA and Queue samples for seq_
- added new automation to master step _Aggregate QC (Library Validation) (RNA) v2_
- activated automation as _Automatic on exit_ in _Record details_

| Protocol | Created in Stage | Tested in Stage | Created in Production  | 
|---|---|---|---|
| Initial QC (RNA) v2 | N/A* | 2023-05-31 IL |  N/A | 
| Library Prep (RNA) | N/A* | 2023-05-31 IL |  N/A |  
| Library Validation QC (RNA) | N/A* | 2023-05-31 IL | N/A  | 
| Normalization of RNA samples for sequencing | N/A* | 2023-05-31 IL | N/A  | 
| Library Validation QC RNA (post norm) v2 | 2023-05-15 ARW  | 2023-05-31 IL | 2023-06-01 IL  | 

*This protocol is the same as in the previous version of the workflow

**Testing setup:**
The testing was done with 5 samples from project with ticket number 743101. The test was named "idatest230531". Since all protocols and steps (except the last step, _Aggregate QC (Library Validation) (RNA) v2_) were the same as in the previous version of the workflow, these samples will just be passed through all steps and the EPPs will be tested so they function satisfactorily. Different scenario testing is not needed. For the last step that has the modification that samples will be passed to workflow _Queue Samples for Sequencing v1_, I will just make sure that this has worked correctly.

| Protocol | Step | Test specification | Comments/Results  | P/F  | Sign | 
|---|---|---|---|---|---| 
| Initial QC (RNA) v2 | Reception Control (RNA) v1 | N/A** | Samples passed, all UDFs are in place and all EPPs worked | P  | 2023-05-31 IL
| Initial QC (RNA) v2 | Qubit QC (RNA) v1 | N/A** | Samples passed, all UDFs are in place and all EPPs worked | P  | 2023-05-31 IL
| Initial QC (RNA) v2 | Tapestation Reception Control (RNA) v1 | N/A** | Samples passed, all UDFs are in place and all EPPs worked  | P  | 2023-05-31 IL
| Initial QC (RNA) v2 | Aggregate QC (RNA) v1 | N/A** | Samples passed, all UDFs are in place and all EPPs worked  | P | 2023-05-31 IL
| Library Prep (RNA) | Aliquot Samples for Fragmentation (RNA) v1 | N/A** | Samples passed, all UDFs are in place and all EPPs worked  | P  | 2023-05-31 IL
| Library Prep (RNA) | A-tailing and Adapter ligation (RNA) v1 | N/A** | Samples passed, all UDFs are in place and all EPPs worked  | P  | 2023-05-31 IL
| Library Validation QC (RNA) | Tapestation QC (RNA) v1 | N/A** | Samples passed, all UDFs are in place and all EPPs worked  | P  | 2023-05-31 IL
| Library Validation QC (RNA) | Quantit QC (Library Validation)  (RNA) v2 | N/A** | Samples passed, all UDFs are in place and all EPPs worked  | P  | 2023-05-31 IL
| Library Validation QC (RNA) | Qubit QC (Library Validation) (RNA) v1 | N/A** | Samples passed, all UDFs are in place and all EPPs worked. **NOTE!** The udfs "Amount needed (ng)" and "Sample volume (ul)" need to be made **not required** but be present in the step so that the "Atlas Method Document" EPP works. | P  | 2023-05-31 IL
| Library Validation QC (RNA) | Aggregate QC (Library Validation) (RNA) v2 | N/A** | Samples passed, all UDFs are in place and all EPPs worked  | P  | 2023-05-31 IL
| Normalization of RNA samples for sequencing | Normalization of RNA samples for sequencing v1 | N/A** | Samples passed, all UDFs are in place and all EPPs worked  | P  | 2023-05-31 IL
| Library Validation QC RNA (post norm) v2 | Tapestation QC (RNA) v1 | Samples pass through the step, EPPs work satisfactory and UDFs are in place  | Samples passed, all UDFs are in place and all EPPs worked  | P  | 2023-05-31 IL
| Library Validation QC RNA (post norm) v2 | Quantit QC (Library Validation)  (RNA) v2 | Samples pass through the step, EPPs work satisfactory and UDFs are in place  | Samples passed, all UDFs are in place and all EPPs worked  | P  | 2023-05-31 IL
| Library Validation QC RNA (post norm) v2 | Qubit QC (Library Validation) (RNA) v1 | Samples pass through the step, EPPs work satisfactory and UDFs are in place  | Samples passed, all UDFs are in place and all EPPs worked. **NOTE!** The udfs "Amount needed (ng)" and "Sample volume (ul)" need to be made **not required** but be present in the step so that the "Atlas Method Document" EPP works. | P  | 2023-05-31 IL
| Library Validation QC RNA (post norm) v2 | Aggregate QC (Library Validation) (RNA) v2 | Samples pass through the step, EPPs work satisfactory and UDFs are in place. Samples move to workflow _Queue Samples for Sequencing_ when finishing the step  | Samples passed, all UDFs are in place and all EPPs worked. Samples moved to _Queue Samples for Sequencing v1_  | P  | 2023-05-31 IL

**The step is the same as in the previous version of the workflow and will not be tested specifically with different scenarios

#### **Project resources:**

All testing documentation (screenshots) is recorded in folder  [_Clinical Genomics/Development projects/LIMS/NovaSeq X Integration/Verifications/RNA v4](https://drive.google.com/drive/folders/1lvrnln9r8SV7jYv5RsqGoDCdjd9qBgKz) on Google Drive.

## **Conclusions:**

The workflow has passed the verification tests and is ready to be used in production

## **Sign off**

| Head of Unit Lab | Date |
|----------------- |------|
|         ALY              |          |

## **Implementation**

| What is needed to implement changes |  Item        |  Date signature    |
|--------------------------------------- |---------- |--------------------|
|  *Information to staff*             |    1. Email sent out to email adress clinical_production@scilifelab.se  <br> 2. Inform during lab meeting <br> 3. Inform lab staff on Slack when workflow is activated     |  1. 2023-08-23 IL  <br>  2. 2023-08-28 ARW + IL  <br> 3. 230829/ARW+IL  |
|  *Documentation*                    |   No Atlas updates needed, no mention of protocol version in _Illumina Stranded mRNA Library Preparation_      |      N/A              |
|  *Test in production*          |   Monitor workflow performance during the first week after activation    |       2023-09-05 ARW + IL          |
|  *Move negative controls*                            |    Move all controls to new workflow after activation in prod     |         2023-08-30 ARW + IL           |
|  *Move ongoing samples*                            |    Move all ongoing samples to new workflow after activation in prod     |     2023-08-30 ARW + IL               |
|  Archive old workflow version and hide from lab view  |  Archive workflow _RNA v3_ | KSV  |

- [x] Verification completed and implemented

**Comment by amandaraud** [comment]
RNA workflow has been created in production (as Pending). Automation to queue samples to workflow Queue samples for sequencing added. Workflow is ready to be activated and tested in prod!

**Comment by amandaraud** [comment]
Verification done and ready to be signed off! @annaengstrom
