### ISSUE TITLE
Verification of new workflow version: SARS-CoV-2 v4

### ISSUE THREAD

**Issue by idalindegaard** [Clinical-Genomics/cg_lims#376]
Lims Issue
---------------

For definitions of headings below see [Basic Concepts](https://atlas.scilifelab.se/infrastructure/lims/basic_concepts/).

**Work Flow:** SARS-CoV-2 v4
**Protocol:** Initial QC (Cov) v1, Library Prep (Cov) v2, Library validation QC (Cov) v2, Normalization of pool for sequencing (Cov) v1, Library validation QC (post norm) (Cov) v1
**Step:** Here to!

## Description:
With the new workflow setup where we have two separate sequencing workflows (NovaSeq 6000 and NovaSeq X) we need to create new versions of all workflows that end with sequencing. Following documents [New workflow in LIMS](https://atlas.scilifelab.se/infrastructure/lims/development/new_workflow/) and [Validation and verification](https://atlas.scilifelab.se/validation/validation_and_verification/#verifications-in-lims) all new versions of workflows need to be verified. The verification includes creating the new workflow version in [the LIMS stage environment](https://clinical-lims-stage.scilifelab.se/clarity/), testing it with different scenarios and adding screenshots of the tests in this issue, then create the workflow in [the LIMS production environment](https://clinical-lims.scilifelab.se/clarity/) and test it once more there with test samples. Since many protocols are straight out copied from the previous version they won't go through extensive testing, we will just check that they perform satisfactorily with regular samples.

Many of the new versions of workflows are just copied, but for SARS-CoV-2 v4 we have added new protocols that we hadn't before. See issue [#158](https://github.com/Clinical-Genomics/cg_lims/issues/158). These new or updated protocols will be tested more.

## Actions:

The change from the previous version is three new/modified protocols according to issue #158
- Library validation QC (Cov) v2 (Similar to _Library validation QC (Cov) v1_ but removed the Tapestation step)
- Normalization of pool for sequencing (Cov) v1 (New step where the buffer and sample volumes are calculated and recorded in order to get the pool concentration 2 nM)
- Library validation QC (post norm) (Cov) v1 (Similar step to _Library validation QC (Cov) v1_ including the Tapestation step. In the _Aggregate QC (Library Validation) (post norm) (Cov) v1_ step the pool is queued to the workflow _Queue Samples for Sequencing_)

| Protocol | Created in Stage | Tested in Stage | Created in Production  | 
|---|---|---|---|
| Initial QC (Cov) v1 | N/A* | 2023-05-17 IL | 2023-06-01 IL  |
| Library Prep (Cov) v2 | N/A* | 2023-05-17 IL |  2023-06-01 IL | 
| Library validation QC (Cov) v2 | 2023-05-11 IL | 2023-05-29 IL |  2023-06-01 IL | 
| Normalization of pool for sequencing (Cov) v1 | 2023-05-11 IL | 2023-05-29 IL |  2023-06-01 IL | 
| Library validation QC (post norm) (Cov) v1 | 2023-05-11 IL | 2023-05-29 IL | 2023-06-01 IL  | 

*This protocol is the same as in the previous version of the workflow

### Testing setup:

Testing 81 samples in project #887101 with apptag **VWGDPTR001** and a negative control from project #604902, LIMS ID ACC10558A69. Since protocols **Initial QC (Cov) v1** and **Library Prep (Cov) v2** are the same as in the previous workflow version and samples will just pass through to see that things work as they should. For protocols **Library validation QC (Cov) v2**, **Normalization of pool for sequencing (Cov) v1** and **Library validation QC (post norm) (Cov) v1**, different scenarios of concentrations will be tried, since that is what will change and be in focus. The first test is called **_idatest230517_** that runs samples with a normal concentration for the normalization. The second is called **_idatest230529_** that will test the same samples with a low concentration (for Qubit) that shouldn't need dilution. 

| Protocol | Step | Test specification | Comments/Results  | P/F  | Sign | 
|---|---|---|---|---|---| 
| Initial QC (Cov) v1 | Reception Control (Cov) v1 | NA** | All 82 samples passed without error messages. All EPPs functional  | P  | 2023-05-17 IL
| Initial QC (Cov) v1 | Tapestation QC (Cov) v1 | NA** | All 82 samples passed without error messages. All EPPs functional  | P  | 2023-05-17 IL
| Initial QC (Cov) v1 | Qubit QC (Cov) v1 | NA** | All 82 samples passed without error messages. All EPPs functional  | P  | 2023-05-17 IL
| Initial QC (Cov) v1 | Quantit QC (Cov) v1 | NA** | All 82 samples passed without error messages. All EPPs functional  | P  | 2023-05-17 IL
| Initial QC (Cov) v1 | Aggregate QC (DNA) (Cov) v1 | NA** | All 82 samples passed without error messages. All EPPs functional  | P  | 2023-05-17 IL
| Library Prep (Cov) v2 | Sample Placement (Cov) v1 | NA** | All 82 samples passed without error messages. All EPPs functional  | P  | 2023-05-17 IL
| Library Prep (Cov) v2 | Library Preparation (Cov) v1 | NA** | All 82 samples passed without error messages. All EPPs functional  | P  | 2023-05-17 IL
| Library Prep (Cov) v2 | Pooling and Clean-up (Cov) v1 | NA** | All 82 samples passed without error messages. All EPPs functional  | P  | 2023-05-17 IL
| Library validation QC (Cov) v2 | Quantit QC (Cov) v2 | Check that Get concentrations and Make Placement map EPPs work, the pool passes through the step and all udfs are in place  | Everything worked as it should  | P  | 2023-05-29 IL
| Library validation QC (Cov) v2 | Qubit QC (Cov) v2 | Check that the pool passes through the step and all udfs are in place and a concentration and QC flag is recorded  | Everything worked as it should  | P  | 2023-05-29 IL
| Library validation QC (Cov) v2 | Aggregate QC (Library Validation) (Cov) v2 | Check that Aggregate QC flags and Copy fields, Calculate Molar Concentration and Report Library QC to sample EPPs work, the pool passes through the step and all udfs are in place. (The size is added manually, value = 340). Make sure that both values from Qubit and Quantit are fetched with the first script. | Everything worked as it should  | P  | 2023-05-29 IL
| Normalization of pool for sequencing (Cov) v1 | Normalization of pool for sequencing (Cov) v1 | Check that Copy Concentration (nM) from Pooling and Clean-up (Cov) v1 and Calculate Normalization Volumes (see issue #379) EPPs work, the pool passes through the step and all udfs are in place. The total volume wished for needs to be filled in manually, and the normalization script will tell if it's missing. | Everything worked as it should, an error message pops up if the user has forgotten about writing the wished total volume. If the concentration to be normalized is lower than the final expected concentration, the script gives an error message and no volumes are calculated. This is OK and the user can leave these fields empty and choose not to normalize  | P  | 2023-05-29 IL
| Library validation QC (post norm) (Cov) v1 | Tapestation QC (post norm) (Cov) v1 | Check that Get Size (bp) from File and Placement map EPPs work, the pool passes through the step and all udfs are in place  | There was no old Tapestation file to use from previous covid runs so I tested with a TGA pool file, and the script could fetch the size from the right position as wished. Everything worked well.  | P  | 2023-05-29 IL
| Library validation QC (post norm) (Cov) v1 | Quantit QC (post norm) (Cov) v1 | Check that Get concentrations and Make Placement map EPPs work, the pool passes through the step and all udfs are in place  | Everything worked as it should | P  | 2023-05-29 IL
| Library validation QC (post norm) (Cov) v1 | Qubit QC (post norm) (Cov) v1 | Check that the pool passes through the step and all udfs are in place and a concentration and QC flag is recorded | Everything worked as it should  | P  | 2023-05-29 IL
| Library validation QC (post norm) (Cov) v1 | Aggregate QC (post norm) (Cov) v1 | Check that Aggregate QC flags and Copy fields, Calculate Molar Concentration and Report Library QC to sample EPPs work, the pool passes through the step and all udfs are in place. The size can be added manually, value = 340 (which we run now according to the document), or fetched with the EPP Aggregate QC flags and copy fields. Make sure that both values from Qubit and Quantit are fetched with the first script. After finishing the step, the samples should be sent to the workflow _Queue Samples for Sequencing_ | Everything worked as it should and the samples had moved to workflow _Queue Samples for Sequencing_ | P  | 2023-05-29 IL

**The step is the same as in the previous version of the workflow and will not be tested specifically with different scenarios

#### **Project resources:**

All screenshot documentation for the tests is collected on Google drive in [_Clinical Genomics/Development projects/LIMS/NovaSeq X Integration/Verifications/Sars-CoV-2 v4](https://drive.google.com/drive/folders/1NLQXZzTdarhVhGj-ycPj4-sC_VC7Jcz_).

## **Conclusions:**
 
The new workflow has passed the verification and is ready to be used in production.

## **Sign off**

| Head of Unit Lab | Date |
|----------------- |------|
|        ALY                |      2023-08-25    |

## **Implementation**

| What is needed to implement changes |  Item        |  Date signature    |
|--------------------------------------- |---------- |--------------------|
|  *Information to staff*             |    1. Email sent out to email adress clinical_production@scilifelab.se  <br> 2. Inform during lab meeting <br> 3. Inform lab staff on Slack when workflow is activated     |  1. 2023-08-23 IL  <br>  2. 2023-08-28 ARW+IL  <br> 3. 2023-08-29/ARW+IL  |
|  *Update documentation*             |    [automated covidseq](https://github.com/Clinical-Genomics/atlas/pull/1837) & [manual covidseq](https://github.com/Clinical-Genomics/atlas/pull/1838)      |  2023-08-29/IL                  |
|  *Test in production*          |   Monitor workflow performance during the first week after activation    |     @amandaraud             |
|  *Move controls*                            |    Move all controls to new workflow after activation in prod       |   2023-08-31 IL+ARW                 |
|  *Move ongoing samples*                            |   Move all ongoing samples to new workflow after activation in prod       |      2023-08-31 IL+ARW              |
|  Archive old workflow version and hide from lab view  |  Archive workflow _SARS-CoV-2 v3_ | KSV |

- [x] Verification completed and implemented

**Comment by amandaraud** [comment]
Workflow has been created in production (as Pending). Automation to queue samples to workflow Queue samples for sequencing added. Workflow is ready to be activated!

**Comment by idalindegaard** [comment]
Update: Detected that the "Missing reads for Pool (M)" udf had not been updated correctly with Reads*Number of samples in pool (seen in the queues of _**Define Run Format and Calculate Volumes (Nova Seq)**_ and _**Define Run Format and Calculate Volumes (Nova Seq X)**_), after the tests had been done. 

The error was fixed by adding the EPP "Calculate Missing Reads Pool" in the step _**Normalization of pool for sequencing (Cov) v1**_.

**Comment by amandaraud** [comment]
**Update:** Detected that the final pool is sent to Define run (...) as a tube, not a plate. Changed auto-placement/tube in the _Normalization of pool (...)_ step to non-automatic and plate. 

Also updated to remove the QC flags in this step, and also made the EPP _Copy concentration (...)_ to automatic upon entry into the step instead of a manual button in Record details, to facilitate for the workflow users.

**Comment by amandaraud** [comment]
@annaengstrom ready to be signed off!
