### ISSUE TITLE
Verification of new workflow version: TWIST v8

### ISSUE THREAD

**Issue by idalindegaard** [Clinical-Genomics/cg_lims#377]
Lims Issue
---------------

For definitions of headings below see [Basic Concepts](https://atlas.scilifelab.se/infrastructure/lims/basic_concepts/).

**Work Flow:** TWIST v8
**Protocol:** Pre Processing TWIST v3, Initial QC TWIST v3, Library Prep TWIST v2, Library Validation QC TWIST v2, Target Enrichment TWIST v4, Library Validation QC TWIST (post hyb) v3, Normalization of samples for sequencing (TWIST) v2, Library Validation QC TWIST (post norm) v2
**Step:** See Test specification table below

## Description:
With the new workflow setup where we have two separate sequencing workflows (NovaSeq 6000 and NovaSeq X) we need to create new versions of all workflows that end with sequencing. Following documents [New workflow in LIMS](https://atlas.scilifelab.se/infrastructure/lims/development/new_workflow/) and [Validation and verification](https://atlas.scilifelab.se/validation/validation_and_verification/#verifications-in-lims) all new versions of workflows need to be verified. The verification includes creating the new workflow version in [the LIMS stage environment](https://clinical-lims-stage.scilifelab.se/clarity/), testing it with different scenarios and adding screenshots of the tests in this issue, then create the workflow in [the LIMS production environment](https://clinical-lims.scilifelab.se/clarity/) and test it once more there with test samples. Since many protocols are straight out copied from the previous version they won't go through extensive testing, we will just check that they perform satisfactorily with regular samples.

All protocols are the same except _Target Enrichment TWIST v4_ that has been updated with the new step _Pool planning TWIST v1_, see issue [#92](https://github.com/Clinical-Genomics/cg_lims/issues/92) for more information and motivation behind this decision. Protocol _Normalization of samples for sequencing (TWIST) v2_ with step _Normalization of samples for sequencing (TWIST) v2_ is modified in the way that the EPP "Copy concentration from Target enrichment TWIST" is updated to "Copy concentration from Target enrichment TWIST v4" because the script fetches information from a modified protocol. Also, the EPP "Queue samples for sequencing" has been added to the last step _Aggregate QC (Library Validation) TWIST v2_ so that samples are going to the correct workflow for sequencing.

## Actions:

| Protocol | Created in Stage | Tested in Stage | Created in Production  |
|---|---|---|---|
| Pre Processing TWIST v3 | N/A* | 2023-05-22 IL  | N/A  |
| Initial QC TWIST v3 | N/A* | 2023-05-22 IL | N/A  | 
| Library Prep TWIST v2 | N/A* | 2023-05-22 IL |  N/A | 
| Library Validation QC TWIST v2 | N/A* | N/A |  N/A | 
| Target Enrichment TWIST v4 | 2023-05-11 IL | N/A | N/A  |
| Library Validation QC TWIST (post hyb) | 2023-05-23 IL | N/A |  N/A | 
| Normalization of samples for sequencing (TWIST) v2 | 2023-05-23 IL | 2023-05-23 IL |  2023-06-12 IL |
| Library Validation QC TWIST (post norm) v2 | 2023-05-23 IL | 2023-05-24 IL | 2023-06-12 IL  | 

*The protocol is the same as in the previous version of the workflow

### Testing setup:
- Projects that are run in the testing: 121192, 353315, 319258, 382993, 301252, 574697, 540912, 670413

I used the same Quantit and Tapestation files as the samples had run in production, see screenshots. Some files contained fewer or more samples than being tested, which is why some error messages occurred, but the correct values were fetched for the correct positions anyway.

I first ran a test called "idastest230522" with 38 samples and 4 pools in the end, but I had to stop and create a new version of the workflow because the three last protocols needed to be re-done and therefore a new workflow version was needed. 
I re-did the test with name "idastest230523" but saved all documentation from the first test until protocol _Library Validation QC TWIST (post hyb) v3_, as the results were the same. In the second test however, I only have three pools, and that's why the testing differs after this protocol step. I also did a last "Idastest230524" for the last three protocols and checked that the correct values and QC flags were fetched. 

| Protocol | Step | Test specification | Comments/Results  | P/F  | Sign | 
|---|---|---|---|---|---| 
| Pre Processing TWIST v3 | Reception Control no placement v2 | NA** | Samples passed through and all EPPs worked | P  | 2023-05-23 IL
| Pre Processing TWIST v3 | Sample Placement (TWIST) v1 | NA** | Samples passed through and all EPPs worked | P  | 2023-05-23 IL
| Pre Processing TWIST v3 | Buffer Exchange v2 | NA** | Samples passed through and all EPPs worked | P  | 2023-05-23 IL
| Initial QC TWIST v3 | Tapestation Reception Control TWIST v2 | NA** | Samples passed through and all EPPs worked | P  | 2023-05-23 IL
| Initial QC TWIST v3 | Qubit QC (DNA) TWIST v2 | NA** | Samples passed through and all EPPs worked  | P  | 2023-05-23 IL
| Initial QC TWIST v3 | Quantit QC (DNA) TWIST v2 | NA** | Samples passed through and all EPPs worked | P  | 2023-05-23 IL
| Initial QC TWIST v3 | Aggregate QC (DNA) TWIST v2 | NA** | Samples passed through and all EPPs worked  | P  | 2023-05-23 IL
| Library Prep TWIST v2 | Aliquot samples for enzymatic fragmentation TWIST v2 | NA** | Samples passed through and all EPPs worked)  | P  | 2023-05-23 IL
| Library Prep TWIST v2 | Enzymatic fragmentation TWIST v2 | NA** | Samples passed through and all EPPs worked  | P  | 2023-05-23 IL
| Library Prep TWIST v2 | KAPA Library Preparation TWIST v1 | NA** | Samples passed through and all EPPs worked | P  | 2023-05-23 IL
| Library Validation QC TWIST v2 | Tapestation QC TWIST v2 | NA** | Samples passed through and all EPPs worked  | P  | 2023-05-23 IL
| Library Validation QC TWIST v2 | Qubit QC (Library Validation) v2 | NA** | Samples passed through and all EPPs worked  | P  | 2023-05-23 IL
| Library Validation QC TWIST v2 | Quantit QC (Library Validation) TWIST v2 | NA** | Samples passed through and all EPPs worked  | P  | 2023-05-23 IL
| Library Validation QC TWIST v2 | Aggregate QC (Library Validation) TWIST v2 | NA** | Samples passed through and all EPPs worked  | P  | 2023-05-23 IL
| Target Enrichment TWIST v4 | Pool planning TWIST v1 | Make sure all information/udfs are present in the step and that the global udf "Suggested pool" can be filled in | Samples passed through and the udf "Suggested pool" can be filled in  | P  | 2023-05-24 IL
| Target Enrichment TWIST v4 | pool samples TWIST v4 | Check that the udf "Suggested pool" has the correct filled in information from the previous step and is in the pooling step | Samples passed through and the udf "Suggested pool" had the correct values. All EPPs worked  | P  | 2023-05-24 IL
| Target Enrichment TWIST v4 | Target enrichment TWIST v4 | NA** | Samples passed through and all EPPs worked  | P  | 2023-05-23 IL
| Library Validation QC TWIST (post hyb) | Tapestation QC TWIST v2 | Check that all EPPs work and all udfs needed are in place and the samples can pass through | Samples passed through and all EPPs worked  | P  | 2023-05-23 IL
| Library Validation QC TWIST (post hyb) | Qubit QC (Library Validation) v2 | Check that all EPPs work and all udfs needed are in place and the samples can pass through | Samples passed through and all EPPs worked  | P  | 2023-05-23 IL
| Library Validation QC TWIST (post hyb) | Quantit QC (Library Validation) TWIST v2 | Check that all EPPs work and all udfs needed are in place and the samples can pass through | Samples passed through and all EPPs worked  | P | 2023-05-23 IL
| Library Validation QC TWIST (post hyb) | Aggregate QC (Library Validation) TWIST v2 | Check that all EPPs work and all udfs needed are in place and the samples can pass through | Samples passed through and all EPPs worked  | P  | 2023-05-23 IL
| Normalization of samples for sequencing (TWIST) v2 | Normalization of samples for sequencing (TWIST) v2 | Updated EPP "Copy concentration from Target enrichment TWIST v4" that fetches concentrations from the updated protocol with the new name _Target enrichment TWIST v4_. Check that concentrations are being fetched. | Samples passed through, the script fetched the right concentrations | P  | 2023-05-23 IL
| Library Validation QC TWIST (post norm) v2 | Tapestation QC TWIST v2 | Check that all EPPs work and all udfs needed are in place and the samples can pass through | Samples passed through and all EPPs worked  | P  | 2023-05-23 IL
| Library Validation QC TWIST (post norm) v2 | Qubit QC (Library Validation) v2 | Check that all EPPs work and all udfs needed are in place and the samples can pass through | Samples passed through and all EPPs worked  | P  | 2023-05-23 IL
| Library Validation QC TWIST (post norm) v2 | Quantit QC (Library Validation) TWIST v2 | Check that all EPPs work and all udfs needed are in place and the samples can pass through | Samples passed through and all EPPs worked | P  | 2023-05-23 IL
| Library Validation QC TWIST (post norm) v2 | Aggregate QC (Library Validation) TWIST v2 | Check that all EPPs work, that the correct values are being fetched and that the samples are being sent to the correct workflow: _Queue Samples for Sequencing v1_ | Samples passed through and all EPPs worked, correct values were fetched when using the EPPs, the samples were went to the correct workflow. | P  | 2023-05-24 IL

**The step is the same as in the previous version of the workflow and will not be tested specifically with different scenarios

#### **Project resources:**

All screenshot documentation for the tests is collected on Google drive in [_Clinical Genomics/Development projects/LIMS/NovaSeq X Integration/Verifications/TWIST v8](https://drive.google.com/drive/folders/1iT5A7TCJsE-IEgVD3sg8F7dYvEARLNm5).

## **Conclusions:**

The workflow passed the verification, and is ready to be used in production

## **Sign off**

| Head of Unit Lab | Date |
|----------------- |------|
|           ALY            |   2023-08-25       |

## **Implementation**

| What is needed to implement changes |  Item        |  Date signature    |
|--------------------------------------- |---------- |--------------------|
|  *Information to staff*             |  1. Email sent out to email adress clinical_production@scilifelab.se  <br> 2. Inform during lab meeting  <br> 3. Inform lab staff on Slack when workflow is activated     |  1. 2023-08-23 IL  <br>  2. 2023-08-28 ARW + IL  <br> 3. 2023-08-29/ARW+IL |
|  *Documentation*                    |   [Updated manual KAPA document](https://github.com/Clinical-Genomics/atlas/pull/1852)   | 2023-08-29/IL                |
|  *Test in production*          |   Monitor workflow performance during the first week after activation    |    2023-09-05 IL+ARW             |
|  *Move controls*                            |    Move all controls to new workflow after activation in prod       |   2023-08-31 IL+ARW                 |
|  *Move ongoing samples*                            |   Move all ongoing samples to new workflow after activation in prod       |      2023-08-31 IL+ARW              |
|  Archive old workflow version and hide from lab view  |  Archive workflow _TWIST v7_ | KSV |

- [x] Verification completed and implemented

**Comment by amandaraud** [comment]
Workflow has been created in production (as Pending). Automation to queue samples to workflow Queue samples for sequencing added. Workflow is ready to be activated!

**Comment by amandaraud** [comment]
@annaengstrom ready to be signed off!
