### ISSUE TITLE
New script needed to calculate normalization volumes for covid pools (WF: SARS-CoV-2 v4)

### ISSUE THREAD

**Issue by idalindegaard** [Clinical-Genomics/cg_lims#379]
Lims Issue
---------------

For definitions of headings below see [Basic Concepts](https://atlas.scilifelab.se/infrastructure/lims/basic_concepts/).

**Work Flow:** SARS-CoV-2 v4
**Protocol:** Normalization of pool for sequencing (Cov) v1
**Step:** Normalization of pool for sequencing (Cov) v1

**Description:** 
The SARS-CoV-2 v3 workflow in LIMS is in need of an update so we register information in an easily traceable way, as suggested in issue #158, where a new normalization protocol and a "post norm" validation QC protocol would be new additions. 

Before, all calculations for diluting the covid pool have been made in the normalization sheet [1470-7_Dilution_Normalization_calculation_for_Bravo (2).xlsx](https://github.com/Clinical-Genomics/cg_lims/files/11499589/1470-7_Dilution_Normalization_calculation_for_Bravo.2.xlsx), see tab **Twist Nextera SARS-CoV-2**. 

In the new normalization protocol/step...
- We want to use the udf **"Concentration (nM)"** as input concentration
- **"Final Concentration (nM)"** that can be stated in the process udf in LIMS by the user as concentration to normalize to.
- We want the new pool to have final volume 100 ul, which can be stated in the sample udf **"Total Volume (uL)"** by the user. 
- The script would yield sample and buffer volumes in the sample udfs **"Sample Volume (ul)"** and **"Volume Buffer (ul)"**. The pool that we dilute from is around 100 ul, so there is not really a limitation for how much sample that can be used. 

See picture below for a visualization of all udfs:

<img width="813" alt="Screenshot 2023-05-17 at 16 59 19" src="https://github.com/Clinical-Genomics/cg_lims/assets/82438141/d76ef2bd-7a95-42ea-a8db-c332f4358117">

This change would also be part of the verification of the new SARS-CoV-2 v4 workflow, documented in issue #376.

**Comment by Karl-Svard** [comment]
Done in PR https://github.com/Clinical-Genomics/cg_lims/pull/381 

Also set up new automation for it, _Calculate Normalization Volumes_, and activated in the **Normalization of pool for sequencing (Cov) v1** step on stage.
