### ISSUE TITLE
WGS qPCR Place Samples in Columns

### ISSUE THREAD

**Issue by ceciliamattssonscilifelab** [Clinical-Genomics/cg_lims#383]
Lims Issue
---------------

**Work Flow:** /[Library validation QC wgs v3](https://clinical-lims.scilifelab.se/clarity/)/CG002 - qPCR QC (Library Validation)
**Protocol:** [qPCR procedure for NGS using Bravo](https://atlas.scilifelab.se/production/lab/supporting_procedures/qPCR_bravo/)
**Step:** Place Samples

**Description:** 
When placing samples for qPCR we always add them in the order of columns. Right now the pre-set in LIMS is _Row_ and it needs to be changed to _Column_ every time. Would be nice if this is pre-set already is _Column_ in **Fill container by: Column**

![image](https://github.com/Clinical-Genomics/cg_lims/assets/101624384/2d5f6dc5-7bae-496d-97f6-4c734c3e9899)

https://clinical-lims.scilifelab.se/clarity/work-placement/429821

**Comment by amandaraud** [comment]
Thanks, Cissi! Tested in stage, then fixed in production (Master step CG002 - qPCR QC (Library Validation)). Closing issue.
