### ISSUE TITLE
Initial testing Queue Samples for Sequencing v1 workflow

### ISSUE THREAD

**Issue by amandaraud** [Clinical-Genomics/cg_lims#389]
Lims Issue
---------------

For definitions of headings below see [Basic Concepts](https://atlas.scilifelab.se/infrastructure/lims/basic_concepts/).

**Work Flow:** Queue Samples for Sequencing v1
**Protocol:** Queue Samples for Sequencing v1
**Step:** 

**Description:**
As part of the validation process of the new NovaSeq X implementation, initial tests are needed prior to validating the new workflow(s). This issue will track the initial tests of workflow Queue samples for sequencing.

The initial tests include:
-  creating the new workflow version in [the LIMS stage environment](https://clinical-lims-stage.scilifelab.se/clarity/)
-   testing it with different scenarios and adding screenshots of the tests in this issue

## Actions: Testing setup

The new workflow consists of one protocol with one step. The workflow were tested using 9 samples. 4 of these were queued for NovaSeq X workflow and 4 for 6000. The samples were a mix of different apptags from the 8 different prep workflows, and consisted both of pools and single samples. 

Screenshots from the initial test can be found on [Google Drive](https://drive.google.com/drive/folders/1zqhfJ-K9uOuE1Q1ff6BJPy7yW1TWf7C-).

The plate was namned test230619qsfs.

| Sample Name                                     | LIMS ID (Submitted Sample) | Sequencing Analysis    | Prep workflow        | Sequencing workflow | Project Name   |
|-------------------------------------------------|----------------------------|------------------------|----------------------|---------------------|----------------|
| Pool # 1                                         | Pool (4 samples)           | PANKTTR010             | TGA                  | NovaSeq 6000        | 121192         |
| vernipt230517                                   | Pool (8 samples)           | RMLP05R800             | NIPT                 | NovaSeq 6000        | 983783         |
| 2022-20190-03                                   | ACC10937A5                 | RNLPOAR100             | RNA                  | NovaSeq 6000        | 743101         |
| 023701400006                                    |                            | WGSPCFC030             | WGS                  | NovaSeq 6000        | 206046         |
| NA12878-1                                       | ACC10455A1                 | WGSPCFR400             | Development Projects | NovaSeq X plus      | 706451         |
| NA24143-5 + NA24143-6 + NA24143-7 +   NA24143-8 | Pool (4 samples)           | WGSPCFR010, WGSPCFR400 | Development Projects | NovaSeq X plus      | 706451         |
| 22-VLT003071                                    | ACC11377A8                 | MWRNXTR003             | Micro                | NovaSeq X plus      | 528947         |
| verrml230523                                    | Pool (8 samples)           | RMLP15R100             | RML                  | NovaSeq X plus      | 327440         |
| vercov230530                                    | Pool (4 samples)           | VWGDPTR001             | Sars-CoV-2           | NovaSeq X plus      | 595303, 604902 |

| Protocol | Step | Created in Stage | Test specification | Comments/Results  | P/F  | Sign | 
|---|---|---|---|---|---| ---|
| Queue Samples for Sequencing v1  | Queue Samples for Sequencing | 2023-05-03 //ARW+KSV | Test that: 1. All samples are queued to the correct wf, 2. It is not possible to move forward without setting sequencing instrument, 3. There are no errors with EPPs. | All 9 samples were successfully passed through the step and queued for the correct sequencing workflow. It was not possible to move forward without setting sequencing instrument. All EPPs functional. | P | 2023-06-19 /ARW | 

## Conclusions:

Comment: 

- [ ] Initial testing completed

**Comment by idalindegaard** [comment]
**Conclusion:**
Initial testing finalized and passed the requirements set up. The workflow is now also validated and ready to be used in production. Closing this issue
