### ISSUE TITLE
Initial testing of NovaSeq X v1 workflow

### ISSUE THREAD

**Issue by idalindegaard** [Clinical-Genomics/cg_lims#390]
Lims Issue
---------------

For definitions of headings below see [Basic Concepts](https://atlas.scilifelab.se/infrastructure/lims/basic_concepts/).

**Work Flow:** NovaSeq X v1 
**Protocol:** NovaSeq X v1, Delivery v1
**Step:** TBA

**Description:** 
With the implementation of NovaSeq X in production, we will disconnect the sequencing protocols from the prep workflows and create new sequencing workflows (NovaSeq X and NovaSeq 6000). The new workflow NovaSeq X v1 contains similar protocols and steps as workflow NovaSeq 6000, but excluding the XP steps and including adjustments to be compatible with the NovaSeq X methodology. 

Following instructions in [New workflow in LIMS](https://atlas.scilifelab.se/infrastructure/lims/development/new_workflow/) and [Validation and verification](https://atlas.scilifelab.se/validation/validation_and_verification/#verifications-in-lims).

The initial testing entails making sure that all kinds of samples that we process at CG can go through the workflow in a satisfactory way and adding screenshots of the tests in this issue. The initial testing is a way of checking that no major errors are encountered for the more precise testing in the validation.

The testing will be divided into two separate tests. The first test, **Mix test**, is about making different pools out of a mixture of different apptags, that will be spread out on different lanes on an 10B flowcell. The other test, **NIPT test**, will be to test a NIPT pool that will be spread out on all eight lanes. 

**Volumes per lane (reagent volumes will be calculated with these numbers x the number of lanes chosen for the pool per flowcell):**
- 8.5 ul naOH (previously 10 ul before Illumina changed it)
- 127.5 ul preload buffer (150 ul before Illumina changed it)
- 1 ul PhiX 

**Note!** The sample sheet will be validated separately.

The documentation will be recorded on [Google Drive](https://drive.google.com/drive/folders/1UweNLFYKHewlnZHMjQDObmtq8k39uI7q).

When the initial tests have been approved, the next step will be to perform the validation. 

**Test setup, first test**

- **Mix test:** Using samples that have been tested in verification issues #370, #372, #373, #374, #375, #376, #377 to get a mixture of all kinds of samples that we process at CG. Separate some projects to make two different pools that will be distributed on all 8 lanes on a 10B flowcell. The flowcell will be named "InitialTestS4_IL".
- **NIPT test:** Using the NIPT pool that was created during verification of the new NIPT WF in issue #371. The flowcell will be named "InitialTestNIPT_IL".

**Test setup, second test**

After the first testing, see above, some problems occurred. These were discussed in the comments below, and fixed. The second test is to see that these have been resolved. It will be performed with just a few random samples, see below. 

<img width="1297" alt="Screenshot 2023-08-14 at 13 49 11" src="https://github.com/Clinical-Genomics/cg_lims/assets/82438141/4e207fa0-db32-49a7-ab8f-408dc209d3a4">

The following steps will be quick tested (230814):
- [x] **Define Run Format and Calculate Volumes (NovaSeq X):** Check that the volumes (new update from Illumina, see comments) are correct. Choose lanes to load to be less than 8 in order to test the following step. - Works
- [x] **Make Pool and Denature (NovaSeq X)**: Check that the volumes (new update from Illumina, see comments) are correct and lanes to load is not set to 8 by default - Works
- [x] **Prepare for Sequencing (NovaSeq X)**: Check that Read length is between 0 and 152 and cycles are less or equal to 20. - Works
Except for checking the above-mentioned things, all other things such as EPPs, should work satisfactorily for these specific samples.

All screenshots for the second test are documented in this [folder](https://drive.google.com/drive/folders/1Vy3kVpc7WdnYfSEA7y_cqE5unndgdXPg) on Google Drive.

**Test setup, post sequencing steps**

The testing of the post sequencing steps will be a bit different as they rely on several other sources outside of LIMS. **NovaSeq X Run** requires actual result files to be present on hasta for the linking to occur. While **Bcl Conversion & Demultiplexing (NovaSeq X)** fetches demultiplex stats from the Sample Lane sequencing metrics in statusdb. This means that past test runs on the NovaSeq X will be used.

| Protocol | Step | Test specification | Comments/Results  | P/F  | Sign | 
|---|---|---|---|---|---| 
| NovaSeq X v1 | Define Run Format and Calculate Volumes (NovaSeq X) | **NIPT & Mix test:** All relevant EPPs work and the pool can be distributed on 8 lanes for NIPT and 4 lanes for the Mix pools. Volumes per lane requirements are met (see above in the description) **Second test** Updated volumes | **NIPT test:** Worked as it should **Mix test:** Worked as it should for both pools. **Second test:** Worked well | P | First test 230710, Second test 230814 IL | 
| NovaSeq X v1 | Make Pool and Denature (NovaSeq X) | **NIPT & Mix test:** Pool can be created, the correct volumes have been calculated for the number of chosen lanes | **NIPT test:** Worked as it should **Mix test:** Unfortunately the sample and process UDFs "Lanes to load" are not the one that was chosen in the step _Define Run Format and Calculate Volumes (NovaSeq X)_, but it has been set to "8". The volumes calculated under "Step Details" are based on 8 lanes as well, which is incorrect in this case. I changed the sample udf "Lanes to load" to "4" as wanted for both pools, so that I can move forward correctly in the next step. **Second test:** Lanes to load is updated correctly | P | First test 230710, Second test 230814 IL | 
| NovaSeq X v1 | Prepare for Sequencing (NovaSeq X) | **NIPT test:** The eight derivatives can be distributed on eight lanes, all EPPs work (although the sample sheet will not be tested specifically in this test) **Mix test:** The four derivatives of each pools can be distributed on eight lanes and the EPPs work well (although the sample sheet will not be tested specifically in this test) **Second test** The Read length is between 0 and 152 and cycles are less or equal to 20  | **NIPT test:** Everything works as it should. The name "InitialTestNIPT_IL" could be chosen, maybe we will have naming requirements for the flowcells as in the NovaSeq 6000 WF? Or will you be able to name it however you want? **Mix test:** Works as it should. Named the flowcell "InitialTestS4_IL" and same goes here as for NIPT with the naming, should there be any requirements for how to name the flowcell? **Second test** Works as it should | P | First test 230710, second test 230814 IL | 
| NovaSeq X v1 | NovaSeq X Run | **Test with mixed flow cell:** A flow cell with mixed index lengths and samples placed across different lanes can enter the step by finding matching results files from hasta. These must then be able to be parsed and saved in process UDFs.  | Everything worked as expected. | P  | 230818 KSV | 
| NovaSeq X v1 | Bcl Conversion & Demultiplexing (NovaSeq X) | **Test with mixed flow cell:** Same flow cell should then be able to fetch the correct demux data from statusdb and be queued correctly to the following step. | Everything worked as expected. | P | 230818 KSV | 
| NovaSeq X v1 | Sequence Aggregation | **Test with mixed flow cell:** Samples on the same flow cell should have been correctly queued after Bcl convert. The following EPPs should then work as expected: Agg reads, rerun info, reports sequencing QC, and queue sample for rerun | Everything worked as expected. |  P | 230818 KSV | 
| Delivery v1 | Delivery | **Test with mixed flow cell:** All samples that passed Qc in the previous step shall be queued correcly, while those that didn't are instead found in Define run format. The newly arrived samples shall the be able tovget marked for delivery and have method docs assigned to them. | Everything worked as expected.  | P | 230818 KSV  |

**Comment by idalindegaard** [comment]
**Update on initial testing 230710:**
- The first step _Define Run Format and Calculate Volumes (NovaSeq X)_ passed
- The second step _Make Pool and Denature (NovaSeq X)_ passed for NIPT but not for the S4 pools. The "Lanes to Load" udf (on both sample and process level) had not been changed to 4 as was set in the previous step. It was set to 8 and all volumes had been calculated accordingly (I could manually set "4" as wanted to proceed to the next step correctly). This has to be fixed before we can start the validation.
- The third step _Prepare for Sequencing (NovaSeq X)_ looked fine, I am just wondering about if we have any naming requirements for the flowcell name, as we have for NovaSeq 6000 flowcells. Now I could type anything (which might be what we want, but I am not sure). I cannot comment on the sample sheet, but it's apparently being validated separately. I did not give this step P or F since I am not completely sure about all requirements, so I leave the judgement up to you @Karl-Svard
- I moved on with the prepared flowcell to the next step _NovaSeq X Run_ but cannot move forward to "Record Details" since there are no files for these runs. Not sure how to work with that so I will leave that to you @Karl-Svard as well...

**Comment by Karl-Svard** [comment]
The issue with the lanes to load UDF in _Make Pool and Denature (NovaSeq X)_ was caused by some inconsistent naming by me 😅

Was called "Number of Lanes to Load" in  _Define Run Format and Calculate Volumes (NovaSeq X)_ and it's accompanying EPPs. Have now changed it to "Lanes to Load" (see https://github.com/Clinical-Genomics/cg_lims/pull/406). And things work as they should again. I'll do some proper validations of this as well later

**Comment by Karl-Svard** [comment]
It was automatically set to 8 before as I wrote a fallback option in the script to always choose the full capacity of a flow cell if no other set amount was given. But maybe this could do more harm than good 🤔

**Comment by idalindegaard** [comment]
Issue #417 has been resolved and closed

**Comment by amandaraud** [comment]
Extra testing 230815 (ARW, IL, EDER): 15 WGS samples (WGSPCFC030 & WGSPCFS120)

**_Define Run Format (...)_**: All samples passed without error. All EPPs functional. Made a few minor changes:
- Updated process UDF names RSB volume and RSB lot nr to EB buffer volume (ul) and EB Buffer Lot Number (KSV updated script in this [PR](https://github.com/Clinical-Genomics/cg_lims/pull/421#event-10096173928) ) 
- Set EB Buffer Lot Number to required
- [Link to completed step](https://clinical-lims-stage.scilifelab.se/clarity/work-complete/412782)

**_Make pool and denature_**: All samples passed without error. All EPPs functional. 
- Tried to set all lot nr process UDFs as required, but the script _Set NovaSeq X UDFs (...)_ failed. The UDFs were left as not required.
- [Link to completed step](https://clinical-lims-stage.scilifelab.se/clarity/work-complete/412788)

**_Prepare for sequencing_**: All samples passed without error. All EPPs functional. 
- _Experiment name_ will be changed to _BaseSpace Run Name_ @Karl-Svard 
- Added new process UDF Library Tube Strip ID (required)
- [Link to completed step](https://clinical-lims-stage.scilifelab.se/clarity/work-details/412789)

**Comment by amandaraud** [comment]
Update: Process UDFs _Index Read 2_ and _Read 2 Cycles_ are set to required.

Discovered that sample sheet generation in step _Prepare for Sequencing_ does not work unless _Index Read 2_ is filled in. We had previously planned to keep this process UDF as not required in case we need to run single end/index sequencing. However, it was decided with KSV and AZ that it will be set as required, and that we will find a solution to sample sheet generation for single end/index samples at a later stage.

**Comment by Karl-Svard** [comment]
Updates done during initial testing:

**Bcl Conversion & Demultiplexing (NovaSeq X)**
A new EPP Queue Samples for Seq Agg (NovaSeq X) was created in order to correctly queue samples to the new Sequence Aggregation step.

**Sequence Aggregation**
A new EPP `Queue Samples for Rerun (NovaSeq X)` was created in order to sent samples to the new "Define Run Format and Calculate Volumes (NovaSeq X)". 

I also added comment fields to NovaSeq X Run and Sequence Aggregation as they didn't have it before.

**Comment by idalindegaard** [comment]
Closing this issue, since all initial testing is finalized and we moved on to document the process further in the validation report [#111](https://github.com/Clinical-Genomics/validations/pull/111) in the validations repo.
