### ISSUE TITLE
Updates to NovaSeq X workflow after new guidelines from illumina

### ISSUE THREAD

**Issue by Karl-Svard** [Clinical-Genomics/cg_lims#417]
Lims Issue
---------------

For definitions of headings below see [Basic Concepts](https://atlas.scilifelab.se/infrastructure/lims/basic_concepts/).

**Work Flow:** NovaSeq X v2
**Protocol:** NovaSeq X v2

#### Define Run Format and Calculate Volumes (NovaSeq X)
- The recommended volume/lane of a pool has decreased from 40ul to 34ul. This will be updated in the script `cg_lims/EPPs/udf/calculate/novaseq_x_volumes.py`
- The Adjusted Bulk Volume has issues in some cases where fewer lanes to load are chosen. Will need to be investigated more. I assume it has to do with some samples having an unusually large concentration.

#### Make Pool and Denature (NovaSeq X)
- The amount of NaOH per lane has decreased from 10ul to 8.5ul.
- Volume of pool per lane to denature has decreased from 40ul to 34ul (like the previous step)
- The amount of Pre Load Buffer has decreased from 150 ul to 127.5ul
- The PhiX volume might change in the future, but will for now stay at 1ul.
- Lot nrs (or all UDFs for that matter) should be set to required so one doesn't accidentally forget it and move on to the next step.

All volume changes will done in `cg_lims/EPPs/udf/set/novaseq_x_denaturation.py`

#### Prepare for Sequencing (NovaSeq X)
In the documentation they mention on several places that the library tube strip ID is needed for the planning of a sequencing run. Even though the current system should work, I feel like this ID should be stored somewhere in the lims. Flow cell IDs will still be used for naming the container in LIMS (if they havent completely replaced this with the library tube strip ID), but a new UDF should be added to this step. Then we'll see if it is required for the sample sheet as well.

**Comment by idalindegaard** [comment]
@Karl-Svard Ready to close?

**Comment by Karl-Svard** [comment]
Yes! The UDF `Library Tube Strip ID` has now been added to **Prepare for Sequencing (NovaSeq X)**.
