### ISSUE TITLE
Add warning in RC Aliquotation steps for aliquotation volumes < 1ul

### ISSUE THREAD

**Issue by FayKanellidou** [Clinical-Genomics/cg_lims#435]
Lims Issue
---------------

For definitions of headings below see [Basic Concepts](https://atlas.scilifelab.se/infrastructure/lims/basic_concepts/).

**Work Flow:** TWIST v8 and WGS PCR free v6
**Protocol:** Library Prep TWIST v2/Aliquot samples for enzymatic fragmentation TWIST , TruSeq DNA PCR-free Library Prep
**Step:** Aliquot samples for enzymatic fragmentation TWIST , Aliquot Samples for Covaris

**Description:** Describe issue here!!!
During the RC we use the Normalisation & Pooling protocol on Hamilton for the aliquotation of the samples that will go in the prep. However the Norm. protocol on Hamilton has a limitation, the pipetting is not 100% precice when it pipettes less than 1ul. So when we see in lims that there is a sample that needs less than 1ul to go in the prep, we have to pipette it manually in the destination container otherwise we don´t exactly with how much material this sample will go in the prep.
 
So because this is an important detail that can be very easily missed by the lab user, it would be a could idea to have a less than 1ul warning when we generate the aliquotation volumes. A suggestion of how the warning could look like is:

"WARNING" there are X samples that have a < 1ul aliquotation volume.

But the Lims specialists can of course suggest a better one if they think.

**Comment by AbiDalby** [comment]
This is relevant for the new Watchmaker workflow.

Work Flow: WGS PCR-free Fragmentation v1
Protocol: Pre Processing WGS Fragmentation v1 , Normalization of WGS samples for sequencing v1
Step: Sample Placement WGS v1 , Normalization of WGS samples for sequencing v1

**Comment by Karl-Svard** [comment]
Fix in https://github.com/Clinical-Genomics/cg_lims/pull/547
