### ISSUE TITLE
New workflow in LIMS: Saphyr 

### ISSUE THREAD

**Issue by idalindegaard** [Clinical-Genomics/cg_lims#442]
## General

The Saphyr instrument from Bionano has been installed and tested, but the production workflow has not been set up. The main planning of the project is done in issue [468](https://github.com/Clinical-Genomics/project-planning/issues/468). 

In this issue we document what needs to be done on the LIMS side when it's time.

## Validation plan

Follow document [New workflow in LIMS](https://atlas.scilifelab.se/infrastructure/lims/development/new_workflow/)
- [x] Create new workflow in LIMS stage - done as far as possible, (the new order form has not been created so the Saphyr run protocols are not complete but will do for now as we want to get the workflow into production before the new LIMS version update 16/4) 240328 / IL
- [x] Test new workflow in LIMS stage - done 240328 / IL
- [x] Perform validation, create a valdation report in the [validations repository on Github](https://github.com/Clinical-Genomics/validations/tree/main/docs/lims). See https://github.com/Clinical-Genomics/validations/pull/181
- [ ] Create and fill out an implementation plan in the [validations repository on Github](https://github.com/Clinical-Genomics/validations/tree/main/docs/_implementation_plans)
- [x] Copy the workflow to LIMS production

### Workflow 

An outline for the steps and protocols needed was made [in this document](https://docs.google.com/document/d/1LHLYqyOWmPpVIicxXnaI7HcYp71c6aYXlgfoG1AOqhg/edit)

All step configurations are documented [in this spreadsheet](https://docs.google.com/spreadsheets/d/1jkpcQqjsiHpcLhleIyHjBwobW-4EeLbG9tHTMK6v1JY/edit#gid=1764864017) which is located in [this folder on Google drive](https://drive.google.com/drive/folders/1hgQfGCX_Mt7zCtTFBbgIkzqCgXDRjMp0), along with the screenshot folders for the testing of the workflow.

**Comment by amandaraud** [comment]
LF has prepared a list of what is needed in the WF: https://docs.google.com/document/d/1LHLYqyOWmPpVIicxXnaI7HcYp71c6aYXlgfoG1AOqhg/edit

**Comment by idalindegaard** [comment]
**Initial testing of the workflow is done** 
The automations and configurations are working as they should. The final testing will be documented in the validation report.
However, the Saphyr Run protocol is limited for now, as the order form and apptag are not finalised, and there are still questionmarks on how to retrieve data etc. We will continue to do the validation regardless, so that the workflow can be put in production asap before the LIMS 6.2 update.

**Comment by Karl-Svard** [comment]
## The Saphyr workflow has now been created in production and is ready for deployment after final signatures

### New workflow: Saphyr (OGM) v1

#### Initial QC (Saphyr) v1
- Reception Control Saphyr, Reception Control Saphyr
- Qubit QC (Saphyr), Qubit QC (Saphyr)
- Aggregate QC (Saphyr), Aggregate QC (Saphyr)

#### Sample Preparation (Saphyr) v1
- Labelling & Staining (Saphyr), Labelling & Staining (Saphyr)

#### Post-prep QC (Saphyr) v1
- Qubit QC (Saphyr), Qubit QC (post-prep) (Saphyr)
- Aggregate QC (Saphyr), Aggregate QC (post-prep) (Saphyr)

#### Saphyr Run v1
- Saphyr Sample Loading and Start, Saphyr Sample Loading and Start
- Saphyr Post Mapping QC, Saphyr Post Mapping QC

#### Delivery v1
- Delivery, Delivery v1

### New EPPs created

#### Calculate Aliquotation Volume from Average concentration (ng/ul) Saphyr
```
bash -c -l "conda activate cg_lims &&  lims -c  /home/glsai/.genologics.yaml epps -l {compoundOutputFileLuid0} -p {processLuid}   udf calculate aliquot-volume --concentration-udf 'Initial Concentration (ng/ul)' --amount-ng-udf 'Amount needed (ng)' --volume-udf 'Sample Volume (ul)' --buffer-udf 'Volume H2O (ul)' --total-volume-udf 'Total Volume (ul)'"
```
- Labelling & Staining (Saphyr)

#### Copy UDFs from Initial QC (Saphyr)
```
bash -c -l "conda activate cg_lims && lims -c /home/glsai/.genologics.yaml epps -l {compoundOutputFileLuid0} -p {processLuid} udf copy artifact-to-artifact  -sau 'Average concentration (ng/ul)' -sau 'Volume (ul)' -sau 'Amount (ng)' --artifact-udfs 'Initial Concentration (ng/ul)' --artifact-udfs 'Volume (ul)' --artifact-udfs 'Initial Amount (ng)' -sa"
```
- Labelling & Staining (Saphyr)

#### Set QC Saphyr 1
```
bash -c -l "/opt/gls/clarity/bin/java -jar /opt/gls/clarity/extensions/ngs-common/v5/EPP/ngs-extensions.jar -i {stepURI:v2} -u {username} -p {password} script:evaluateDynamicExpression -t false -h false -exp 'output.QC = output.::Coefficient of variation (CV):: <= step.::Maximum CV value:: && output.::Average concentration (ng/ul):: >= step.::Minimum required concentration (ng/ul)::' -log {compoundOutputFileLuid1}"
```
- Qubit QC (Saphyr)

#### Calculate amount from average
```
bash -c -l "conda activate cg_lims &&  lims -c /home/glsai/.genologics.yaml epps -l {compoundOutputFileLuid0} -p {processLuid}  udf calculate calculate-amount-ng --concentration-udf 'Average concentration (ng/ul)' --amount-udf 'Amount (ng)' --volume-udf 'Volume (ul)' -m"
```
- Qubit QC (Saphyr)

#### Calculate Average concentration (ng/ul) and CV for Initial Saphyr
```
bash -c -l "conda activate cg_lims &&  lims -c  /home/glsai/.genologics.yaml epps -l {compoundOutputFileLuid0} -p {processLuid} udf calculate calculate-saphyr-concentration -cr 'Concentration 1 (ng/ul)' -cr 'Concentration 2 (ng/ul)' -cr 'Concentration 3 (ng/ul)'"
```
- Qubit QC (Saphyr)

#### Check Required - Aggregate QC (Saphyr)
```
bash -c -l "conda activate cg_lims &&  lims -c /home/glsai/.genologics.yaml epps -l {compoundOutputFileLuid0} -p {processLuid} udf check check-artifact-udfs  -i -au 'Average concentration (ng/ul)'"
```
- Aggregate QC (Saphyr)

#### Calculate Average concentration (ng/ul) and CV for Post-Prep Saphyr
```
bash -c -l "conda activate cg_lims &&  lims -c  /home/glsai/.genologics.yaml epps -l {compoundOutputFileLuid0} -p {processLuid} udf calculate calculate-saphyr-concentration -cr 'Concentration 1 (ng/ul)' -cr 'Concentration 2 (ng/ul)'"
```
- Qubit QC (post-prep) (Saphyr)


#### Set QC Saphyr 2
```
bash -c -l "/opt/gls/clarity/bin/java -jar /opt/gls/clarity/extensions/ngs-common/v5/EPP/ngs-extensions.jar -i {stepURI:v2} -u {username} -p {password} script:evaluateDynamicExpression -t false -h false -exp 'output.QC = output.::Coefficient of variation (CV):: <= step.::Maximum CV value:: && output.::Average concentration (ng/ul):: >= step.::Minimum required concentration (ng/ul):: && output.::Average concentration (ng/ul):: <= step.::Maximum required concentration (ng/ul)::' -log {compoundOutputFileLuid1}"
```
- Qubit QC (post-prep) (Saphyr)

### New UDFs created

#### Derived sample
- Initial Amount (ng)
- Initial Concentration (ng/ul)
- Target DNA ≥ 150kbp (Gbp)
- Collected DNA ≥ 150kbp (Gbp)
- N50 ≥ 150kbp (kbp)
- N50 ≥ 20kbp (kbp)
- Label Density per 100kbp
- Map Rate (%)
- Est Effective Coverage ≥ 150kbp (X)
- PLV (%)
- NLV (%)
- Concentration 1 (ng/ul)
- Concentration 2 (ng/ul)
- Concentration 3(ng/ul)
- Coefficient of variation (CV)
- Average concentration (ng/ul)

#### Measurement
- Concentration 1 (ng/ul)
- Concentration 2 (ng/ul)
- Concentration 3(ng/ul)
- Coefficient of variation (CV)
- Average concentration (ng/ul)

### New Container type
- Saphyr Chip

**Comment by Karl-Svard** [comment]
### Deployed to production!
