### ISSUE TITLE
Add pre-filled info into the sequencing workflows to reduce risk of errors

### ISSUE THREAD

**Issue by EmiliaRegazzoni** [Clinical-Genomics/cg_lims#446]
Lims Issue
---------------

For definitions of headings below see [Basic Concepts](https://atlas.scilifelab.se/infrastructure/lims/basic_concepts/).

**Work Flow:** NovaSeq X v 1
**Protocol:** Prepare for Sequencing (NovaSeq X)
**Step:** Read 1 Cycles, Reads 2 Cycles, Index Read 1, Index Read 2

**Description:** <img width="978" alt="image" src="https://github.com/Clinical-Genomics/cg_lims/assets/92719658/e72a256e-b9a6-4483-b6f1-d683c7bd519e">

Kan detta vara ifyllt? vi använder alltid 151-10-10-151 och att behöva skriva i det varje gång är onödigt! Dock vill vi behålla att vi kan ändra texten om vi vill (för särskilda RML pooler).

Vi skulle även vilja ha samma för NovaSeq 6000 flödet men 51-8-8-51 (@idalindegaard vet nog vad jag menar!)

**Comment by idalindegaard** [comment]
I've updated this in LIMS and changed the NovaSeq X document (see [PR](https://github.com/Clinical-Genomics/atlas/pull/2123))
