### ISSUE TITLE
Update NovaSeq X workflow for 25B and future 1.5B flow cells

### ISSUE THREAD

**Issue by amandaraud** [Clinical-Genomics/cg_lims#447]
Lims Issue
---------------

For definitions of headings below see [Basic Concepts](https://atlas.scilifelab.se/infrastructure/lims/basic_concepts/).

**Work Flow:** NovaSeq X v1
**Protocol:**  NovaSeq X 
**Step:** All steps 

**Description:**
The flow cell 25B is now available and we want to start using it in production. Lims needs to be updated.
25B has 8 lanes (like 10B), but can handle more reads (25 000 read pairs = 50 000 reads). Illumina has also provided instructions for 1.5B and we think it is best to update the workflow to prepare for 1.5B also. The sample sheet should not be affected.

*New volumes  for 25B (1.5B in parenthesis):*
min volume per lane: 56 ul (34 ul)
pix 1.6 ul (1 ul)
NaOH: 14 ul (8.5 ul)
preload buffer: 210 ul (127.5 ul)
dispense 275 ul denatured library

*What is needed:*

- [ ] New container object for the flow cells

Define run (...):
- [ ] dropdown options in process UDF "Flow cell type" with 10B, 25B and 1.5B
- [ ] include new volumes for 25B and 1.5B in script

Make Pool and Denature (NovaSeq X)
- [ ] dropdown option in process UDF "Flow cell type" with 10B, 25B and 1.5B
Note! Volumes different but since script takes volumes from previous step, this will be automatically updated 

Prepare for Sequencing (NovaSeq X)
- [ ] Run mode: automatically retrieved when step opens, should be automatically updated (test!)
- [ ] Would be neat if read length and index lengths had default values depending on the flow cell. Could potentially be done by the same script that sets Run mode.

Steps from NovaSeq X Run and forward should not be affected by the change, but should be tested still to confirm that everything works as intended.

**Comment by amandaraud** [comment]
Updated issue after meeting with EDER, IL, KSV and ARW 2023-11-09

**Comment by Karl-Svard** [comment]
## Configuration setup on stage

### General
- [ ] New containers for 25B (8 lanes) and 1.5B (2 lanes)
- [ ] Create and deploy `cg_lims` branch with new volume constants

### Define Run Format and Calculate Volumes (NovaSeq X)
- [ ] Convert the `Flow Cell Type` process UDF into a text drop-down with 10B, 25B, and 1.5B as options

### Make Pool and Denature (NovaSeq X)
- [ ] Add Library Tube Strip ID as a process UDF. Should be set as required.

### Prepare for Sequencing (NovaSeq X)
- [ ] Set up new EPP for fetching Library Tube Strip ID from the previous step, and to set default values for read and index lengths.

**Comment by Karl-Svard** [comment]
Related PR https://github.com/Clinical-Genomics/cg_lims/pull/453

**Comment by idalindegaard** [comment]
## **Testing new features (2023-11-20/21):**

### Define Run Format and Calculate Volumes (NovaSeq X)
Testing minimum volume for the pool for both 1.5B and 25B (with the available options in the drop-down menu in the process UDF view) and the correct volumes are set (see 2 pictures below):
<img width="972" alt="Screenshot 2023-11-21 at 15 39 28" src="https://github.com/Clinical-Genomics/cg_lims/assets/82438141/0e109a30-c422-4c24-b2c8-50107b93487f">
<img width="670" alt="Screenshot 2023-11-20 at 17 39 07" src="https://github.com/Clinical-Genomics/cg_lims/assets/82438141/57ce2824-d269-4520-bd23-e2b6b3b741ec">

You cannot choose more than two lanes for the 1.5B flowcell option (see picture below):
<img width="670" alt="Screenshot 2023-11-20 at 17 36 24" src="https://github.com/Clinical-Genomics/cg_lims/assets/82438141/85173c69-fc33-4603-8d03-6d3acee2a440">

### Make Pool and Denature (NovaSeq X)

The correct volumes are set for PhiX, NaOH, Pre-Load Buffer, Volume of pool to denature, total volume of pool etc for both 1.5B and 25B (see 2 pictures below):
<img width="670" alt="Screenshot 2023-11-20 at 17 40 34" src="https://github.com/Clinical-Genomics/cg_lims/assets/82438141/c8f4358a-1ec1-4fc9-9d53-9e3a06920f13">
<img width="972" alt="Screenshot 2023-11-21 at 15 44 47" src="https://github.com/Clinical-Genomics/cg_lims/assets/82438141/0158b258-f739-4b71-921c-4ad1b33e6d91">

If you forget to write the Library Tube Strip ID you will get a warning message when exiting the step (you cannot proceed without it):
<img width="664" alt="Screenshot 2023-11-21 at 11 28 33" src="https://github.com/Clinical-Genomics/cg_lims/assets/82438141/557a66ff-a5c5-4b22-bfe7-bb2fd8c57362">

### Prepare for Sequencing (NovaSeq X)

There are options for three different types of flowcells (1.5B, 10B, 25B):
<img width="972" alt="Screenshot 2023-11-21 at 15 48 44" src="https://github.com/Clinical-Genomics/cg_lims/assets/82438141/174d345a-6b2f-44af-a544-a39baba4f757">

In the following screenshots we can see that the options 1.5B vs 25B seem to work well, and the Run Mode process UDF is changed according to the chosen option. 
<img width="670" alt="Screenshot 2023-11-20 at 17 41 40" src="https://github.com/Clinical-Genomics/cg_lims/assets/82438141/229f1adb-e2ab-4443-89d3-78535227e62c">
<img width="664" alt="Screenshot 2023-11-21 at 11 35 48" src="https://github.com/Clinical-Genomics/cg_lims/assets/82438141/6cf11862-913c-4a2e-bcdd-129bf2425483">
<img width="664" alt="Screenshot 2023-11-21 at 11 36 02" src="https://github.com/Clinical-Genomics/cg_lims/assets/82438141/108658b5-54df-43db-8862-8249a7cff2ba">
<img width="664" alt="Screenshot 2023-11-21 at 11 37 09" src="https://github.com/Clinical-Genomics/cg_lims/assets/82438141/df8cba3b-e4d8-424f-aacf-52fd80122200">

<img width="972" alt="Screenshot 2023-11-21 at 15 49 23" src="https://github.com/Clinical-Genomics/cg_lims/assets/82438141/a3acd724-1b2c-42c3-8401-ad
<img width="972" alt="Screenshot 2023-11-21 at 15 51 22" src="https://github.com/Clinical-Genomics/cg_lims/assets/82438141/1dcec63e-ea6a-4782-bcad-2944eab6fb4a">
d1a33d3a1d">
<img width="972" alt="Screenshot 2023-11-21 at 15 54 02" src="https://github.com/Clinical-Genomics/cg_lims/assets/82438141/77325636-ef14-4856-a1c9-fbde502ca471">

The EPP "Set Sequencing Settings" ran successfully when entering Record Details:
<img width="1256" alt="Screenshot 2023-11-21 at 15 55 20" src="https://github.com/Clinical-Genomics/cg_lims/assets/82438141/ea3bb377-16a8-4dcc-b219-c1c0833e5031">

## Conclusion

The changes work well in the workflow and can be implemented in production LIMS

**Comment by Karl-Svard** [comment]
## Implementing in production

### General
- [x] The new `cg_lims` branch has been merged and deployed
- [ ] New containers for 25B (8 lanes) and 1.5B (2 lanes)
- [ ] Add them as new options to the global derived sample UDF `Flowcell Type`

### Define Run Format and Calculate Volumes (NovaSeq X)
- [ ] Convert the `Flow Cell Type` process UDF into a text drop-down with 10B, 25B, and 1.5B as options

### Make Pool and Denature (NovaSeq X)
- [ ] Add Library Tube Strip ID as a process UDF. Should NOT be set as required (script won't work otherwise).
- [ ] Create new automation, "Check Library Tube Strip UDF", run it when exiting Record Details

### Prepare for Sequencing (NovaSeq X)
- [ ] Add new flow cells as container options in the step
- [ ] Remove 10B as the default value for the `Run Mode` process UDF
- [ ] Create new automation, "Set Sequencing Settings", and configure it to activate when starting Record details

**Comment by Karl-Svard** [comment]
Changes deployed to production, closing
