### ISSUE TITLE
Make sequencing pooling easier

### ISSUE THREAD

**Issue by amandaraud** [Clinical-Genomics/cg_lims#449]
## Description of the issue

The planning of NovaSeq X sequencing runs is often laborious and complex - it takes time and you need to take many factors into consideration. The process is not efficient or smooth, and there are ways to automate some steps.

The planning is done outside of LIMS in separate excel spreadsheets, such as [the total calculation for a whole flowcell](https://docs.google.com/spreadsheets/d/1paWC4f68dSFXduMMpRx9OoAYBE4SRzjxXhAu9vtf6BY/edit#gid=499440287), [TGA topup calculations](https://docs.google.com/spreadsheets/d/1pKy79OGleRPVOTZrbN42oZahbNm8H8ooX305lFtDRh8/edit#gid=1256940521) and [WGS topup calculations](https://docs.google.com/spreadsheets/d/1R01lFbBhxMu3IJrLBsOT_qmUQjdT8gzKLN2faGI_Ghg/edit#gid=0). Many values have to be looked up in LIMS steps such as Sequence Aggregation

## Suggestions of improvement

- When topups are requeued, their remaining reads to sequence are not always in accord with what the samples actually need, so that could be corrected in the requeueing script that the bioinformatician uses 
- Script(s) that you can run when you have gotten the reads to sequence, to adjust them according to the method
     - TGA & RML samples: x0.65 (when running with WGS samples - i.e. not always, this should be a separate EPP)
     - Bacterial microbial samples: changed from 6 M to 3.5 M (always)
     - RNA samples: x0.4 (always)
     - WGS samples with 2400 M: adjust to 2100 M (always)

>

**Comment by idalindegaard** [comment]
Linked to [this issue](https://github.com/Clinical-Genomics/project-planning/issues/473)

**Comment by idalindegaard** [comment]
Closing as this is redundant, see issue #498
