### ISSUE TITLE
Add instrument in TGA Aliquotation step

### ISSUE THREAD

**Issue by saschaconradt** [Clinical-Genomics/cg_lims#454]
Lims Issue
---------------

For definitions of headings below see [Basic Concepts](https://atlas.scilifelab.se/infrastructure/lims/basic_concepts/).

**Work Flow:** TWIST v8
**Protocol:** Library Prep TWIST v2
**Step:** Aliquot samples for enzymatic fragmentation TWIST

**Description:**Please add a field to choose an instrument (Laura or Leslie or N/A)

**Comment by amandaraud** [comment]
Created a Master Step Field "Hamilton instrument", but did not activate on step. Waiting for updates in Arnold upload script.

**Comment by Karl-Svard** [comment]
fixed in https://github.com/Clinical-Genomics/cg_lims/pull/535
