### ISSUE TITLE
Add new PCR instrument (Star)

### ISSUE THREAD

**Issue by carolinadiettrich** [Clinical-Genomics/cg_lims#458]
Lims Issue
---------------

For definitions of headings below see [Basic Concepts](https://atlas.scilifelab.se/infrastructure/lims/basic_concepts/).

**Work Flow:** Full name here please!
**Protocol:** And here!
**Step:** Here to!

**Description:** Describe issue here!!!
Please we need to add the new PCR instrument called Star to Lims.

**Comment by idalindegaard** [comment]
Added to all relevant steps in LIMS
