### ISSUE TITLE
Change the qPCR layout for the estimation of concentrations

### ISSUE THREAD

**Issue by FayKanellidou** [Clinical-Genomics/cg_lims#460]
Lims Issue
---------------

For definitions of headings below see [Basic Concepts](https://atlas.scilifelab.se/infrastructure/lims/basic_concepts/).

**Work Flow:** WGS PCR free v6
**Protocol:** Library validation QC wgs v4
**Step:** CG002 - qPCR QC (Library Validation)

**Description:** 
We are going to change the qPCR method and the new qPCR will have a different layout than the current one. 
The new sample & Standard layout can be found [here](https://docs.google.com/spreadsheets/d/1rx9a5fP0q0S6uIY6l43tCPkDqym41FNnm5Nhz1OO5_c/edit#gid=2036230586). With the current setup the samples are placed in the 384 well plate in triplicates and in 3 different dilutions, while with the new setup the samples will be placed in triplicates again but there will be only one dilution for each sample.

The criteria for excluding the outlier Ct values of the triplicates should also be adjusted

- Since there will only be one dilution there will not be a need to to keep the limitations that indicate the values between dilutions should have a certain range.
- The triplicate Ct values for each sample should not differ more than 0.2. If there are triplicates that have a difference higher than 0.2 then lims should be allowed to remove up to 2 out of 3 Ct triplicates and base the nM estimation from the triplicate Cts that remain.

_This issue is part of the prio one project [Change qPCR setup & move it on Hamilton #519](https://github.com/Clinical-Genomics/project-planning/issues/519)_

**Comment by FayKanellidou** [comment]
Volodymyr said he will prepare the new method and add it on Hamilton next week so we would like now to make preparations for the upcoming qPCR method change as soon a possible.

**Comment by idalindegaard** [comment]
> Volodymyr said he will prepare the new method and add it on Hamilton next week so we would like now to make preparations for the upcoming qPCR method change as soon a possible.

@FayKanellidou We will look at it next week!

**Comment by amandaraud** [comment]
New well transformer python dictionary created, added to project folder, subfolder "Lims" https://drive.google.com/drive/folders/1KB9k4ZBe_CDIceACaNMIrHg5vg38oKgY
