### ISSUE TITLE
Remove a columns from the queue

### ISSUE THREAD

**Issue by EmiliaRegazzoni** [Clinical-Genomics/cg_lims#464]
Lims Issue
---------------

For definitions of headings below see [Basic Concepts](https://atlas.scilifelab.se/infrastructure/lims/basic_concepts/).

**Work Flow:** NovaSeq X sequencing
**Protocol:** Queue Samples for Sequencing v2 and NovaSeq X v1
**Step:** Queue Samples for Sequencing and Define Run Format and Calculate Volumes (NovaSeq X)

**Description:**

Could you please remove two columns from the queue so that it is easier to visualize the samples in the queue? Specifically can you remove "Workflow" and "Received at"?

From the queue for Define Run Format and Calculate Volumes (NovaSeq X) could you also remove the column "LIMS ID (container)" for the same reason?

**Comment by idalindegaard** [comment]
Hi @EmiliaRegazzoni, sure I can do it. I'm thinking about "Received at" though, it was placed there so we can prioritize samples that have been in the loop for a long time/longer than others in the same plate. I think it can be useful to have

**Comment by EmiliaRegazzoni** [comment]
Yes, I can also see the use... I was hoping that the "waiting" was enough but of course if a sample is requeued then it will be reset... Let's keep it! Thanks for the input Ida!

**Comment by idalindegaard** [comment]
@EmiliaRegazzoni Yeah, I agree there are many columns and it's a bit annoying to drag them out etc.. 
I removed the other ones - good suggestion!
