### ISSUE TITLE
Remove BaseSpace Sequence Hub Configuration from old novaseq 6000 wf

### ISSUE THREAD

**Issue by EmiliaRegazzoni** [Clinical-Genomics/cg_lims#465]
Lims Issue
---------------

For definitions of headings below see [Basic Concepts](https://atlas.scilifelab.se/infrastructure/lims/basic_concepts/).

**Work Flow:** NovaSeq v3
**Protocol:** NovaSeq v3
**Step:** STANDARD Prepare for Sequencing (Nova Seq)

**Description:** After discussion with AZ and you (lims people) we concluded that we do not need the BaseSpace config in the new X workflow. So let's also remove it from the old 6000 workflow! Do you agree?

**Comment by idalindegaard** [comment]
I agree, and it's done!
