### ISSUE TITLE
Initial testing - ONT v2 workflow

### ISSUE THREAD

**Issue by amandaraud** [Clinical-Genomics/cg_lims#468]
**Work Flow:** ONT v2

**Protocols:** Initial QC (ONT) v2, ONT Library Prep v2, Library Validation (ONT)

**Step:** _all steps in these protocols_

## **Description:**
As CG is running long read sequencing on the PrometION from Oxford Nanopore Technologies (ONT), there is a need for a Lims workflow to keep track of all samples processed with this instrument. The ONT v2 workflow has been designed to provide a basic workflow from initial QC, via prep and library QC, to sequencing and delivery. 

This issue will keep track of the initial testing of the new ONT workflow, following instructions in [New workflow in LIMS](https://atlas.scilifelab.se/infrastructure/lims/development/new_workflow/) and [Validation and verification](https://atlas.scilifelab.se/quality_assurance/validation/validation_and_verification/#validations-in-lims). The initial testing will ensure that all steps of the workflow function properly, by checking that no major errors are encountered before the more precise testing in the validation.

When the initial testing has been approved, the next step will be to perform the validation.

*Note!* The two last protocols of the ONT v2 workflow, **ONT sequencing** and **Delivery v1** are not yet included in this testing issue.

*Note!* During the validation process, it was realized that another step was needed, _DNA Size Selection (ONT)_, after the _DNA Fragmentation (ONT)_ step. This step is not included in the initial testing. Further information about this can be found in the More testing will be done in the [validation repport](https://github.com/Clinical-Genomics/validations/pull/150). 

### **Testing setup:**

| Protocol | Step | Test specification | Comments/Results  | P/F  | Sign | 
|---|---|---|---|---|---| 
| _Protocol name_  | _Step name_  | _The criteria for passing the test for this step_ | _Comments or results from testing_  | _P (Pass) or F (Fail) based on the criteria in the Test specification_  | _Date and Sign_
| Initial QC (ONT) v2 | Reception Control ONT | Date is set, QC flags can be set, no errors in EPPS | No errors, two suggestions for minor changes | P | 240118/ARW | 
| Initial QC (ONT) v2 | Qubit QC (DNA) ONT | Volumes can be fetched with "Copy Volume (ul) from Sample (to measurement)", concentrations can be recorded, amounts calculated with EPP, Atlas Method Document works and lot no, document, instrument and assay are required. QC flags need to be set | Everything works as should | P | 240119/IL | 
| Initial QC (ONT) v2 | Quantit QC (DNA) ONT | Samples can be placed in a 96 well plate. Volumes can be fetched with "Copy Volume (ul) from Sample (to measurement)", concentrations can be fetched from file and recorded, amounts calculated with EPP, placement map works, Atlas Method Document works and lot no, document, instrument and assay are required. QC flags need to be set | Everything works as should | P | 240119/IL | 
| Initial QC (ONT) v2 | Tapestation Reception Control (ONT) | Samples can be placed in a 96 well plate. DIN and Size (bp) can be fetched from files and recorded, placement map works, Atlas Method Document works and lot no, document, instrument and assay are required. QC flags need to be set | Everything works as should | P | 240119/IL | 
| Initial QC (ONT) v2 | Aggregate QC (DNA) ONT | All values that are given in the Copy task fields can be fetched from the right steps, there are two working presets for Quantit/Qubit, values can be recorded | Everything worked fine after a minor correction of the name of the Tapestation step that was incorrect in the presets (recorded in the excel sheet linked under project resources) | P | 240119/IIL | 
| ONT Library Prep v2 | ONT Pre-Prep Sort | QC values from previous protocol are visible. The next or the step after that in the protocol can be chosen | Works well | P| 240119/IL| 
| ONT Library Prep v2 | DNA Fragmentation (ONT) | Values are fetched from RC with Copy UDFs from Reception Control QC, when adding an amount needed (ng), the EPP Calculate ONT Aliquot Volumes for fragmentation generates volumes for Sample Volume (ul) and Volume H2O (ul) that together adds up to Total Volume (ul) which is 55ul, when adding the correct Tapestation CSV file (...compactRegionTable.csv), Get Size (bp) From File fetches values for Size (bp). When the user adds values to Concentration, Calculate Amount for 48 ul of the samples gives the Amount (ng). | Everything works as should | P | 240119/IL| 
| ONT Library Prep v2 | Aliquot Samples for ONT Prep | Total volume (ul) is set to 48 and is required, Copy UDFs/Volumes from Initial QC and/or Fragmentation fetch correct volumes (if the user skipped the Fragmentation step you can use the one stating "...or Fragmentation"), when the user adds a value to Amount needed (ng), Calculate ONT Aliquot Volumes will generate values to Sample Volume (ul) and Volume H2O (ul) that in total equals Total Volume (ul) | Everything works as it should | P | 240119/IL| 
| ONT Library Prep v2 | ONT End Repair |Copy volume and amount EPPs get the right values. Calculate Amount for 60 ul of the samples calculates correct amounts in ng and fmol. | The EPPs work as they should. I double-checked the amounts with the formulas Amount (ng)=Concentration (ng/ul)*Volume (ul) _(which was 60ul)_. And Amount (fmol)=(10^6)*Amount (ng)/(Size from fragmentation (bp)*615.96+36.04) - both were correct | P | 240123/IL | 
| ONT Library Prep v2 | ONT Adapter Ligation | Copy Amount EPP gets Amount (ng) and sets as Input Amount (ng) | Works as it should | P | 240123/IL| 
| Library Validation (ONT) | Qubit QC (Library Validation) ONT |Equipment document, assay, Lot no: Qubit kit and instrument are required. QC flags need to be set | Works as it should | P | 240123/IL| 
| Library Validation (ONT) | Quantit QC (Library Validation) ONT | Samples can be placed in a 96 well plate. Document, assay, instrument and lot number udfs are required. EPPs work as they should. | Minor correction, had to add a placement step and make process udfs required. Everything works as it should after some corrections | P | 240123/IL| 
| Library Validation (ONT) | Aggregate QC (Library Validation) ONT | Copy task 1 - source step works for both Quantit and Qubit when pressing "1. Aggregate QC Flags...". The "Calculate Amount for 24 ul of the samples" EPP calculates correct amounts (ng and fmol) | Everything worked fine. I double-checked the amounts with the formulas Amount (ng)=Concentration (ng/ul)*Volume (ul) _(which was 24ul)_. And Amount (fmol)=(10^6)*Amount (ng)/(Size from fragmentation (bp)*615.96+36.04) - both were correct | P | 240123/IL| 
| ONT Sequencing | ONT Start Sequencing | Samples can be loaded onto ONT flow cells, and required aliquots can be calculated based on the input amount in fmol. | Everything went as expected, and the correct values were calculated and set. | P | 240308/KSV| 
| ONT Sequencing | ONT Sequencing and Reloading | Samples can either get their reload volumes calculated or they can move on to the last seq step. | Everything went as expected, and the correct values were calculated and set. | P | 240308/KSV| 
| ONT Sequencing | ONT Finish Sequencing | Samples get their correct QC values parsed and set from the result files on Hasta. | Everything went as expected, and the correct values were calculated and set. | P | 240308/KSV| 

#### **Project resources:**
Screenshots are uploaded to the Initial testing [ONT v2 folder on Google Drive](https://drive.google.com/drive/folders/1NJXokxn0ZEuFjUPFKEke5oX7bu3xNWgU). Details on suggested changes in each step can be found in the [ONT v2 - Initial testing overview on Google Drive](https://drive.google.com/drive/folders/1EMRCFPQhgbcR-mgIPv-0yC2faPTU53Z_)
## **Conclusions:**

_Summarize conclusions here._

The tests passed after minor corrections, se comments for each step. The focus on the testing was to see that the most important functionality is working such as scripts and that the necessary UDFs are in place - and if needed -set as required. 

More testing will be done in the [validation repport](https://github.com/Clinical-Genomics/validations/pull/150). 

## **Sign off**

| Head of Unit Lab | Date |
|----------------- |------|
|  LF (on behalf of ALY)                            |      2024-03-14    |

- [x] Initial testing completed

**Comment by amandaraud** [comment]
@linnealafleur The initial testing is done, please have a look and sign off. Continuing with validation in separate issue.

**Comment by linnealafleur** [comment]
@amandaraud  the size selection step is missing here.
