### ISSUE TITLE
Add new "Sample delivered" automation and merge it with the rest of the Delivery v1 EPPs

### ISSUE THREAD

**Issue by Karl-Svard** [Clinical-Genomics/cg_lims#472]
Lims Issue
---------------

For definitions of headings below see [Basic Concepts](https://atlas.scilifelab.se/infrastructure/lims/basic_concepts/).

**Work Flow:** NovaSeq 6000 v1 / NovaSeq X v1
**Protocol:** Delivery v1
**Step:** Delivery

**Description:** We had two samples, ACC13583A5 and ACC13597A1, that partially passed the delivery step. This resulted in the automation "Sample delivered" executing successfully but not the later "Set Delivery Date, Method Document and update Arnold". The samples then looked to be delivered, even though they hadn't and no invoicing was conducted.

**Comment by idalindegaard** [comment]
Created a new EPP "Samples delivered, Set Delivery Date, Method Document and update Arnold" that merged the "Sample delivered" and "Set Delivery Date, Method Document and update Arnold" EPPs and set it to activate when exiting the step.

Tested with sample ACC13087A21 and it worked, see screenshot of the stage API (https://clinical-lims-stage.scilifelab.se/api/v2/samples/ACC13087A21)

<img width="876" alt="Screenshot 2024-03-06 at 15 50 24" src="https://github.com/Clinical-Genomics/cg_lims/assets/82438141/cf1a6ca7-3f6d-4612-8720-cce011a1a9a6">

Updated LIMS production as well
