### ISSUE TITLE
Set prepared_at for RML samples

### ISSUE THREAD

**Issue by islean** [Clinical-Genomics/cg_lims#493]
Lims Issue
---------------

**Description:** We are developing new functionality intending to summarize all cases' statuses within an order. This hinges on the cases having `prepared_at` set, which is currently not done for RML samples. Given that no lab prep is needed, they can be considered prepared upon receiving them. Could we set `prepared_at` for RML samples when they are received?

**Comment by Karl-Svard** [comment]
### Fixed in production

I've added the automation "Set Library Preped Date" to activate on exit for the following steps:
- Library Pooling NIPT (workflow: NIPT v2)
- CG002 - RML Library Pooling (workflow: RML v7)
