### ISSUE TITLE
Add Raredisease as option in LIMS

### ISSUE THREAD

**Issue by peterpru** [Clinical-Genomics/cg_lims#494]
Lims Issue
---------------

For definitions of headings below see [Basic Concepts](https://atlas.scilifelab.se/infrastructure/lims/basic_concepts/).

**Work Flow:** Full name here please!
**Protocol:** And here!
**Step:** Delivery

**Description:**

As part of the cg integration we would like to have Raredisease in LIMS. Raredisease has been added into atlas here: https://github.com/Clinical-Genomics/atlas/pull/2579

**Comment by Karl-Svard** [comment]
Done!
