### ISSUE TITLE
Improve sequencing planning and pooling, prio 1 project

### ISSUE THREAD

**Issue by EmiliaRegazzoni** [Clinical-Genomics/cg_lims#498]
Lims Issue
---------------

For definitions of headings below see [Basic Concepts](https://atlas.scilifelab.se/infrastructure/lims/basic_concepts/).

**Work Flow:** NovaSeq X
**Protocol:** NovaSeq X v1
**Step:** Define Run Format and Calculate Volumes (NovaSeq X)

## Description:
This is an updated request linked to a Prio 1 project: https://github.com/Clinical-Genomics/project-planning/issues/473. As explained in issue https://github.com/Clinical-Genomics/cg_lims/issues/449, the planning of NovaSeq X sequencing runs is often laborious and complex - it takes time and you need to take many factors into consideration. The process is not efficient or smooth, and there are ways to automate some steps.

The planning is done outside of LIMS in separate excel spreadsheets, such as [the total calculation for a whole flowcell](https://docs.google.com/spreadsheets/d/1paWC4f68dSFXduMMpRx9OoAYBE4SRzjxXhAu9vtf6BY/edit#gid=499440287), [TGA topup calculations](https://docs.google.com/spreadsheets/d/1pKy79OGleRPVOTZrbN42oZahbNm8H8ooX305lFtDRh8/edit#gid=1256940521) and [WGS topup calculations](https://docs.google.com/spreadsheets/d/1R01lFbBhxMu3IJrLBsOT_qmUQjdT8gzKLN2faGI_Ghg/edit#gid=0). Many values have to be looked up in LIMS steps such as Sequence Aggregation

### What we would like:
- Scripts that you can run, when you have gotten the reads to sequence, to adjust them according to the method:
    - Micro adjustments: All reads to sequence of micro bacteria are set to 3.5 M instead of 6 M when mixed with other libraries
    - TGA adjustments: All reads to sequence of pool are multiplied with 0.7 when mixed with other libraries
    - ClinSeq adjustments: All reads to sequence of pool are multiplied with 0.8 when mixed with other libraries
    - WGS adjustments: WGXXXXS120 reads to sequence are set from 2400 to 2200 M reads
    - WGS Top-Up adjustments: The reads left to sequence for samples lacking reads are multiplied with 1.25 for samples with reads left under 100 M and 1.5 if the reads missing are 100 or above
    - RNA adjustments: All reads to sequence are multiplied with 0.4 when mixed with other libraries
    - RML/ClinSeq, RNA topups: multiply by 1.2
    - Re-set micro and virus topups to 3.5 and 2 M reads, respectively.
- Easier way to calculate TGA top ups: could we add the pool a sample belongs to in the sequence aggregation step? This will help! Could we even add the number of reads the pool has gotten?
    - Could it be automatically calculated in the sequence aggregation step?
- Could the coverage calculation for wgs top ups be simplified? Can we import the coverage a sample has received?

### Suggestion/solution:

See LIMS issue #514

**Comment by EmiliaRegazzoni** [comment]
@idalindegaard @Karl-Svard what do you think is a realistic timeline is based on prioritisation of other ongoing high prio lims projects?

**Comment by Karl-Svard** [comment]
I would say June if we're quick. But vacations will of course slow down the work as we get closer to summer.

**Comment by EmiliaRegazzoni** [comment]
I think we can close this issue!

**Comment by Karl-Svard** [comment]
Ok! Feel free to reopen or create a new issue if you need any of the last two points solved as well:

> - Easier way to calculate TGA top ups: could we add the pool a sample belongs to in the sequence aggregation step? This will help! Could we even add the number of reads the pool has gotten?
Could it be automatically calculated in the sequence aggregation step?
> - Could the coverage calculation for wgs top ups be simplified? Can we import the coverage a sample has received?
