### ISSUE TITLE
Remove the Bravo Shirin from lims steps

### ISSUE THREAD

**Issue by FayKanellidou** [Clinical-Genomics/cg_lims#506]
Lims Issue
---------------

For definitions of headings below see [Basic Concepts](https://atlas.scilifelab.se/infrastructure/lims/basic_concepts/).

**Work Flow:** Microbial WGS v7, WGS PCR free v6
**Protocol:** CG002 - Normalization of microbial samples, Library validation QC wgs v4
**Step:** CG002 - Normalization of microbial samples for sequencing, CG002 - qPCR QC (Library Validation)

**Description:** Describe issue here!!!
We have removed from production the Bravo Shirin and would like to remove the option to select this instrument in the lims steps.

**Comment by FayKanellidou** [comment]
When it is done can you also please sign here?
https://github.com/Clinical-Genomics/validations/issues/204#event-12889407722

**Comment by idalindegaard** [comment]
Done, and I have signed @FayKanellidou

**Comment by FayKanellidou** [comment]
Thank youu!!
