### ISSUE TITLE
Hamilton Barcodes In LIMS

### ISSUE THREAD

**Issue by mayabrandi** [Clinical-Genomics/cg_lims#51]
- Create a new derived sample udf: **Barcode**
- In reception control - allways scann barcode to original derived sample
- Identifye which steps need a hamilton file.
- In the steps above, enable barcode scanning to output artifacts.
- Write scritp to generate hamilton file.

## Workflows to update
- [x] Twist
- [ ] Micro
- [ ] WGS
- [ ] MAF

**Comment by henrikstranneheim** [comment]
@mayabrandi Could you add the estimated effort?

**Comment by annaengstrom** [comment]
Would be nice if this could be done during the next 4 weeks

**Comment by cesve** [comment]
It is not needed to implement in all workflows at the same time. I think we should focus on Twist first and then Micro. Then the lab gets used to working with barcodes, then we can continue with wgs and maf.

Twist and micro are also the workflows where we need it the most at the moment.

**Comment by annaengstrom** [comment]
The most urgent need is Twist. We cannot put Hamilton KAPA 96 method into production without having this in place. The is a very high urgency into getting KAPA 96 into production.

**Comment by cesve** [comment]
**_Verification of implementation in TWIST wf_**

_Protocol Pre Processing TWIST v2_
_Step Reception Control TWIST_

![Screenshot 2021-05-21 at 08 31 31](https://user-images.githubusercontent.com/37171914/119092728-12f11f80-ba0f-11eb-924f-55b7046e12a9.png)
_Barcodes added to each tube_

**Comment by henrikstranneheim** [comment]
@mayabrandi Done?
