### ISSUE TITLE
New Watchmaker WGS workflow

### ISSUE THREAD

**Issue by idalindegaard** [Clinical-Genomics/cg_lims#520]
Lims Issue
---------------

For definitions of headings below see [Basic Concepts](https://atlas.scilifelab.se/infrastructure/lims/basic_concepts/).

**Work Flow:** WGS PCR-free Fragmentation v1
**Protocol:** Pre Processing WGS Fragmentation v1, Initial QC WGS Fragmentation v1, Library Prep WGS fragmentation v1, Library validation QC WGS Watchmaker v1, Normalization of WGS samples for sequencing v1
**Step:** many!

**Description:** 

New Watchmaker Human WGS DNA library prep is to replace the current TruSeq DNA PCR-free library prep and this needs a new workflow in LIMS. The method is soon ready to be implemented in production, see project issue [#504](https://github.com/Clinical-Genomics/project-planning/issues/504).

**What is needed:**
- [x] Outline the workflow requirements - [[WIP document here](https://docs.google.com/spreadsheets/d/1IRaDDk7Oaj_1sG2blGHDyc8xMroJFGc1pLwk2U9AkuU/edit?gid=1764864017#gid=1764864017)] ([From Carolina](https://docs.google.com/document/d/1eNZMOHxFuWDd6O3EfLPKuHHE8Na4W9YHQFZkS5-7GBA/edit))
- [x] New workflow in stage
- [x] Testing of workflow in stage
- [x] Arnold support @Karl-Svard [New arnold model outline](https://docs.google.com/document/d/1oLg5M-rc4m8em03oMGeIxMzUts-HLXVa96KiccumgG8/edit). Issue created https://github.com/Clinical-Genomics/cg_lims/issues/555
- [x] [Validation report](https://github.com/Clinical-Genomics/validations/pull/232) and more testing
- [x] [Implementation plan for the whole Watchmaker WGS project](https://github.com/Clinical-Genomics/validations/pull/235/files), [Implementation plan for LIMS workflow](https://github.com/Clinical-Genomics/validations/pull/240/files#diff-79d80c4ca31f3e6f406afb1792c1e5c389ca9576d78cef08d03786a1c6a6c973)
- [x] Update method with necessary LIMS instructions - CDM
- [x] Create workflow in production
- [x] Follow up samples in production - tested by CDM 2024-11-05

**Comment by idalindegaard** [comment]
#528 and #529 need to be fixed before we are able to finalize the workflow in stage

**Comment by AbiDalby** [comment]
Watchmaker WGS Workflow activated in LIMS production on 2024-10-31
