### ISSUE TITLE
Always add reads for negative controls - NovaSeq X v1 WF

### ISSUE THREAD

**Issue by karlnyr** [Clinical-Genomics/cg_lims#524]
We want to always add the number of reads to negative controls in the in NovaSeq X v1 workflow. We do not need to address the NovaSeq v3 workflow as we do not handle negative controls in this workflow any longer.

---------------

For definitions of headings below see [Basic Concepts](https://atlas.scilifelab.se/infrastructure/lims/basic_concepts/).

**Work Flow:** NovaSeq X v1
**Protocol:** NovaSeq X v1
**Step:**  Bcl Conversion & Demultiplexing (NovaSeq X)

We want to always add the number of reads, from previous and current sequencing runs, to a sample in the NovaSeq X v1 WF.

**Comment by karlnyr** [comment]
Once this issue is closed, we can revert the revert done in: https://github.com/Clinical-Genomics/cg/pull/3689

**Comment by karlnyr** [comment]
and close https://github.com/Clinical-Genomics/cg/issues/2871

**Comment by Karl-Svard** [comment]
fix in https://github.com/Clinical-Genomics/cg_lims/pull/531
