### ISSUE TITLE
Re-design pool_normalization script to normalize other samples than just pools - and make "Total Volume (uL)" work on process level

### ISSUE THREAD

**Issue by idalindegaard** [Clinical-Genomics/cg_lims#529]
Lims Issue
---------------

For definitions of headings below see [Basic Concepts](https://atlas.scilifelab.se/infrastructure/lims/basic_concepts/).

**Work Flow:** SARS-CoV-2 v4, Development Projects v5 and WGS PCR-free Fragmentation v1 (upcoming workflow)
**Protocol:** Normalization of [... ]samples/pool for sequencing
**Step:** Normalization of [... ]samples/pool for sequencing

**Description:** 

The script was created for normalizing pool volumes to a desired nM concentration. The calculations in the script work for non-pools as well and use "Total Volume (uL)", "Sample Volume (ul)", "Volume Buffer (ul)", "Concentration (nM)" (all on sample level) and "Final Concentration (nM)" (process level). These UDFs are defined in the script. 

It would be useful to re-name and design the script to not only mention pools, generalise the udfs needed so they can more easily be switched to other ones for other workflows in the future and also make the "Total Volume (uL)" work on process level, instead of defining it on every sample.

[link to script](https://github.com/Clinical-Genomics/cg_lims/blob/master/cg_lims/EPPs/udf/calculate/pool_normalization.py)

**Comment by Karl-Svard** [comment]
Linked to https://github.com/Clinical-Genomics/cg_lims/pull/533

**Comment by idalindegaard** [comment]
Changes tested, merged and deployed in stage and prod
