### ISSUE TITLE
Align delivery formats to our current delivery options

### ISSUE THREAD

**Issue by karlnyr** [Clinical-Genomics/cg_lims#548]
Lims Issue
---------------

**Work Flow:** Delivery
**Protocol:** Delivery v1
**Step:** Delivery v1?

**Description:** Currently we have the following delivery formats available:

<img width="276" alt="image" src="https://github.com/user-attachments/assets/a9a729f1-9ed1-4ce2-bb41-5ffea061eee1">

We need them to align with the delivery options we offer to our customers instead of this. 

Something like:

```plaintext
- raw-data
- raw-data+analysis
- raw-data+analysis+scout
- scout
- scout+analysis
- analysis
- statina
- internal (used for controls and projects)
- **optional**: fastq_qc
- **optional**: fastq_qc+analysis
```

**Comment by karlnyr** [comment]
We should have `fastq` instead of `raw-data` because that is what we have in `cg`

**Comment by Karl-Svard** [comment]
Fixed in prod!
