### ISSUE TITLE
Generalize make_pooling_map for other workflows than covid

### ISSUE THREAD

**Issue by idalindegaard** [Clinical-Genomics/cg_lims#552]
Lims Issue
---------------

For definitions of headings below see [Basic Concepts](https://atlas.scilifelab.se/infrastructure/lims/basic_concepts/basic_concepts/).

**Work Flow:** Full name here please!
**Protocol:** And here!
**Step:** Here to!

**Description:** 

The [pooling map](https://github.com/Clinical-Genomics/clinical_EPPs/blob/master/EPPs/make_twist_pooling_map.py) script used in _Pool samples for hybridization TWIST_ is still in the clinical_epps repository and needs some changes, for example what is described in issue #59. We found out that the [make pooling map](https://github.com/Clinical-Genomics/cg_lims/blob/master/cg_lims/EPPs/files/pooling_map/make_pooling_map.py) script in cg_lims is a good script that can be generalized for other workflows than covid. 

It would be good if the containers are colorized, so that pipetting errors are minimized. Also, it would be good if the order of the pools are the same as the placement in the plate.

Thoughts:
- click options for some of the columns in the table

**Comment by Karl-Svard** [comment]
Fixed in https://github.com/Clinical-Genomics/cg_lims/pull/559
