### ISSUE TITLE
Simplify moving between steps in lims

### ISSUE THREAD

**Issue by EmiliaRegazzoni** [Clinical-Genomics/cg_lims#553]
Lims Issue
---------------

For definitions of headings below see [Basic Concepts](https://atlas.scilifelab.se/infrastructure/lims/basic_concepts/basic_concepts/).

**Work Flow:** Queue samples for sequencing

**Description:** It would be great to not have to choose the step a sample should take and apply it when there is only one choice

<img width="983" alt="image" src="https://github.com/user-attachments/assets/8d843213-6257-49f5-8d6e-001449290990">

**Comment by AbiDalby** [comment]
Added new EPP "Set Next Steps 1" to automatically select "Mark protocol as complete" for the "Queue samples for sequencing v2" protocol and step. Set to run automatically when exiting "record details"

Changed from EPP "Set Next Steps" which was for log file position 3.

Test in stage showed that this works without needing to manually choose "Set protocol as complete".

![Image](https://github.com/user-attachments/assets/c035b759-791b-49da-be0b-9dbab5fb862d)

**Comment by AbiDalby** [comment]
Deployed the change in production for the protocol "Queue samples for sequencing v2" to allow smooth transfer to next protocol.

Continuation of this issue for all workflows and protocols can be found in [issue 560](https://github.com/Clinical-Genomics/cg_lims/issues/560)
