### ISSUE TITLE
Set date and missing reads automatically upon exit of Record details for RC WGS and TGA

### ISSUE THREAD

**Issue by idalindegaard** [Clinical-Genomics/cg_lims#554]
Lims Issue
---------------

For definitions of headings below see [Basic Concepts](https://atlas.scilifelab.se/infrastructure/lims/basic_concepts/basic_concepts/).

**Work Flow:** TWIST v8, WGS PCR-free Fragmentation v1 and WGS PCR free v6 
**Protocol:** Pre Processing, Initial QC
**Step:** Reception control

**Description:** 

When those doing RC get samples in tubes they first take all samples into the step, generate a barcode file and then abort the step before adding the barcode labels. This procedure is sometimes undertaken for samples that haven't yet arrived to the lab. The issue is that sometimes the "Set date, missing reads and Atlas Method Document" automation is clicked before aborting the step for those samples that haven't arrived, and then the "Received at" field is populated and shown in the order portal, which has caused confusion for the customers that know that the sample hasn't arrived yet. 

It was requested to have the "Set date, missing reads and Atlas Method Document" automation running automatically when the step (or Record details) is finished instead of a manual button, to get around the problem. 

In the Reception control steps of TWIST v8 and WGS PCR-free Fragmentation v1, there is already a "Check missing sample udfs and set Next Step Remove" EPP running automatically, so this was merged with the above-mentioned EPP. However, the check of missing sample udfs is not required since they will always be set with the new configuration.

**New EPP "Set date, missing reads, Atlas Method, Next Step remove"**

`bash -c -l "conda activate cg_lims && lims -c /home/glsai/.genologics.yaml epps -l {compoundOutputFileLuid0} -p {processLuid} udf copy process-to-sample -sudf 'Received at' -pudf 'date arrived at clinical genomics' && lims -c /home/glsai/.genologics.yaml epps -l {compoundOutputFileLuid0} -p {processLuid} udf set set-reads-missing-on-new-samples && lims -c /home/glsai/.genologics.yaml epps -l {compoundOutputFileLuid0} -p {processLuid} udf set method-document -pru 'Library Preparation Method'  -pru 'Library Preparation Method 1' -pru 'Library Preparation Method 2' -pru 'Supporting Procedure Document' -pru 'Supporting Procedure Document 1' -pru 'Supporting Procedure Document 2' -pru 'Equipment Document' -pru 'Equipment Document 1' -pru 'Equipment Document 2' -pru 'Sequencing Method' -pru 'Library preparation method' && /opt/gls/clarity/bin/java -jar /opt/gls/clarity/extensions/ngs-common/v5/EPP/ngs-extensions.jar -i {stepURI:v2} -u {username} -p {password} script:evaluateDynamicExpression -t false -h false -exp 'if (input.::Skip Buffer Exchange:: == true) { nextStep = ::REMOVE:: } else { nextStep = ::ADVANCE:: }' -log {compoundOutputFileLuid1}"`

**Comment by idalindegaard** [comment]
## Testing of new EPP "Set date, missing reads, Atlas Method, Next Step remove"

### TWIST v8

Tested below with set date and when one sample is chosen to skip buffer exchange:
<img width="671" alt="Screenshot 2024-10-31 at 12 46 48" src="https://github.com/user-attachments/assets/fde15e05-56d4-4175-8964-45e8ef37126e">
<img width="671" alt="Screenshot 2024-10-31 at 12 46 54" src="https://github.com/user-attachments/assets/7e9dac18-2c12-46d3-a5cb-3c13cf4f474c">
<img width="671" alt="Screenshot 2024-10-31 at 12 47 13" src="https://github.com/user-attachments/assets/e04d9406-db75-434c-9c01-d2643022c861">
<img width="651" alt="Screenshot 2024-10-31 at 12 47 32" src="https://github.com/user-attachments/assets/f1dbafdf-5ce2-43b8-b554-b15805702529">

Tested below when the date had not been set, the error is detected and the user has to go back and set it to proceed:
<img width="651" alt="Screenshot 2024-10-31 at 13 45 55" src="https://github.com/user-attachments/assets/8b8ad17f-fc2f-42c4-a011-3117b297b730">

### WGS PCR-free Fragmentation v1

<img width="651" alt="Screenshot 2024-10-31 at 12 52 25" src="https://github.com/user-attachments/assets/1c51728e-025b-44c8-a9f0-d338a5e98d9c">
<img width="651" alt="Screenshot 2024-10-31 at 12 52 46" src="https://github.com/user-attachments/assets/2f9925d0-1ef7-490a-afb3-369e957d8bb5">
<img width="651" alt="Screenshot 2024-10-31 at 12 53 05" src="https://github.com/user-attachments/assets/e996de8e-e8d9-4ddf-bdaa-23449b6ee881">

New EPP works as intended!

**Comment by Karl-Svard** [comment]
Nice work! 🙌
