### ISSUE TITLE
Remove "delivery format"

### ISSUE THREAD

**Issue by RasmusBurge-CG** [Clinical-Genomics/cg_lims#557]
Lims Issue
---------------

For definitions of headings below see [Basic Concepts](https://atlas.scilifelab.se/infrastructure/lims/basic_concepts/basic_concepts/).

**Work Flow:** Delivery (only one step)

**Description:** 

In the step delivery we currently need to add "delivery format", this is stored in statusdb, and does not need to be stored in LIMS. Also, the delivery format might change, this might cause confusion when there is different information regarding one case.

This will remove unneeded work, HIGH impact EASY to remove!

**Comment by beatrizsavinhas** [comment]
Closing this in favour of https://github.com/Clinical-Genomics/project-Automatic-Delivery/issues/16 to be implemented in the Automatic Delivery project.
