### ISSUE TITLE
New file in Sars-CoV-2 WF

### ISSUE THREAD

**Issue by cesve** [Clinical-Genomics/cg_lims#56]
Lims Issue
---------------

**Work Flow:** SARS-CoV-2 v1
**Protocol:** Library Prep (Cov) v1
**Step:** Library Preparation (Cov) **_and_** Pooling and Clean-up (Cov)

**Description:** When automating the Sars-CoV-2 library preparation on Hamilton a file is needed. The following information is needed:

- LIMS ID - submitted sample
- Sample Well position - input artifact
- Destination Well position - output artifact 
- Index Well position. - as in twist make_kapa_csv.py

The headings in the file should be: 
- LIMS ID
- Sample Well
- Destination Well
- Index Well

Additional information:
- The file must be sorted by Sample Well position column wise (A1-H1, A2-H2 etc.)
- The wells should be in format A1, B1 etc.
- The file should be in format *.txt and comma seperated.

**Comment by cesve** [comment]
@henrikstranneheim @mayabrandi when do you think we can do this? It is quite urgent since we need it for the automation of Sars-CoV-2 method. Would be great to have it in place within 2-3 weeks. Thanks!

**Comment by cesve** [comment]
@henrikstranneheim @mayabrandi when do you think we can do this? It is quite urgent since we need it for the automation of Sars-CoV-2 method. Would be great to have it in place within 2-3 weeks. Thanks!

**Comment by cesve** [comment]
@henrikstranneheim or @mayabrandi do you have an estimation of when you think we can do this? Thanks a lot!

**Comment by henrikstranneheim** [comment]
I have not had a chance to talk to @mayabrandi yet but I think we start working on this sometime next week. We have to prioritize the NIPT project as it is on a very tight deadline.

**Comment by cesve** [comment]
> I have not had a chance to talk to @mayabrandi yet but I think we start working on this sometime next week. We have to prioritize the NIPT project as it is on a very tight deadline.

Great, thanks Henrik!

**Comment by mayabrandi** [comment]
I expect it to take no more than a day @henrikstranneheim Cissi, can you add a urgency label? @cesve

**Comment by cesve** [comment]
# Verification Test
The new script for creating the Covid file has been added to the following steps:

Work Flow: SARS-CoV-2 v1
Protocol: Library Prep (Cov) v1
Step: Library Preparation (Cov) and Pooling and Clean-up (Cov)

## Step Library Preparation (Cov)

The file was created successfully and contained the correct information. The samples are not pooled in this step but they still have a destination well in the file. That information is not used but as we wanted to use the same script for both LIMS steps we decided to include that information. The file works in the protocol on Hamilton instrument.

<img width="498" alt="Screenshot 2021-06-15 at 21 24 56" src="https://user-images.githubusercontent.com/37171914/122216322-8d954980-ceac-11eb-898e-17cd40a58ff9.png">

[92-1454623-sars-cov2-hamilton-prep.txt](https://github.com/Clinical-Genomics/cg_lims/files/6662850/92-1454623-sars-cov2-hamilton-prep.txt)

## Step Pooling and Clean-up (Cov)

The file was created successfully and contained the correct information. The indecies are not used in this step of the protocol or in this LIMS step. Therefor a "-" is written instead of an index well position. The file works in the protocol on Hamilton instrument.

<img width="493" alt="Screenshot 2021-06-16 at 14 01 06" src="https://user-images.githubusercontent.com/37171914/122216410-ab62ae80-ceac-11eb-8782-d8ae20bd37e6.png">

[92-1454644-sars-cov2-hamilton-prep.txt](https://github.com/Clinical-Genomics/cg_lims/files/6662861/92-1454644-sars-cov2-hamilton-prep.txt)

**Comment by cesve** [comment]
@mayabrandi jag lade in testet här också, kan du stänga issue:n och länka till PR när du är klar?

**Comment by mayabrandi** [comment]
Done by this pr: https://github.com/Clinical-Genomics/cg_lims/pull/58
