### ISSUE TITLE
Advanced LIMs search for retrieving data about TGA samples 

### ISSUE THREAD

**Issue by evitser** [Clinical-Genomics/cg_lims#565]
Lims Issue
---------------

For definitions of headings below see [Basic Concepts](https://atlas.scilifelab.se/infrastructure/lims/basic_concepts/basic_concepts/).

**Work Flow:** TWIST v8
**Protocol:**  Library validation QC TWIST v2, Library validation QC TWIST (post hyb)
**Step:**  QuantiT QC (Library validation) TWIST, Tapestation QC TWIST

**Description:** 
The aim is to retrieve some LIMS data about all passed TGA samples processed in CG during 2024 with apptags: PAN, PAZ and EXO. In details, LIMS ID, customer number, sample source and prep date are needed. Then, we will be able to look into more details about the samples like concentration, size, tapestation, etc.

**Comment by idalindegaard** [comment]
The desired data could be retrieved with Advanced search, looked at it together with Evi.
