### ISSUE TITLE
TWIST / TGA, colorize the pooling map based on source container

### ISSUE THREAD

**Issue by RasmusBurge-CG** [Clinical-Genomics/cg_lims#59]
Lims Issue
---------------

**Work Flow:** TWIST v2
**Protocol:** Target Enrichment TWIST v2
**Step:** Pool samples for hybridization TWIST

**Description:** 
To the point: Update the placement map to color the rows based on the source container.

During a prep of TGA one sample was taken from the wrong plate [1]. This was caused due to inexperience, focusing too much on the volume of sample, source well and which well to transport the sample to. In order to prevent this error to occur again it was suggested that the rows could be colored based on the source container. Then samples from TGA210524 would be one color and TGA210517 would be another (See fig 1). This would make the laborant directly aware if a pool would contain samples from multiple plates, and would make it even harder to accidentally miss this information. 

![](https://user-images.githubusercontent.com/80392398/120205654-7eff2f00-c22a-11eb-817d-4a5a74a0cb9a.png)
*Fig 1. The placement map used during the deviation.*

[1] issue #55, https://github.com/Clinical-Genomics/Deviations/issues/55

**Comment by henrikstranneheim** [comment]
@mayabrandi Shall we close this one?

**Comment by mayabrandi** [comment]
yes

**Comment by cesve** [comment]
Hej Maya,

Color coding placement map doesn't work in the step Pool samples for hybridization TWIST. Can you check this when you have time?

**Comment by EmiliaRegazzoni** [comment]
@Karl-Svard @idalindegaard @AbiDalby If we can include this in issue #456 as well I think that is a good idea! it is easuy to make an error while pooling

**Comment by idalindegaard** [comment]
Thanks for the reminder, we will look into this as well

**Comment by Karl-Svard** [comment]
Fixed in https://github.com/Clinical-Genomics/cg_lims/pull/559
