### ISSUE TITLE
Add step in protocol Library Prep (Cov) v1

### ISSUE THREAD

**Issue by cesve** [Clinical-Genomics/cg_lims#84]
Lims Issue
---------------

**Work Flow:** SARS-CoV-2-v2
**Protocol:** Library Prep (Cov) v1
**Step:** New Step, "Step 1 Sample placement"

**Description:** A file is generated in Step Library Preparation (Cov) where the input in "Sample well" is the sample source well. Since we don't have any sample placement step before this step, the "Sample well" is in this case the same as "Original well". This will be problematic if more than one original plate is prepared at the same time. It will also be problematic when adding negative controls.

A solution is to have a step before the Library Preparation (Cov)-step. In this step a placement of the samples is performed. No other information is needed.

**Comment by cesve** [comment]
@mayabrandi if you give me some guidance and support I can try to add it myself?

**Comment by cesve** [comment]
A new version of the SARS-CoV-2 workflow has been created. It's named SARS-CoV-2 v3.

The following have been changed/added/removed:

**Protocol Initial QC (Cov) v1**
_No changes_

**Protocol Library Prep (Cov) v2**

- Step "Sample Placement (Cov)" has been added. 
In this step there is a sample placement. There are process UDF's for Method document, Document version and lot no for Nuclease-free water in the Record Details view. There is also button for creating a Placement map in this step. The original well/container is shown in this placement map. The script used here is named: "Placement Map (Original Well)"

- Step Library Preparation (Cov) has been modified

> The script Calculate H2O has been deactivated. The reason for removing them is that it's not needed anymore as the customer always sends more than 20 ul of the samples. I.e. there is no need to add water to the samples.

> A new script for creating a placement map has been added. The reason for this is that we don't want the H2O volume visible in the placement map.

> Process UDF's "Total Volume" and "PCR-machine: 37 degrees incubation" have been removed.

> Sample UDF's "Volume H2O (ul)" has been removed.

- Step Pooling and Clean-up  (Cov)
_No changes_

**Protocol Library validation QC (Cov) v1**
_No changes_

**Protocol NovaSeq v3**
_No changes_

**Protocol Delivery v1**
_No changes_

**Comment by cesve** [comment]
_**Verification of the new version of the workflow**_

49 samples were added to the new workflow in 2 separate orders:

1. 48 samples in a plate (ACC8442A1-A48) #184512
2. 1 sample in a tube (ACC8443A1) #913672

The samples are run through protocols:
1. Protocol 
2. Library Prep (Cov) v2
3. Library validation QC (Cov) v1

The steps in protocol **_Library Prep (Cov) v2_** are documented since they have been modified:

**_Step "Sample Placement (Cov)_**
![Screenshot 2021-09-10 at 13 57 14](https://user-images.githubusercontent.com/37171914/132849933-665f5b39-3c50-4dfc-a4f3-f9482b4bb58a.png)
_Samples added in the step_

![Screenshot 2021-09-10 at 13 58 00](https://user-images.githubusercontent.com/37171914/132850044-126cf21e-a442-4a6e-98dc-9196efeb8cdd.png)
_Sample placement_

![Screenshot 2021-09-10 at 13 58 56](https://user-images.githubusercontent.com/37171914/132850142-41786e8f-8f5f-4103-863e-84bf727e6a83.png)
_Script run succssful_

![Screenshot 2021-09-10 at 14 00 16](https://user-images.githubusercontent.com/37171914/132850316-436d41df-2055-4a8d-8a8c-d525860a5efa.png)
_Sample placement is created. It contains the wanted information and the information is correct(Project, Sample name, Sample ID (same as LIMS ID), Original container and Original well)._

**Comment by mayabrandi** [comment]
The new workflow can be put in production without any further configuration changes.

**Comment by cesve** [comment]
SARS-CoV-2 v2 is archived and lab team has been informed about the new version of the workflow.
