### ISSUE TITLE
EPP: aliquot_covaris_microbial.py

### ISSUE THREAD

**Issue by barrystokman** [Clinical-Genomics/cg_lims#86]
Lims Issue
---------------

**Work Flow:** CG001 Microbial WGS (archived)/CG002 Microbial WGS (archived)
**Protocol:** CG002 - Nextera Microbial WGS/CG003 - Nextera Microbial WGS
**Step:** CG002 - Normalization of microbial samples

**Description:** Implement EPP `aliquot_covaris_microbial.py`

**Comment by barrystokman** [comment]
```
(cg_lims) bash-4.2$ python opt/clinical_EPPs/clinical_EPPs/check_configuration.py -s aliquot_covaris_microbial.py
INFO:AUTOMATION: Searching for 'aliquot_covaris_microbial.py'.
INFO:Button: 2. Calculate Aliquot Volume
INFO:Bash string: bash -c "/home/glsai/miniconda3/envs/epp_master/bin/aliquot_covaris_microbial.py --pid {processLuid}"
INFO:Processes: ['807'] 
```

**Comment by barrystokman** [comment]
Workflows `CG001 Microbial WGS` and `CG002 Microbial WGS` are both archived.

**Comment by mayabrandi** [comment]
Hej! The script is being activly used in **CG002 - Normalization of microbial samples** as part of protocol **Nextera Microbial WGS v4** in workflow **Microbial WGS v6**! So it can not be archived! It should be transfered to cg_lims though!

**Comment by barrystokman** [comment]
Good thing you checked, I missed that! :) I'll pick it up after https://github.com/Clinical-Genomics/cg_lims/issues/93 and https://github.com/Clinical-Genomics/cg_lims/issues/94

**Comment by barrystokman** [comment]
PR here: https://github.com/Clinical-Genomics/cg_lims/pull/133
