### ISSUE TITLE
Transfer check_indexes_in_pools.py

### ISSUE THREAD

**Issue by barrystokman** [Clinical-Genomics/cg_lims#88]
Lims Issue
---------------

**Work Flow:** tbd
**Protocol:** tbd
**Step:** tbd

**Description:** Implement EPP `check_indexes_in_pools.py`

**Comment by barrystokman** [comment]
![image](https://user-images.githubusercontent.com/26384108/133386049-3eb1ac0a-97d2-43f3-aa21-d32907f1fc9d.png)

**Comment by barrystokman** [comment]
### Check Duplicate Index
Automation use enabled here:
Master Steps -> Steps -> Protocols -> Workflows (active only):

| # | Master Step | Step | Protocol | Workflow | Check Duplicate Index |
|-|-|-|-|-|-|
|1. | pool samples TWIST v2  | Pool samples for hybridization TWIST |Target Enrichment TWIST v2 |TWIST v4 | Y |
|2. | Pool Samples (iSeq) v1  |  | | | |

**Comment by Karl-Svard** [comment]
Duplicate issue: https://github.com/Clinical-Genomics/cg_lims/issues/208
