### ISSUE TITLE
Add a Planning for hyb step in TWIST wf

### ISSUE THREAD

**Issue by cesve** [Clinical-Genomics/cg_lims#92]
Lims Issue
---------------
**Work Flow:** TWIST v3
**Protocol:** Target Enrichment TWIST v2
**Step**: Pool samples for hybridization TWIST

Description: We would like to add a planning step before the step Pool samples for hybridization TWIST.

From ALY:
"Due to different facts around the samples, we have to bring samples into a LIMS step, run a script, check if it is fine, if it is not, we have to remove all samples, start all over again, run the script, and we typically do this several times. The problem is that we cannot remove single samples from the step and and bring them back. The whole process takes a few hours which is a major problem."

In a meeting with ALY, MB, VK, OL and CS it was decided to, to reduce time spent on this we will add planning step before the actual pooling is done.

In the planning step it should be possible to write a pool name (at sample level) and run the script "Calculate Volumes" that is used in the step Pool samples for hybridization TWIST. It should also be possible to change the pooling name for samples and run the script again. It should also be possible to run the script Make Pooling Map to see why a sample or pool gets a red flag.

When done with the planning step it should be possible to choose the next step, either Pool samples for hybridization TWIST or repeat step (the planning).

The samples that are pushed forward to Pool samples for hybridization TWIST should have the UDF: "Pool name" that was added in the planning step, visible in the queue to the step.

**Comment by cesve** [comment]
@RasmusBurge-CG can you have a look at this together with me and MB?

**Comment by RasmusBurge-CG** [comment]
@cesve Yes!

**Comment by cesve** [comment]
A new workflow has been created on stage TWIST v8. 

It is identical to the previous version except that an additional step was added in protocol **_Target Enrichment TWIST v4_**.

The new step is named **_Pool Planning TWIST_** and will be step 1 in the protocol.
The step type is "No Outputs" as we don't want to create any new artifacts in this step.

There will not be any Process UDF's, only one for comments.

These artifact UDF's are added:
<img width="229" alt="Screenshot 2022-06-23 at 15 01 19" src="https://user-images.githubusercontent.com/37171914/175304796-30e77363-bd75-44ee-8fdf-6c9a250a3dab.png">

A new global field was created "Pool Name". Here the user can add a name or a number to identify which samples to place in which pool. 

There won't be any automations to start with. In the near future we want to have scripts that calculates the volumes (similiar to the one we have in the next step), we also want to create a pooling map and check for duplicate indecies. The point with this step is that it will be much easier to get an overview of the sample details and it will hopefully make the planning easier. It's also possible to download the sample details to an excel file.

This solution was shown in lab meeting 2022-06-15 and we agreed on adding the step even though the scripts are missing. We will add it to Production in August to avoid issues during summer holiday.

We will also make some tests:

- [ ] Check samples with same indecies (stage)
- [ ] Check that samples come to the correct wf when skipping/not skipping buffer exchange (prod)
- [ ] Run some samples through the workflow first on stage and then on prod.

**Comment by RasmusBurge-CG** [comment]
Created a new project on stage named _888888_. The sample list was taken from three projects in production. 

[twist8_test.xlsx](https://github.com/Clinical-Genomics/cg_lims/files/9248956/twist8_test.xlsx)

**Comment by idalindegaard** [comment]
**Conclusion:**
These ideas have been considered in the [verification of the new workflow TWIST v8](https://github.com/Clinical-Genomics/cg_lims/issues/377) so you can follow the progression there. The new change has been what was last discussed in this issue (2022-06-15), where a new planning step has been implemented but no new scripts. They can be added later if needed. This issue can then be re-opened if there's a need. Closing now.
